### ISSUE TITLE
taier ui 编译报错

### ISSUE THREAD

**Issue by liuzhiyuan0502** [DTStack/Taier#1010]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

npm run build

> build
> umi build

× Webpack
  Compiled with some errors in 1.84m

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 ERROR  Failed to compile with 2 errors                                                                                                                                         15:22:33

 error  in ./node_modules/@dtinsight/molecule/node_modules/monaco-editor/esm/vs/language/html/monaco.contribution.js

Module parse failed: Unexpected token (130:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     dispose() {
|       onLanguageListener.dispose();
>       mode?.dispose();
|       mode = void 0;
|     }

 @ ./node_modules/@dtinsight/molecule/esm/monaco/index.js 7:0-64
 @ ./src/utils/completion.ts
 @ ./src/utils/index.ts
 @ ./src/pages/index.tsx
 @ ./src/.umi-production/core/routes.ts
 @ ./src/.umi-production/umi.ts
 @ multi ./src/.umi-production/umi.ts

 error  in ./node_modules/@dtinsight/molecule/node_modules/monaco-editor/esm/vs/language/typescript/tsMode.js

Module parse failed: Unexpected token (686:30)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       }
|       const tags = [];
>       if (entry.kindModifiers?.indexOf("deprecated") !== -1) {
|         tags.push(monaco_editor_core_exports.languages.CompletionItemTag.Deprecated);
|       }

 @ ./node_modules/@dtinsight/molecule/node_modules/monaco-editor/esm/vs/language/typescript/monaco.contribution.js 232:11-29
 @ ./node_modules/@dtinsight/molecule/esm/monaco/index.js
 @ ./src/utils/completion.ts
 @ ./src/utils/index.ts
 @ ./src/pages/index.tsx
 @ ./src/.umi-production/core/routes.ts
 @ ./src/.umi-production/umi.ts
 @ multi ./src/.umi-production/umi.ts

Child

    ERROR in ./node_modules/@dtinsight/molecule/node_modules/monaco-editor/esm/vs/language/html/monaco.contribution.js 130:11
    Module parse failed: Unexpected token (130:11)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    |     dispose() {
    |       onLanguageListener.dispose();
    >       mode?.dispose();
    |       mode = void 0;
    |     }
     @ ./node_modules/@dtinsight/molecule/esm/monaco/index.js 7:0-64
     @ ./src/utils/completion.ts
     @ ./src/utils/index.ts
     @ ./src/pages/index.tsx
     @ ./src/.umi-production/core/routes.ts
     @ ./src/.umi-production/umi.ts
     @ multi ./src/.umi-production/umi.ts

    ERROR in ./node_modules/@dtinsight/molecule/node_modules/monaco-editor/esm/vs/language/typescript/tsMode.js 686:30
    Module parse failed: Unexpected token (686:30)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    |       }
    |       const tags = [];
    >       if (entry.kindModifiers?.indexOf("deprecated") !== -1) {
    |         tags.push(monaco_editor_core_exports.languages.CompletionItemTag.Deprecated);
    |       }
     @ ./node_modules/@dtinsight/molecule/node_modules/monaco-editor/esm/vs/language/typescript/monaco.contribution.js 232:11-29
     @ ./node_modules/@dtinsight/molecule/esm/monaco/index.js
     @ ./src/utils/completion.ts
     @ ./src/utils/index.ts
     @ ./src/pages/index.tsx
     @ ./src/.umi-production/core/routes.ts
     @ ./src/.umi-production/umi.ts
     @ multi ./src/.umi-production/umi.ts
null
 info  如果你需要进交流群，请访问 https://fb.umijs.org
build failed
Error: build failed
    at J:\packages\tiaer\Taier-1.3.0\Taier-1.3.0\taier-ui\node_modules\@umijs\bundler-webpack\lib\index.js:177:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (J:\packages\tiaer\Taier-1.3.0\Taier-1.3.0\taier-ui\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:147581:10), <anony
mous>:60:1)
    at AsyncSeriesHook.lazyCompileHook (J:\packages\tiaer\Taier-1.3.0\Taier-1.3.0\taier-ui\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:147518:20)
    at onCompiled (J:\packages\tiaer\Taier-1.3.0\Taier-1.3.0\taier-ui\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:98603:21)
    at J:\packages\tiaer\Taier-1.3.0\Taier-1.3.0\taier-ui\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:99013:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (J:\packages\tiaer\Taier-1.3.0\Taier-1.3.0\taier-ui\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:147581:10), <anony
mous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (J:\packages\tiaer\Taier-1.3.0\Taier-1.3.0\taier-ui\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:147518:20)
    at J:\packages\tiaer\Taier-1.3.0\Taier-1.3.0\taier-ui\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:99010:31
 info  如果你需要进交流群，请访问 https://fb.umijs.org

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mortalYoung** [comment]
目前 master 分支无法复现，可以给一下 Taier 的版本吗
