### ISSUE TITLE
[Question][Shell任务] 执行shell任务报 java.lang.NoSuchFieldError: PROJECT_TYPE

### ISSUE THREAD

**Issue by caiyuyux** [DTStack/Taier#1019]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

报错如图所示

![image](https://user-images.githubusercontent.com/8185717/228706311-972da78e-8a8a-4a3d-8671-bb7283819836.png)

--- 
更多的日志

![image](https://user-images.githubusercontent.com/8185717/228706892-89f96041-7119-4f4b-989e-27d6104f78c6.png)
![image](https://user-images.githubusercontent.com/8185717/228706975-e1283b1b-1fa9-4720-99ca-6f3121a7bb35.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caiyuyux** [comment]
@bnyte @vainhope 应该不是日志包的问题，我之前在群咨询过，好像是 cdh 集群没有兼容的问题
![image](https://user-images.githubusercontent.com/8185717/231028833-53d2d95c-46c8-46da-93d6-fbcaf2e79a8b.png)

**Comment by vainhope** [comment]
https://github.com/DTStack/Taier/issues/1026 相同问题 已修复
