### ISSUE TITLE
新建的工作流任务，

### ISSUE THREAD

**Issue by xjs1983boy** [DTStack/Taier#1030]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

新建的工作流任务，建了几个数据同步节点并做了保存，然后再双击去数据同步节点，添加数据同步任务，没有问题。
如果是在没有保存数据同步节点的情况下去填加数据同步任务，就会导致节点显示不出来，严重的情况还会导致之前保存好的数据节点也不能显示出来。

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/33441983/230284420-c5212e96-83c8-45bf-af8d-a1c646d57d90.png">
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/33441983/230284607-182c9b76-f476-4531-9cb8-f10e14a5ab34.png">

### What you expected to happen

新建的工作流任务，建了几个数据同步节点并做了保存，然后再双击去数据同步节点，添加数据同步任务，没有问题。
如果是在没有保存数据同步节点的情况下去填加数据同步任务，就会导致节点显示不出来，严重的情况还会导致之前保存好的数据节点也不能显示出来。

### How to reproduce

新建的工作流任务，建了几个数据同步节点并做了保存，然后再双击去数据同步节点，添加数据同步任务，没有问题。
如果是在没有保存数据同步节点的情况下去填加数据同步任务，就会导致节点显示不出来，严重的情况还会导致之前保存好的数据节点也不能显示出来。

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mortalYoung** [comment]
我按照你的复现步骤在 master 无法复现，可以提供一下版本或者更加详细一些的步骤吗
