### ISSUE TITLE
[Bug] [flinksql Standalone ]taier1.3版本 udf jar找不到

### ISSUE THREAD

**Issue by kannon007** [DTStack/Taier#1041]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

日志显示jar 下载成功，但本地临时目录中并未找到这个jar
![51f7e1aa921aee259bee49947433312c](https://user-images.githubusercontent.com/10329981/231638938-b04789cf-a1fb-4629-91a0-76618abba1b4.png)

flink 日志
![1681355845409](https://user-images.githubusercontent.com/10329981/231639947-7e909633-54cf-4091-82da-4d06989f609a.png)

### What you expected to happen

看源码应该是下载成功了的
![image](https://user-images.githubusercontent.com/10329981/231640259-a8de120f-ae03-4d17-a944-6b996a1215a5.png)

看下是不是有其他 环节自动清空了 tmp 目录

### How to reproduce

flink Standalone  模式 运行 flink sql

### Version

v1.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
我这边验证一下

**Comment by milfoil-w** [comment]
> 我这边验证一下

你好，有复现吗

**Comment by vainhope** [comment]
参考下 https://github.com/DTStack/Taier/issues/1067
有复现的步骤吗 @milfoil-w
