### ISSUE TITLE
[报错][任务] 执行任务 队列提示报错 这个是怎么回事

### ISSUE THREAD

**Issue by 617450941** [DTStack/Taier#1057]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

执行任务 队列提示报错 这个是怎么回事
{
  "id": 3,
  "jobId": "4lcmonrn0270",
  "jobName": "runJob_run_sync_task_同步数据_1682063381534_20230421154941",
  "computeType": 1,
  "stage": 4,
  "jobInfo": "{\"computeType\":1,\"exeArgs\":\"-job %7B%22job%22%3A%7B%22content%22%3A%5B%7B%22reader%22%3A%7B%22parameter%22%3A%7B%22password%22%3A%22aj7mEaiJp6fhzCnL%22%2C%22column%22%3A%5B%7B%22name%22%3A%22goods_id%22%2C%22type%22%3A%22INT+UNSIGNED%22%2C%22key%22%3A%22goods_id%22%7D%2C%7B%22name%22%3A%22goods_price%22%2C%22type%22%3A%22DECIMAL%22%2C%22key%22%3A%22goods_price%22%7D%2C%7B%22name%22%3A%22goods_name%22%2C%22type%22%3A%22VARCHAR%22%2C%22key%22%3A%22goods_name%22%7D%2C%7B%22name%22%3A%22goods_details%22%2C%22type%22%3A%22VARCHAR%22%2C%22key%22%3A%22goods_details%22%7D%5D%2C%22connection%22%3A%5B%7B%22sourceId%22%3A1%2C%22password%22%3A%22aj7mEaiJp6fhzCnL%22%2C%22jdbcUrl%22%3A%5B%22jdbc%3Amysql%3A%2F%2F192.168.1.61%3A3306%2Ftest1%22%5D%2C%22type%22%3A1%2C%22table%22%3A%5B%22my_goods%22%5D%2C%22username%22%3A%22test1%22%7D%5D%2C%22sourceIds%22%3A%5B1%5D%2C%22username%22%3A%22test1%22%7D%2C%22name%22%3A%22mysqlreader%22%7D%2C%22writer%22%3A%7B%22parameter%22%3A%7B%22postSql%22%3A%5B%5D%2C%22password%22%3A%22bA2S2KkBzn4cmKsY%22%2C%22column%22%3A%5B%7B%22name%22%3A%22goods_id%22%2C%22isPart%22%3Afalse%2C%22type%22%3A%22INT+UNSIGNED%22%2C%22key%22%3A%22goods_id%22%7D%2C%7B%22name%22%3A%22goods_price%22%2C%22isPart%22%3Afalse%2C%22type%22%3A%22DECIMAL%22%2C%22key%22%3A%22goods_price%22%7D%2C%7B%22name%22%3A%22goods_name%22%2C%22isPart%22%3Afalse%2C%22type%22%3A%22VARCHAR%22%2C%22key%22%3A%22goods_name%22%7D%2C%7B%22name%22%3A%22goods_details%22%2C%22isPart%22%3Afalse%2C%22type%22%3A%22VARCHAR%22%2C%22key%22%3A%22goods_details%22%7D%5D%2C%22connection%22%3A%5B%7B%22jdbcUrl%22%3A%22jdbc%3Amysql%3A%2F%2F192.168.1.61%3A3306%2Fcsc%22%2C%22table%22%3A%5B%22my_goods%22%5D%7D%5D%2C%22sourceIds%22%3A%5B2%5D%2C%22preSql%22%3A%5B%5D%2C%22username%22%3A%22csc%22%7D%2C%22name%22%3A%22mysqlwriter%22%7D%7D%5D%2C%22setting%22%3A%7B%22restore%22%3A%7B%22isRestore%22%3Afalse%2C%22isStream%22%3Afalse%7D%2C%22speed%22%3A%7B%22readerChannel%22%3A1%2C%22writerChannel%22%3A1%2C%22bytes%22%3A-1048576%2C%22channel%22%3A1%7D%7D%7D%7D\",\"generateTime\":1682063381629,\"groupName\":\"default_default\",\"jobId\":\"4lcmonrn0270\",\"lackingCount\":0,\"maxRetryNum\":0,\"name\":\"runJob_run_sync_task_同步数据_1682063381534_20230421154941\",\"priority\":1682064381629,\"sqlText\":\"\",\"submitExpiredTime\":0,\"taskParams\":\"mr.job.parallelism = 1\\n\",\"taskType\":2,\"tenantId\":1}",
  "nodeAddress": "172.28.0.3:8090",
  "jobResource": "sync_default_default_batch_FlinkYarnSession2",
  "jobPriority": 1682064381644,
  "isFailover": 0,
  "waitReason": "Flink session cluster is unhealthy, waiting to reboot cluster.",
  "tenantId": null,
  "gmtCreate": 1682063381000,
  "gmtModified": 1682063381000,
  "isDeleted": 0,
  "status": 25,
  "execStartTime": null,
  "generateTime": 1682063381000,
  "waitTime": "17秒",
  "tenantName": "taier"
}

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 617450941** [comment]
添加的集群都测试通过的

**Comment by vainhope** [comment]
参考下这个问题呢
https://github.com/DTStack/Taier/issues/372

**Comment by 617450941** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by 617450941** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
