### ISSUE TITLE
[Question][自定义函数] 自定义函数的jar包为什么会读取失败

### ISSUE THREAD

**Issue by 617450941** [DTStack/Taier#1067]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

![image](https://user-images.githubusercontent.com/7607957/234267454-80d720d3-2a2e-4fdd-b3dc-7be496e163a7.png)
如上面的提示 已经上传到sftp成功了的
![image](https://user-images.githubusercontent.com/7607957/234267564-8404966f-7cb8-4c67-8ea8-f1480c32ed80.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/235332917-259ae78d-b50c-43a6-a09e-1c8dde4156e1.png)
![image](https://user-images.githubusercontent.com/18212930/235332929-1ab19571-0377-4d06-9a28-2081f1afb879.png)


![image](https://user-images.githubusercontent.com/18212930/235332948-df21aace-1a82-4d6e-8d9a-c2062e38bc09.png)


1.4版本暂时无法复现 可以说明下复现步骤和版本吗 @617450941

**Comment by 617450941** [comment]
我是docker-compose部署的  按这篇文档部署的 https://dtstack.github.io/Taier/docs/quickstart/deploy/docker

**Comment by 617450941** [comment]
sftp组件也是测试通过的  sftp组件用的是这个 atmoz/sftp docker镜像部署的

**Comment by vainhope** [comment]
可以看下Taier.log有什么关系信息 主要逻辑在com.dtstack.taier.flink.FlinkClient#beforeSubmitFunc上
或者用1.4版本试试呢

**Comment by 617450941** [comment]
错误信息 如下 
rallelism.default=1\\ntaskmanager.numberOfTaskSlots=1\\njobmanager.memory.process.size=1g\\ntaskmanager.memory.process.size=2g\\nexecution.checkpointing.interval=5min\\nexecution.checkpointing.externalized-checkpoint-retention=RETAIN_ON_CANCELLATION\\ntable.exec.state.ttl=1d\\nlog.level=INFO\",\"taskType\":5,\"tenantId\":1}","return":"{\"errorMsg\":\"com.dtstack.taier.pluginapi.exception.PluginDefineException: null failed\\ncom.dtstack.taier.pluginapi.exception.PluginDefineException: null failed\\n\\tat com.dtstack.taier.flink.FlinkClient.beforeSubmitFunc(FlinkClient.java:225)\\n\\tat com.dtstack.taier.flink.FlinkClient.grammarCheck(FlinkClient.java:1090)\\n\\tat com.dtstack.taier.common.client.ClientProxy.lambda$null$12(ClientProxy.java:305)\\n\\tat com.dtstack.taier.pluginapi.callback.ClassLoaderCallBackMethod.callbackAndReset(ClassLoaderCallBackMethod.java:31)\\n\\tat com.dtstack.taier.common.client.ClientProxy.lambda$grammarCheck$13(ClientProxy.java:305)\\n\\tat java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)\\n\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n\\tat java.lang.Thread.run(Thread.java:748)\\nCaused by: java.lang.RuntimeException: File does not exist: /usr/taier/tmp/null_98/jar/1_flink.common-1.0-SNAPSHOT.jar\\n\\tat com.dtstack.taier.base.filesystem.FilesystemManager.getLocalJarFile(FilesystemManager.java:163)\\n\\tat com.dtstack.taier.base.filesystem.FilesystemManager.downloadFile(FilesystemManager.java:121)\\n\\tat com.dtstack.taier.base.filesystem.FilesystemManager.downloadFile(FilesystemManager.java:82)\\n\\tat com.dtstack.taier.flink.util.FlinkUtil.downloadJar(FlinkUtil.java:199)\\n\\tat com.dtstack.taier.flink.FlinkClient.beforeSubmitFunc(FlinkClient.java:221)\\n\\t... 8 more\\n\",\"result\":false}"}

**Comment by vainhope** [comment]
看下这段逻辑呢
![image](https://user-images.githubusercontent.com/18212930/235571026-1b429572-586a-4251-820c-e7a1343f14ee.png)

**Comment by 617450941** [comment]
这个远程文件是存再hdfs的还是sftp上的?

**Comment by 617450941** [comment]
看了下是内部的jobId为null导致的

**Comment by 617450941** [comment]
![image](https://user-images.githubusercontent.com/7607957/236433965-cb720b2b-6d59-44c3-9972-9b94c48c4442.png)

**Comment by 617450941** [comment]
还有现在也不会自动创建目录

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/236453614-8b3379c5-49cb-47a2-b4a6-8b458e719fff.png)
这段逻辑会去创建不存在的目录
jobId为空的话 应该是一个固定的null 目录 也不会导致下载不到
而且新建一个任务的时候 jobId就会生成了

**Comment by 617450941** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
