### ISSUE TITLE
调度依赖不能修改

### ISSUE THREAD

**Issue by cs3163077** [DTStack/Taier#1079]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar feature requirement.

### Description

调度依赖不能修改，每次重新打开都是初始值

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mortalYoung** [comment]
可以给一下版本吗

**Comment by cs3163077** [comment]
> 可以给一下版本吗可以给一下版本吗可以给一下版本吗



> 可以给一下版本吗

master版本

**Comment by mortalYoung** [comment]
在 master 分支无法复现，可以给一下复现操作吗

**Comment by cs3163077** [comment]
> 在 master 分支无法复现，可以给一下复现操作吗

![image](https://github.com/DTStack/Taier/assets/13974148/8a3b9259-42f0-49d9-87aa-ee7e6e57c308)
![image](https://github.com/DTStack/Taier/assets/13974148/ff1bef33-5dd8-4b8a-9727-425986bd5f48)
重新打开任务
![image](https://github.com/DTStack/Taier/assets/13974148/2d088322-dc4d-4141-98ab-7b3807954370)
