### ISSUE TITLE
能否告知一下团队工作邮箱？想要报告一个可能漏洞，但需要团队邮箱确认。

### ISSUE THREAD

**Issue by santubb** [DTStack/Taier#1082]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

能否告知一下团队工作邮箱？想要报告一个可能漏洞，但需要团队邮箱确认。后续可以上传issue。

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by weaksloth** [comment]
不方便直接提issue吗？

**Comment by santubb** [comment]
> 

已经报告给团队其他人员啦~
