### ISSUE TITLE
[Bug] [taier-data-develop] Generate sql for flink standalone task fail，"不支持的表类型"

### ISSUE THREAD

**Issue by weaksloth** [DTStack/Taier#1086]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

语法校验错误：不支持的表类型
SQL转换错误：不支持的表类型

### What you expected to happen

在字典表里获取`1.12-standalone`的versionValue为`112_standalone`，在`SqlGenerateFactory`中条件判断flink standalone任务时会有逻辑错误：
```java
        switch (tableType) {
            case SIDE:
                if (StringUtils.isNotBlank(versionValue) && FlinkVersion.FLINK_112.getVersion().equals(versionValue)) {
                    return TableFactory.getSideTable(dataSource.getDataTypeCode(), dataJson, paramJson, FlinkVersion.FLINK_112).getCreateSql();
                }
            case SINK:
                if (StringUtils.isNotBlank(versionValue) && FlinkVersion.FLINK_112.getVersion().equals(versionValue)) {
                    return TableFactory.getSinkTable(dataSource.getDataTypeCode(), dataJson, paramJson, FlinkVersion.FLINK_112).getCreateSql();
                }
            case SOURCE:
                if (StringUtils.isNotBlank(versionValue) && FlinkVersion.FLINK_112.getVersion().equals(versionValue)) {
                    return TableFactory.getSourceTable(dataSource.getDataTypeCode(), dataJson, paramJson, FlinkVersion.FLINK_112).getCreateSql();
                }
            default:
                throw new DtCenterDefException(String.format("不支持的表类型:%s", tableType.getTableType()));
        }
```

### How to reproduce

任务类型：flink sql
引擎版本：flink-1.12-standalone

当设置好源和目标后，进行"语法检查"操作或者"转换为SQL"操作时，提示"不支持的表类型"

### Anything else

如果要修改的话，是调整字典里的值还是在判断条件中使用`versionValue.contains(FlinkVersion.FLINK_112.getVersion())`替代equals更好呢

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
数据库的枚举值应该是112
![image](https://github.com/DTStack/Taier/assets/18212930/732ce2c9-85f4-4738-a6c8-0303cd26d41b)

这个地方sql修复过

**Comment by weaksloth** [comment]
@vainhope 大佬我是执行的`init.sql`，我看了一下`init.sql`里这个值还不是112，第1676行
