### ISSUE TITLE
[Question][Module Name] Ask for question CompoundEnumeration  not found

### ISSUE THREAD

**Issue by zhencang** [DTStack/Taier#1091]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

DtClassLoader.java:[190,20] 找不到符号
[ERROR]   符号:   类 CompoundEnumeration
[ERROR]   位置: 类 com.dtstack.taier.pluginapi.loader.DtClassLoader

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhencang** [comment]
use old jdk?

**Comment by vainhope** [comment]
用1.8试试
