### ISSUE TITLE
周期任务实例被设置为冻结状态，下边的子任务还是运行执行了

### ISSUE THREAD

**Issue by xjs1983boy** [DTStack/Taier#1095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

将提交的周期任务状态修改为冻结，但是第二天任务下边的子任务还是执行成功了。

### What you expected to happen

将提交的周期任务状态修改为冻结，但是第二天任务下边的子任务还是执行成功了。

### How to reproduce

将提交的周期任务状态修改为冻结，但是第二天任务下边的子任务还是执行成功了。

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
![image](https://github.com/DTStack/Taier/assets/18212930/920bbedd-3987-4b9b-9485-234613f5315e)
运行的任务调度属性是自依赖么
