### ISSUE TITLE
增量同步endLocation信息没能同步到Prometheus

### ISSUE THREAD

**Issue by cs3163077** [DTStack/Taier#1104]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar feature requirement.

### Description

相同环境下standalone,per_job,session，增量同步endLocation信息没能同步到Prometheus，而用脚本chunjun-standalone.sh -job ss.json可以写入。
![image](https://github.com/DTStack/Taier/assets/13974148/120d1666-2129-46ef-8724-ccbb99bd6901)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
确认下 per_job模式 的任务 运行的时候 pushgateway的host和port是否正确呢

**Comment by cs3163077** [comment]
配置应该没问题，有其他指标
![image](https://github.com/DTStack/Taier/assets/13974148/b06390c9-283f-4ea7-885a-a2696350c9cf)

集群配置
![image](https://github.com/DTStack/Taier/assets/13974148/cce5d599-ef22-41d2-8180-3748c97f76d3)

per_job配置
![image](https://github.com/DTStack/Taier/assets/13974148/71a0c014-df4a-414a-9625-994416136b7a)

测试脚本
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "password": "*****",
            "increColumn": "id",
            "startLocation": "0",
            "column": [
              {
                "name": "id",
                "type": "bigint"
              },
              {
                "name": "name",
                "type": "nvarchar"
              },
              {
                "name": "birthday",
                "type": "nvarchar"
              },
              {
                "name": "ts",
                "type": "datetime"
              }
            ],
            "customSql": "SELECT *  FROM ***",
            "connection": [
              {
                "schema": "dbo",
                "jdbcUrl": [
                  "jdbc:jtds:sqlserver://192.168.***.***:****/**"
                ],
                "table": [
                  ""
                ]
              }
            ],
            "where": "1=1",
            "username": "sa"
          },
          "name": "sqlserverreader"
        },
        "writer": {
          "name": "streamwriter",
          "parameter": {
            "print": false
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": 1,
        "readerChannel": 1,
        "writerChannel": 1,
        "bytes": -1048576
      },
      "restore": {
        "restoreColumnName": "id",
        "isStream": false
      }
    }
  }
}
