### ISSUE TITLE
[npm打包异常][taier-ui] npm打包异常

### ISSUE THREAD

**Issue by feelshana** [DTStack/Taier#1122]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

master分支下taier-ui打包异常
$ umi build
[INFO] Bundle with webpack 5...
[INFO] i Compiling Webpack
[INFO] (node:8696) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
[INFO] (Use `node --trace-deprecation ...` to show where the warning was created)
[INFO] (node:8696) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
[INFO] Browserslist: caniuse-lite is outdated. Please run:
[INFO] npx browserslist@latest --update-db
[INFO] 
[INFO] Why you should do it regularly:
[INFO] https://github.com/browserslist/browserslist#browsers-data-updating
[INFO] √ Webpack: Compiled with some errors in 1.33m
[INFO]  ERROR  Failed to compile with 1 errors15:47:16
[INFO] 
[INFO]  error  in ./node_modules/antlr4-c3/lib/index.mjs
[INFO] 
[INFO] Module parse failed: Unexpected token (1697:9)
[INFO] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[INFO] |   static COMPLETE_CHAR_SET = i13.of(N.MIN_CHAR_VALUE, N.MAX_CHAR_VALUE);
[INFO] |   static EMPTY_SET = new i13();
[INFO] >   static {
[INFO] |     i13.COMPLETE_CHAR_SET.readonly = true, i13.EMPTY_SET.readonly = true;
[INFO] |   }
[INFO] 
[INFO] ERROR in ./node_modules/antlr4-c3/lib/index.mjs 1697:9
[INFO] Module parse failed: Unexpected token (1697:9)
[INFO] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[INFO] |   static COMPLETE_CHAR_SET = i13.of(N.MIN_CHAR_VALUE, N.MAX_CHAR_VALUE);
[INFO] |   static EMPTY_SET = new i13();
[INFO] >   static {
[INFO] |     i13.COMPLETE_CHAR_SET.readonly = true, i13.EMPTY_SET.readonly = true;
[INFO] |   }
[INFO]  @ ./node_modules/dt-sql-parser/dist/parser/common/basicParser.js 3:0-47 221:25-43
[INFO]  @ ./node_modules/dt-sql-parser/dist/parser/spark.js 3:0-47 5:38-49
[INFO]  @ ./node_modules/monaco-sql-languages/out/esm/sparksql/sparkSQLWorker.js 1:0-55 7:26-34
[INFO]  @ ./node_modules/monaco-sql-languages/out/esm/sparksql/sparksql.worker.js 2:0

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by feelshana** [comment]
master分支下taier-ui打包异常 请问是什么原因呢

**Comment by mortalYoung** [comment]
贴一下报错信息呗

**Comment by feelshana** [comment]
报错信息如下：
ERROR  Failed to compile with 1 errors16:02:18
[INFO] 
[INFO]  error  in ./node_modules/antlr4-c3/lib/index.mjs
[INFO] 
[INFO] Module parse failed: Unexpected token (1697:9)
[INFO] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[INFO] |   static COMPLETE_CHAR_SET = i13.of(N.MIN_CHAR_VALUE, N.MAX_CHAR_VALUE);
[INFO] |   static EMPTY_SET = new i13();
[INFO] >   static {
[INFO] |     i13.COMPLETE_CHAR_SET.readonly = true, i13.EMPTY_SET.readonly = true;
[INFO] |   }
[INFO] 
[INFO] ERROR in ./node_modules/antlr4-c3/lib/index.mjs 1697:9
[INFO] ERROR in ./node_modules/antlr4-c3/lib/index.mjs 1697:9null
[INFO] Module parse failed: Unexpected token (1697:9)
[INFO] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[INFO] |   static COMPLETE_CHAR_SET = i13.of(N.MIN_CHAR_VALUE, N.MAX_CHAR_VALUE);
[INFO] |   static EMPTY_SET = new i13();
[INFO] >   static {
[INFO] |     i13.COMPLETE_CHAR_SET.readonly = true, i13.EMPTY_SET.readonly = true;
[INFO] |     i13.COMPLETE_CHAR_SET.readonly = true, i13.EMPTY_SET.readonly = true;build failed
[INFO] |   }

**Comment by feelshana** [comment]
ERROR in ./node_modules/antlr4-c3/lib/index.mjs 1697:9
Module parse failed: Unexpected token (1697:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   static COMPLETE_CHAR_SET = i13.of(N.MIN_CHAR_VALUE, N.MAX_CHAR_VALUE);
|   static EMPTY_SET = new i13();
>   static {
|     i13.COMPLETE_CHAR_SET.readonly = true, i13.EMPTY_SET.readonly = true;
|   }
 @ ./node_modules/dt-sql-parser/dist/parser/common/basicParser.js 3:0-47 221:25-43
 @ ./node_modules/dt-sql-parser/dist/parser/spark.js 3:0-47 5:38-49
 @ ./node_modules/monaco-sql-languages/out/esm/sparksql/sparkSQLWorker.js 1:0-55 7:26-34
 @ ./node_modules/monaco-sql-languages/out/esm/sparksql/sparksql.worker.js 2:0-50 5:35-49

**Comment by feelshana** [comment]
ERROR in ./node_modules/antlr4-c3/lib/index.mjs 1697:9
Module parse failed: Unexpected token (1697:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   static COMPLETE_CHAR_SET = i13.of(N.MIN_CHAR_VALUE, N.MAX_CHAR_VALUE);
|   static EMPTY_SET = new i13();
>   static {
|     i13.COMPLETE_CHAR_SET.readonly = true, i13.EMPTY_SET.readonly = true;
|   }
 @ ./node_modules/dt-sql-parser/dist/parser/common/basicParser.js 3:0-47 221:25-43
 @ ./node_modules/dt-sql-parser/dist/parser/generic.js 3:0-47 4:40-51
 @ ./node_modules/monaco-sql-languages/out/esm/sql/sqlWorker.js 1:0-54 7:26-31
 @ ./node_modules/monaco-sql-languages/out/esm/sql/sql.worker.js 2:0-40 5:19-28

webpack compiled with 1 error
null
 info  如果你需要进交流群，请访问 https://fb.umijs.org
build failed
Error: build failed
    at D:\workspace\Taier-final\taier-ui\node_modules\@umijs\bundler-webpack\lib\index.js:177:29
    at D:\workspace\Taier-final\taier-ui\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114591:14
    at processQueueWorker (D:\workspace\Taier-final\taier-ui\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114529:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
 info  如果你需要进交流群，请访问 https://fb.umijs.org
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
