### ISSUE TITLE
[Question][任务系统参数]工作流任务中的系统参数分别在手动运行和调度定期运行时出现不同结果的问题

### ISSUE THREAD

**Issue by ddwolf715** [DTStack/Taier#1131]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

任务参数的使用，遇到了问题，周期性运行都有问题，见周期实例的截图，我创建的是每10分钟运行一次，每一次都是报出同样的错误信息。

周期实例
<img width="400" height="200" alt="image" src="https://github.com/DTStack/Taier/assets/17849555/c9cddd4a-13b6-4512-ae5d-bc7e64e08d13">

用计划时间 ${bdp.system.cyctime} 为例说明，我在SQL语句中使用了这个系统变量，但分别在手工运行和调度运行时有差异：
1. 给参数  ${bdp.system.cyctime}  加了单引号括起来，见下方SQL-1
手工运行时，在数据库里结果正确，显示正确定的时间，见下方结果-1
但如果调度运行，在数据库里的结果就是字符串  ${bdp.system.cyctime} ,见下方结果-2

SQL-1
insert into dmp_dataquality_test_data_y
select
reflect("java.util.UUID","randomUUID") id, -- 检查结果数据的主键
from_unixtime(unix_timestamp()+28800,'yyyy-MM-dd HH:mm:ss') start_flag,
'${bdp.system.cyctime}' dataquality_exec_cyc_time, -- 计划开始时间
'${bdp.system.runtime}' dataquality_exec_start_time, -- 实际开始时间
'end' end_flag
from dmp_dataquality_test_child;

结果-1
<img width="400" height="200" alt="image" src="https://github.com/DTStack/Taier/assets/17849555/ebf0e1f4-7e30-4829-bc55-c0d0b320cb33">

结果-2
<img width="400" height="200" alt="image" src="https://github.com/DTStack/Taier/assets/17849555/45969377-cf35-4553-ba61-9a90eb644062">

2.不给参数   ${bdp.system.cyctime}  加单引号，见下方SQL-2
手工运行时也是正确的，结果-3
但如果调度运行，就报错了，错误日志见下方错误-1

SQL-2
insert into dmp_dataquality_test_data
select
reflect("java.util.UUID","randomUUID") id, -- 检查结果数据的主键
'start' start_flag,
${bdp.system.cyctime} dataquality_exec_cyc_time, -- 计划开始时间
${bdp.system.runtime} dataquality_exec_start_time, -- 实际开始时间
'end' end_flag
from dmp_dataquality_test_child;

结果-3
<img width="400" height="200" alt="image" src="https://github.com/DTStack/Taier/assets/17849555/2b171197-03bb-4134-8cc2-3947f63c861a">

错误-1
<img width="400" height="200" alt="image" src="https://github.com/DTStack/Taier/assets/17849555/383bd574-3cbe-4565-809f-acecec6224de">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ddwolf715** [comment]
自己顶一下帖子

**Comment by vainhope** [comment]
![image](https://github.com/DTStack/Taier/assets/18212930/b742c90a-32a1-4081-8dbb-762f51e4f089)

![image](https://github.com/DTStack/Taier/assets/18212930/d03f31ce-f409-496a-b918-7e850dc64ed4)

验证是正常执行的

1. 确认任务提交的时候 是否将参数替换规则带上
   在taier的数据库查询
   select info -> '$.taskParamsToReplace'
   from schedule_task_shade_info
   where task_id =
      (select task_id from schedule_task_shade where name = 'testParamcyc');
2. 任务执行的时候在控制台上查看任务真实SQL 是否语法正确

**Comment by vainhope** [comment]
正常的使用是加'${bdp.system.cyctime}'
控制台上查看任务真实SQL 是否已经替换过了呢

**Comment by vainhope** [comment]
控制台是在这里查看 确认替换后的语法是否正确
![image](https://github.com/DTStack/Taier/assets/18212930/e911ef9b-85a6-42ac-9a26-797688c8b06a)

**Comment by Dev-Lon** [comment]
> 控制台是在这里查看 确认替换后的语法是否正确 ![image](https://user-images.githubusercontent.com/18212930/283308318-e911ef9b-85a6-42ac-9a26-797688c8b06a.png)

同样的写法，为什么我这边就没替换过来，如下图
![图片](https://github.com/DTStack/Taier/assets/92787915/ddb2731c-bf44-4bf2-b32a-0fd5d3f3bbb7)

**Comment by ddwolf715** [comment]
更新到最新版本号，发现没有此问题了。之前用的1.4版本

**Comment by ddwolf715** [comment]
更新到最新版本后，发现没有此问题了，正在做进一步的细致测试。
之前用的1.4版本，发生此贴的问题。
