### ISSUE TITLE
[Bug] [taier-ui] Failed to compile with error : can't resolve 'dt-sql-parser/dist/parser/generic'

### ISSUE THREAD

**Issue by LangWuyue** [DTStack/Taier#1144]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

![img_v3_025p_2621d2b7-b642-45e3-998f-df63c29a1e5g](https://github.com/DTStack/Taier/assets/25575108/2ca246f0-2871-40d9-b4b4-1e31f7beed70)

### What you expected to happen

yarn run build success

### How to reproduce

step1:
git clone https://github.com/DTStack/Taier
step2:
cd taier && git checkout v1.4.0
step3:
cd taier-ui && npm install
step4:
yarn run build

### Version

v1.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jin-sir** [comment]
Please use pnpm install or yarn install

**Comment by jin-sir** [comment]
Please use yarn/pnpm run build
