### ISSUE TITLE
taier-1.4.0执行sparkSQL报错

### ISSUE THREAD

**Issue by chencanleng** [DTStack/Taier#1149]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

下载taier-1.4.0源码本地编译后，配置sparkthrift数据源正常，但是执行sparkSQL任务时报错
![image](https://github.com/DTStack/Taier/assets/142563234/f57e3ab8-046f-47c5-9e73-5e2619e5530d)

[日志.txt](https://github.com/DTStack/Taier/files/13669668/default.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
https://github.com/DTStack/Taier/issues/1100 
代码已合并1.4 需要重新拉下代码编译一下插件
