### ISSUE TITLE
[Bug] [develop] can't start in local or by docker 

### ISSUE THREAD

**Issue by anpei-lu** [DTStack/Taier#1153]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

你好，非常喜欢这个开源项目，想引入使用，目前我在存在两个问题：
1、本地编译完成了，但是执行到application.run(args)的时候，一直卡住，日志打印8090端口出来了，zookeeper也链接上了。
2、换种方式，使用docker启动的话，错误日志显示zookeeper一直连接不上，我在idea上面用java代码连接是可以的
以上问题不知道怎么解决，求助求助

### What you expected to happen

插件中有几个maven无法下载，我注释起来了。会不会跟这个有关？
<img width="1440" alt="image" src="https://github.com/DTStack/Taier/assets/61785149/7b9460e5-45a6-4275-8bec-862ad980dc2b">

### How to reproduce

Mac m1 系统

### Anything else

联系电话：18566086516（微信同号）
邮箱：anpei.lu@icloud.com

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
和插件的依赖没有关系的
正常启动后 访问不了页面还是如何
建议贴一份taier.log

**Comment by anpei-lu** [comment]
你好，我的电脑是Mac m1，可能存在不兼容，我更换了方式，以下是我在CentOS Linux release 7.9.2009 (Core)使用docker 25.0.3安装的步骤：

**Comment by vainhope** [comment]
日志看起来没有报错 页面访问是有什么问题呢

**Comment by anpei-lu** [comment]
已解决，非常感谢！
