### ISSUE TITLE
[Bug] [UI] 前端页面崩溃 

### ISSUE THREAD

**Issue by chyueyi** [DTStack/Taier#1161]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

![image](https://github.com/DTStack/Taier/assets/35141460/853114dc-db55-4baf-9539-818a4969d5dd)
![image](https://github.com/DTStack/Taier/assets/35141460/0f86c681-5412-44cc-bae8-12a4f82bb752)
打开Mysql任务，会导致浏览器内存极速上升，从而页面崩溃，感觉是mysql.worker.js的问题。

### What you expected to happen

页面能正常使用不报错

### How to reproduce

打开Mysql任务，会导致浏览器内存极速上升，从而页面崩溃，感觉是mysql.worker.js的问题。

### Version

v1.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by niutaofan** [comment]
遇到同样问题，在进行任务编辑[hive sql]的任务编辑页，出现浏览器当前页的CPU跑满，内存逐渐上升
![微信图片_20240414172118](https://github.com/DTStack/Taier/assets/24287423/6b8a22a6-3193-4718-b001-2a93a56f9d5b)

**Comment by niutaofan** [comment]
还有人维护么

**Comment by jin-sir** [comment]
@niutaofan 我该如何复现呢，能提供一下例子吗？

**Comment by niutaofan** [comment]
进入ETL的编辑页，当触发：onDidChangeModelContent，出现函数死循环。导致CPU上升
![image](https://github.com/DTStack/Taier/assets/24287423/34a59fd0-5f87-47a8-8e24-6a9e7e66c995)

![image](https://github.com/DTStack/Taier/assets/24287423/2f61c700-8483-49d1-a710-80b36e403d36)

**Comment by niutaofan** [comment]
> 进入ETL的编辑页，当触发：onDidChangeModelContent，出现函数死循环。导致CPU上升 ![image](https://private-user-images.githubusercontent.com/24287423/324228570-34a59fd0-5f87-47a8-8e24-6a9e7e66c995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODI2NTksIm5iZiI6MTcxMzY4MjM1OSwicGF0aCI6Ii8yNDI4NzQyMy8zMjQyMjg1NzAtMzRhNTlmZDAtNWY4Ny00N2E4LThlMjQtNmE5ZTdlNjZjOTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA2NTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NjRkNjQ1M2RmNzU4ZmVjOWVlNmFkNTY0MTc4MGJhMWVmYjRkZWI5ZjQxYTQ1MzlmZjcxMGQxYzRlYTA4ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eNd-t8Cl4DJJOqjt3yDxSvtrEHaBo_52VhgsV1xDcDM)
> 
> ![image](https://private-user-images.githubusercontent.com/24287423/324228675-2f61c700-8483-49d1-a710-80b36e403d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODI2NTksIm5iZiI6MTcxMzY4MjM1OSwicGF0aCI6Ii8yNDI4NzQyMy8zMjQyMjg2NzUtMmY2MWM3MDAtODQ4My00OWQxLWE3MTAtODBiMzZlNDAzZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA2NTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYWJhY2Y2MWI4OTRjNWMyZDZiMTUzZGQyMjNkYjljOWU1ODkyMjUxZDE0YmM1YTc5NzI5OTE3NGEzZGE1MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7AcXIKtK0b6364T89hGjXUzUKur0y_QzeCqgC4TsTXw)

同样，在修改调度依赖、环境参数时候，都会导致CPU跑满
![image](https://github.com/DTStack/Taier/assets/24287423/663ba47f-534c-40b8-acda-af4fcc0785db)

**Comment by jin-sir** [comment]
> 进入ETL的编辑页，当触发：onDidChangeModelContent，出现函数死循环。导致CPU上升 ![image](https://private-user-images.githubusercontent.com/24287423/324228570-34a59fd0-5f87-47a8-8e24-6a9e7e66c995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTUxMTEsIm5iZiI6MTcxMzY5NDgxMSwicGF0aCI6Ii8yNDI4NzQyMy8zMjQyMjg1NzAtMzRhNTlmZDAtNWY4Ny00N2E4LThlMjQtNmE5ZTdlNjZjOTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDEwMjAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NmJmZDkxZWRiN2JjZjdmMTNmMDEyZGM4ZGFiYTFmYjI2NzhhZTVlZmZmYzM2YTczYTFiYTBkMWIzZmI2MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cgeUY_NX8CG7ayxRDdtdx1O2Eihu3I9rNc8CSYPPDNU)
> 
> ![image](https://private-user-images.githubusercontent.com/24287423/324228675-2f61c700-8483-49d1-a710-80b36e403d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTUxMTEsIm5iZiI6MTcxMzY5NDgxMSwicGF0aCI6Ii8yNDI4NzQyMy8zMjQyMjg2NzUtMmY2MWM3MDAtODQ4My00OWQxLWE3MTAtODBiMzZlNDAzZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDEwMjAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMTIxM2M2Y2NlZDExZWI2YjQzNWNjNTVmODAyZTVjNWZiZTEzMGUzNWQ5ZmU2MzcyZjY5Y2IxMzkzMGM4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OGNjW1I77CZRc0donZRo42HOJxPF0VpoEbrb4lXzf1Y)

我复现不出你这个问题。并且你说的在输入内容时会触发`onDidChangeModalContent`，导致 CPU 爆满。由于这块的编辑器是[molecule](https://github.com/DTStack/molecule)，并不是图片中的这个 Editor 组件，不会触发`onDidChangeModalContent`
![2024-04-21 18 40 23](https://github.com/DTStack/Taier/assets/56628290/172c34f2-e0a5-4f70-bfde-6464fc90b67e)

**Comment by niutaofan** [comment]
好的，谢谢！
我怕这边是win10环境，编译的是master分支。  可能是我本地问题吧

**Comment by zvrr** [comment]
> > 进入ETL的编辑页，当触发：onDidChangeModelContent，出现函数死循环。导致CPU上升 ![image](https://private-user-images.githubusercontent.com/24287423/324228570-34a59fd0-5f87-47a8-8e24-6a9e7e66c995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTUxMTEsIm5iZiI6MTcxMzY5NDgxMSwicGF0aCI6Ii8yNDI4NzQyMy8zMjQyMjg1NzAtMzRhNTlmZDAtNWY4Ny00N2E4LThlMjQtNmE5ZTdlNjZjOTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDEwMjAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NmJmZDkxZWRiN2JjZjdmMTNmMDEyZGM4ZGFiYTFmYjI2NzhhZTVlZmZmYzM2YTczYTFiYTBkMWIzZmI2MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cgeUY_NX8CG7ayxRDdtdx1O2Eihu3I9rNc8CSYPPDNU)
> > ![image](https://private-user-images.githubusercontent.com/24287423/324228675-2f61c700-8483-49d1-a710-80b36e403d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTUxMTEsIm5iZiI6MTcxMzY5NDgxMSwicGF0aCI6Ii8yNDI4NzQyMy8zMjQyMjg2NzUtMmY2MWM3MDAtODQ4My00OWQxLWE3MTAtODBiMzZlNDAzZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDEwMjAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMTIxM2M2Y2NlZDExZWI2YjQzNWNjNTVmODAyZTVjNWZiZTEzMGUzNWQ5ZmU2MzcyZjY5Y2IxMzkzMGM4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OGNjW1I77CZRc0donZRo42HOJxPF0VpoEbrb4lXzf1Y)
> 
> 我复现不出你这个问题。并且你说的在输入内容时会触发`onDidChangeModalContent`，导致 CPU 爆满。由于这块的编辑器是[molecule](https://github.com/DTStack/molecule)，并不是图片中的这个 Editor 组件，不会触发`onDidChangeModalContent` ![2024-04-21 18 40 23](https://private-user-images.githubusercontent.com/56628290/324241510-172c34f2-e0a5-4f70-bfde-6464fc90b67e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTIxNjQsIm5iZiI6MTcxNDM5MTg2NCwicGF0aCI6Ii81NjYyODI5MC8zMjQyNDE1MTAtMTcyYzM0ZjItZTBhNS00ZjcwLWJmZGUtNjQ2NGZjOTBiNjdlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExNTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZGVhMTFiNGY1MzJkMWZkNzE0MGUwOWRiNzYyMThmNjQ5OWI0NWZjMWQ3MmM2MDk1YzJkOTFhMDMyMTlmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eLuzBy_DHyp0Htf8tTtBIivFvT7zbC8FPiA3q_rereI) [ ![2024-04-21 18 40 23](https://private-user-images.githubusercontent.com/56628290/324241510-172c34f2-e0a5-4f70-bfde-6464fc90b67e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTIxNjQsIm5iZiI6MTcxNDM5MTg2NCwicGF0aCI6Ii81NjYyODI5MC8zMjQyNDE1MTAtMTcyYzM0ZjItZTBhNS00ZjcwLWJmZGUtNjQ2NGZjOTBiNjdlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExNTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZGVhMTFiNGY1MzJkMWZkNzE0MGUwOWRiNzYyMThmNjQ5OWI0NWZjMWQ3MmM2MDk1YzJkOTFhMDMyMTlmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eLuzBy_DHyp0Htf8tTtBIivFvT7zbC8FPiA3q_rereI) ](https://private-user-images.githubusercontent.com/56628290/324241510-172c34f2-e0a5-4f70-bfde-6464fc90b67e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTIxNjQsIm5iZiI6MTcxNDM5MTg2NCwicGF0aCI6Ii81NjYyODI5MC8zMjQyNDE1MTAtMTcyYzM0ZjItZTBhNS00ZjcwLWJmZGUtNjQ2NGZjOTBiNjdlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExNTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZGVhMTFiNGY1MzJkMWZkNzE0MGUwOWRiNzYyMThmNjQ5OWI0NWZjMWQ3MmM2MDk1YzJkOTFhMDMyMTlmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eLuzBy_DHyp0Htf8tTtBIivFvT7zbC8FPiA3q_rereI) [ ](https://private-user-images.githubusercontent.com/56628290/324241510-172c34f2-e0a5-4f70-bfde-6464fc90b67e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTIxNjQsIm5iZiI6MTcxNDM5MTg2NCwicGF0aCI6Ii81NjYyODI5MC8zMjQyNDE1MTAtMTcyYzM0ZjItZTBhNS00ZjcwLWJmZGUtNjQ2NGZjOTBiNjdlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExNTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZGVhMTFiNGY1MzJkMWZkNzE0MGUwOWRiNzYyMThmNjQ5OWI0NWZjMWQ3MmM2MDk1YzJkOTFhMDMyMTlmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eLuzBy_DHyp0Htf8tTtBIivFvT7zbC8FPiA3q_rereI)

你这是什么版本？编译了master和1.4分支，也是页面挂死

**Comment by jin-sir** [comment]
@zvrr 1.4分支的，能提供下操作过程吗，怎么操作可以导致页面崩溃？

**Comment by zvrr** [comment]
> @zvrr 1.4分支的，能提供下操作过程吗，怎么操作可以导致页面崩溃？

@jin-sir dockerhub上的镜像不会有这个问题。本地编译了的master、1.4.0-RELEASE tag v1.4.0 都是这个问题。麻烦你编译下这几个分支看看，应该就可以复现了。
![taier](https://github.com/DTStack/Taier/assets/194304/1e1fe423-bb7e-47bf-93bc-3f9aa264cbb6)

**Comment by yunchat** [comment]
我这也遇到了!

**Comment by greenery2** [comment]
我也是，编译master分支，只要在编辑器按下，任务编辑或设置的setting.json编辑都是卡死浏览器。
![image](https://github.com/DTStack/Taier/assets/51855633/e48ec2f3-8760-4c7f-ada5-aff6ed1761a0)

**Comment by jin-sir** [comment]
@zvrr 很尴尬，我用mac和window10编译了这几个分支，还是复现不出来

**Comment by hww02** [comment]
在master和1.4分支上也遇到了同样的问题，项目启动后，点击任务开发中的任务，数遍点击编辑框或者按enter减 导致cpu内存快速升高，直至浏览器崩溃，有友友解决的吗？

Uploading 771f3882cd7218e325f43144aa3e0e46.mp4…

**Comment by jin-sir** [comment]
在使用npm 或 yarn 安装依赖时，pnpm-lock文件失效，将依赖包`@dtinsight/molecule`升级到了1.3.5，在 molecule@1.3.5 中，存在无限循环问题，导致页面崩溃，现已将版本暂时锁定在 1.3.4。请重新拉取最新代码，重新安装依赖
