### ISSUE TITLE
sftp组件可以使用ftp方式连接吗

### ISSUE THREAD

**Issue by whiteS18** [DTStack/Taier#1166]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

有一个阿里云云虚拟主机，使用filezilla使用ftp端口号21进行连接可以正常连接并上传，但是在webui页面上添加sftp组建后连接失败
![图片](https://github.com/DTStack/Taier/assets/31566522/e97d0407-6aa3-4509-9abb-82cc5173543e)
![图片](https://github.com/DTStack/Taier/assets/31566522/f713f83f-5742-4b2e-90b6-975f4c3a852b)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Jixiangup** [comment]
有防火墙嘛

**Comment by whiteS18** [comment]
> 有防火墙嘛
应该没有，如果filezilla可以访问的话webui也应该可以访问吧？

**Comment by Jixiangup** [comment]
> > 有防火墙嘛
> > 应该没有，如果filezilla可以访问的话webui也应该可以访问吧？

理论上是的 但是会有可能存在虚拟机拒绝的可能 有时间我看看

**Comment by Jixiangup** [comment]
ftp和ssh是两种不同的协议 taier是使用ssh去和服务器通信的 故而无法连接成功
