### ISSUE TITLE
如何关闭高可用配置？

### ISSUE THREAD

**Issue by whiteS18** [DTStack/Taier#1167]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

我现在只想单独添加一个数据源，但是我在点击测试连通性的时候，它提示我说开启kerberos认证后，需配置SFTP服务了，这个玩意怎么关掉呢？

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Jixiangup** [comment]
现在没有直接关闭的功能 只能先配置一下SFTP组件

**Comment by Jixiangup** [comment]
如果有问题再重新打开这个issue
