### ISSUE TITLE
dt-insight-hive-shade 包从哪里下载

### ISSUE THREAD

**Issue by jiemotongxue** [DTStack/Taier#216]
![image](https://user-images.githubusercontent.com/16730029/155097301-0794c730-f397-4c7d-975b-f43caed2e142.png)

**Comment by dtdazhi** [comment]
临时解决方案： 通过【袋鼠云开源框架技术交流群】钉钉群号：30537511  下载taier.tar
[image](https://user-images.githubusercontent.com/16730029/155097471-de93b54e-31fe-41bb-a864-0f44f7ee3591.png)

解压后有3个jar包  
参考文档 安装到本地mavne库中即可。

最终解决方案：上传到maven中央仓库直接依赖下载，目前已经在走申请流程。

**Comment by dtdazhi** [comment]
临时解决方案： 通过【袋鼠云开源框架技术交流群】钉钉群号：30537511  下载taier.tar
![image](https://user-images.githubusercontent.com/16730029/155097471-de93b54e-31fe-41bb-a864-0f44f7ee3591.png)

解压后有3个jar包  
参考文档 安装到本地mavne库中即可。
最终解决方案：上传到maven中央仓库直接依赖下载，目前已经在走申请流程。

**Comment by dtdazhi** [comment]
请确定一下 dt-insight-hive-shade 包是否安装到本地的maven仓库了，您上面的依赖不到的包，在群里能够下载到
<img width="629" alt="image" src="https://user-images.githubusercontent.com/88131825/155249953-c7e4d029-66b1-4a0f-b3ea-14adac8abe58.png">

**Comment by jiemotongxue** [comment]
![image](https://user-images.githubusercontent.com/16730029/155677786-b126eb45-3c87-4a4a-b785-292b1c4c8bb4.png)


dt-insight-hive-shade的包已经上传到maven仓库
