### ISSUE TITLE
执行运行k8s任务在哪看 ??

### ISSUE THREAD

**Issue by BoYiZhang** [DTStack/Taier#218]
我看  调度方式：同时支持Yarn/K8s
这个哪看 ????

**Comment by jiemotongxue** [comment]
关于 On k8s 的技术实现，后面的迭代版本会push到社区上。  
可以关注Github的Issue，未来规划近段时间会发布上来。

**Comment by BoYiZhang** [comment]
好期待啊, on k8s 是 task 跑在 k8s的pod里面嘛...

**Comment by jiemotongxue** [comment]
是的。 flink、spark 自身都有on k8s 的模式
