### ISSUE TITLE
测试sftp、资源调度等连通性时候报错

### ISSUE THREAD

**Issue by zlj921020** [DTStack/Taier#219]
![image](https://user-images.githubusercontent.com/24295496/155133251-b5de729c-3d75-46c2-84c5-7802203d26b6.png)

**Comment by dtdazhi** [comment]
您检查一下pluginLibs目录下的dummy插件有没有jar，堆栈信息没有截全，从前面的信息看出是在加载dummy的jar时出错的

**Comment by zlj921020** [comment]
![image](https://user-images.githubusercontent.com/24295496/155138952-ceec3050-7ad7-4b48-a692-b2eddf4cf030.png)
我使用idea调试的，没有部署

**Comment by vainhope** [comment]
idea调试 需要先执行build/mvn-build-plugins.sh
确保本地目录pluginLibs有对应的插件包

![image](https://user-images.githubusercontent.com/18212930/155249681-8d2cb1bc-b741-4d6b-81a6-205551ac2f34.png)
