### ISSUE TITLE
mvn-build.sh执行后得到的是jar包${git.branch}未替换

### ISSUE THREAD

**Issue by Shlpeng** [DTStack/Taier#224]
问题描述：未经任何改动，mvn-build.sh执行后得到的是taier-data-develop-${git.branch}-with-dependencies.jar

临时解决：
直接处理的方式移除掉pom文件中
![image](https://user-images.githubusercontent.com/15671474/155261181-5ebc18f8-3066-4c54-a811-6a05ddd27c2f.png)

**Comment by jiemotongxue** [comment]
@Shlpeng  邀请您提个PR帮助我们修复这个问题

**Comment by Shlpeng** [comment]
> @Shlpeng 邀请您提个PR帮助我们修复这个问题

可以把 git.branch 替换成 project.version 变量不

**Comment by jiemotongxue** [comment]
remove ${git.branch}, done~
