### ISSUE TITLE
./bin/taier.sh脚本兼容macbook环境上启动的优化建议

### ISSUE THREAD

**Issue by Shlpeng** [DTStack/Taier#225]
问题描述：./bin/taier.sh脚本兼容macbook环境上启动的优化建议

临时解决：
1，注释了checkuser的调用
2，注释了. /etc/init.d/functions
3，启动的时候采用的命令是 ./bin/taier.sh start  （start的右边又空出了个空格）

**Comment by jiemotongxue** [comment]
已优化：https://github.com/DTStack/Taier/pull/240
