### ISSUE TITLE
开发页面中 获取任务开发目录失败，请联系管理员

### ISSUE THREAD

**Issue by Su1024** [DTStack/Taier#228]
![image](https://user-images.githubusercontent.com/23012179/155311891-5697abd7-799e-4093-9f17-a55f29e7f3ba.png)

**Comment by vainhope** [comment]
请确定下是否有执行过绑定集群的操作 

https://dtstack.github.io/Taier/docs/quickstart/start#%E7%BB%91%E5%AE%9A%E9%9B%86%E7%BE%A4

**Comment by Su1024** [comment]
![image](https://user-images.githubusercontent.com/23012179/155447735-72bf4b98-2582-4c8c-aa9a-c2383c669cdc.png)
![image](https://user-images.githubusercontent.com/23012179/155447784-2ab51b79-b3a9-4fc5-af71-5c4dc6ad3429.png)
在执行 绑定集群操作的时候 发现没有队列选择

**Comment by Su1024** [comment]
![image](https://user-images.githubusercontent.com/23012179/155447949-e39b98f1-f557-4d04-9f9c-7d4fa2f89ea4.png)
![image](https://user-images.githubusercontent.com/23012179/155447975-e494270b-22bc-40ce-b663-2eb46c5e1604.png)
在执行绑定集群操作的时候 没有队列可以选择

**Comment by dtdazhi** [comment]
绑定集群的时候测试连通性过了吗？

**Comment by Su1024** [comment]
![image](https://user-images.githubusercontent.com/23012179/155448476-258a06b5-156d-485c-91e7-e8cbf84c1327.png)
![image](https://user-images.githubusercontent.com/23012179/155448487-8188bf49-7e3a-4daa-9de3-e9a3a250a749.png)
![image](https://user-images.githubusercontent.com/23012179/155448497-d029f2f6-ddbc-4fc9-a2be-c696d0ac5898.png)
![image](https://user-images.githubusercontent.com/23012179/155448509-ce39669b-51dc-4871-ba3a-e2dbde53116d.png)
测试过了

**Comment by dtdazhi** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/88131825/155455041-937d0be1-7b43-44a7-a6df-978bc8798125.png">
你先查看一下表console_queue里面的数据有没有队列信息，如果没有点击集群的测试连通性试一下，如果还没有的话，那debug一下代码看看测试连通性通过的时候，为什么没有插入队列信息到表console_queue。代码截图参考下面
<img width="878" alt="image" src="https://user-images.githubusercontent.com/88131825/155455336-692c25af-9ea0-47d3-82e4-9a5acc44a079.png">

**Comment by Su1024** [comment]
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/23012179/155473030-d64c20d1-5cfb-4dbb-ba3a-bbb9029257e0.png">
看到表里是有数据的

**Comment by dtdazhi** [comment]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/88131825/155475638-f6d0d2fa-273e-44ec-b38f-8df7b20258ac.png">

那看一下/taier/cluster/getClusterEngine 这个接口的返回数据，返回的json中clusterId 为1数据里面返回的engines下游没有队列数据了，如果有的话，那可能就是前面没有加载，如果没有的话，需要debug一下getClusterEngine接口，看一下为什么查询不出来数据
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/88131825/155475556-560d2938-2530-450e-a214-34cfd21317a2.png">

**Comment by Su1024** [comment]
![image](https://user-images.githubusercontent.com/23012179/155478926-3368ced0-ce8c-478e-8ce7-3cb5478fba9c.png)
看起来应该是前端没有加载出来的问题了

**Comment by Su1024** [comment]
重启前端解决

**Comment by vainhope** [comment]
如果接口返回信息未乱码 数据库初始化数据也为乱码 需要指定jdbc的编码格式 并新建租户对接集群
![image](https://user-images.githubusercontent.com/18212930/156349442-8e0d0cfb-8b20-4f68-81c7-2a381a15dcb2.png)

![image](https://user-images.githubusercontent.com/18212930/156349369-80182772-f6f7-476d-b725-eee2f34b83f1.png)
