### ISSUE TITLE
启动报错：Cannot find module '/Taier/taier-ui/cup'

### ISSUE THREAD

**Issue by Shlpeng** [DTStack/Taier#230]
问题描述：linux 环境下：1，yarn版本：v1.22.17；2，node版本：v16.14.0；3，整体过程的回放：
![pRnxiDHxTb](https://user-images.githubusercontent.com/15671474/155463142-5f184ce5-7c45-4883-b4c1-d57f1e806483.png)

过程说明：
3.1，其中通过yarn global add pm2 mini-cup安装依赖不生效，所以通过npm install -g mini-cup和npm install -g pm2再次安装，但还是不生效（在用pm2 start cup启动时报 Cannot find module 错）

**Comment by mortalYoung** [comment]
可能是因为你之前安装过 cup 这个，你先通过 `npm uninstall -g cup` 把这个包删掉再试，否则会导致 cup 命令冲突

**Comment by Shlpeng** [comment]
> 可能是因为你之前安装过 cup 这个，你先通过 `npm uninstall -g cup` 把这个包删掉再试，否则会导致 cup 命令冲突

已经卸载了，但还是有问题

**Comment by Shlpeng** [comment]
我重新拉了一台新的机器，单纯只部署了前端，是ok的了

**Comment by mortalYoung** [comment]
试试看先 `which cup` 找到 cup 命令的位置，然后 cd 到命令所在的文件夹，然后再 `ll` 看看 `cup` 命令软链接的地方，然后再进去软链接所在的文件夹的地方，再 ll 一次看看真实地址是不是 `../mini-cup/app.js`

**Comment by Shlpeng** [comment]
cup -> ../lib/node_modules/mini-cup/app.js

**Comment by Shlpeng** [comment]
/usr/local/node/16.14.0/bin/cup -> ../lib/node_modules/mini-cup/app.js
