### ISSUE TITLE
绑定新租户时异常

### ISSUE THREAD

**Issue by Su1024** [DTStack/Taier#231]
在执行绑定新租户时发送异常

![image](https://user-images.githubusercontent.com/23012179/155483514-22b87835-6d1e-4cea-a7d4-17d434f3a8a8.png)

请求接口 500

![image](https://user-images.githubusercontent.com/23012179/155483583-e073695d-7ba2-451a-9fbd-d176e143b4ee.png)

看了后端日志
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/23012179/155483624-4ca42990-06f4-4ec6-bc89-115f20da0ae2.png">

debug看了下代码
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/23012179/155483841-8ab91710-ec67-4727-8eb3-3458c07abd34.png">

前端传入的 componentCode 为null

**Comment by QAQ-Jun** [comment]
看目前的现象是集群SparkThrift组件未配置或者SparkThrift未设置为元数据获取方式。正确的配置如下：
![image](https://user-images.githubusercontent.com/33590567/155484448-ffc539e8-5c00-4e23-9234-aedaad155e83.png)

**Comment by Su1024** [comment]
我check下

**Comment by Su1024** [comment]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/23012179/155490064-10afd20e-767d-4ac9-8938-57b004b81b85.png">
本地已经启动好了spark thriftserver 但是在多集群管理的时候 提示组件不支持
![image](https://user-images.githubusercontent.com/23012179/155490255-d84210b9-997c-45b9-9e6e-c3034aa9d653.png)

**Comment by Su1024** [comment]
> 看目前的现象是集群SparkThrift组件未配置或者SparkThrift未设置为元数据获取方式。正确的配置如下： ![image](https://user-images.githubusercontent.com/33590567/155484448-ffc539e8-5c00-4e23-9234-aedaad155e83.png)

感谢大佬 可以解决
