### ISSUE TITLE
查询数据时异常

### ISSUE THREAD

**Issue by Su1024** [DTStack/Taier#235]
![image](https://user-images.githubusercontent.com/23012179/155500230-b0416d76-ca88-45c6-8b60-8de3d09f8fa6.png)
在任务开发页面查询对应的数据 异常
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/23012179/155500297-c641a8af-64f0-4ee6-a57f-82eaab1e2c7d.png">

**Comment by vainhope** [comment]
确认下 data-develop 启动包里面i18n有打进去么

**Comment by Su1024** [comment]
这是我本地idea启动的的服务

**Comment by vainhope** [comment]
确认本地项目启动时候有依赖到taier-common
