### ISSUE TITLE
taier-ui 页面访问报错, 无法登陆用户

### ISSUE THREAD

**Issue by cheersmate1024** [DTStack/Taier#236]
![d3fda9641e582b7a1e9f9078279d8a0](https://user-images.githubusercontent.com/54657730/155677977-fb31fb17-c854-4761-a478-0f647dc7a576.png)

**chrome 访问taier-ui** 
![image](https://user-images.githubusercontent.com/54657730/155678319-8370f2a0-bda4-4355-aab4-97bf70a1b937.png)
**直接访问taier 端口**
![image](https://user-images.githubusercontent.com/54657730/155678406-388d7c4f-e6bf-48c1-832e-2878fcd44c52.png)

**engine_request.log** 
![image](https://user-images.githubusercontent.com/54657730/155678124-015c827a-1909-4ee7-aaff-6faa676663bc.png)

**rdos.err**
![image](https://user-images.githubusercontent.com/54657730/155678595-f87d34e5-8c4a-436f-8cbc-cad0ec134388.png)

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/155690805-6f9f23f6-e6a1-4f14-a2a9-b56b3a2baf77.png)

看日志 页面的请求是没有到taier到web后端到
确认下前端配置的web 后端url 是正确的么

**Comment by cheersmate1024** [comment]
感谢,解决了  是cup.config.js 没配置好
