### ISSUE TITLE
执行sparkSql 报错

### ISSUE THREAD

**Issue by cheersmate1024** [DTStack/Taier#249]
Error creating validator of type org.datanucleus.properties.CorePropertyValidator
![image](https://user-images.githubusercontent.com/54657730/156168544-f14e20bc-cb6b-47ae-b3dc-2adb3590da68.png)

**Comment by xiuzhu9527** [comment]
May be missing hive-site.xml

**Comment by cheersmate1024** [comment]
> May be missing hive-site.xml
hive-site.xml 是有配置的

**Comment by xiuzhu9527** [comment]
hive-site.xml中是否配置了metastore url

**Comment by cheersmate1024** [comment]
> hive-site.xml中是否配置了metastore url

解决了 是缺少jar包  谢谢
