### ISSUE TITLE
本地启动时一直死循环

### ISSUE THREAD

**Issue by bnyte** [DTStack/Taier#254]
如题项目本体启动时一直在死循环，是需要传入特殊参数或者特殊配置嘛？
![image](https://user-images.githubusercontent.com/75556346/156490286-0e0128d7-da94-45a0-be76-853ba9d41683.png)
![image](https://user-images.githubusercontent.com/75556346/156490307-f8834732-fdbf-4b93-8713-600deeb70c47.png)

**Comment by vainhope** [comment]
JobDealer包下的部分实现类 
会去启动线程 循环获取数据库里面数据信息做后续操作
不是死循环

**Comment by bnyte** [comment]
> JobDealer包下的部分实现类 会去启动循环获取里面的数据信息做操作 不是死循环

我已理解，辛苦。我现在关闭这个issue
