### ISSUE TITLE
windows local start project systemUserdir wrong directory separator

### ISSUE THREAD

**Issue by bnyte** [DTStack/Taier#255]
> English

When the project starts with Windows, the system code uses `/` as a split, which doesn't apply to Windows, so it may need to be fixed. Use the `File` tool provided by `Java` to solve him! !

> Chinese

当项目使用Windows系统启动时，系统代码采用`/`作为分割，这并不适用Windows系统，因此他可能需要修复。使用`Java`提供的`File`工具解决他！！

> bug screenshot

![image](https://user-images.githubusercontent.com/75556346/156709358-223c5d52-2941-4d33-8636-4107ae2670aa.png)

> error log

```
14:09:42.014 [main] ERROR com.dtstack.taier.develop.TaierApplication - start error:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.dtstack.taier.common.util.SystemPropertyUtil.setSystemUserDir(SystemPropertyUtil.java:37)
	at com.dtstack.taier.develop.TaierApplication.main(TaierApplication.java:49)
```

**Comment by vainhope** [comment]
后面会修复这个问题

**Comment by bnyte** [comment]
> 后面会修复这个问题

可以的话我可以提交PR完善它

**Comment by vainhope** [comment]
可以的 辛苦
