### ISSUE TITLE
idea 本地执行mvn clean install -Dmaven.test.skip报错

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/Taier#257]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :plugins.dummy

**Comment by vainhope** [comment]
请通过 build/目录下 mvn-build.sh 试下

**Comment by momisabuilder** [comment]
谢谢，可以了。
但是，我这边遇到一个问题，执行脚本mvn-build.sh，会闪退，通过将脚本中的命令粘贴出来，放在idea terminal终端执行，即可。


mvn clean package -DskipTests -T 1C -pl taier-data-develop,taier-worker/taier-plugins/dummy,taier-worker/taier-plugins/flink/common,taier-worker/taier-plugins/flink/yarn3-hdfs3-flink110,taier-worker/taier-plugins/flink/yarn2-hdfs2-flink110,taier-worker/taier-plugins/spark/yarn3-hdfs3-spark210/spark-yarn-client,taier-worker/taier-plugins/spark/yarn3-hdfs3-spark210/spark-sql-proxy,taier-worker/taier-plugins/spark/yarn2-hdfs2-spark210/spark-yarn-client,taier-worker/taier-plugins/spark/yarn2-hdfs2-spark210/spark-sql-proxy,taier-worker/taier-plugins/hadoop/yarn3-hdfs3-hadoop3,taier-worker/taier-plugins/hadoop/yarn2-hdfs2-hadoop2,taier-worker/taier-plugins/stores/hdfs2,taier-worker/taier-plugins/stores/hdfs3,taier-worker/taier-plugins/schedules/yarn2,taier-worker/taier-plugins/schedules/yarn3,taier-worker/taier-plugins/rdbs/hive,taier-worker/taier-plugins/rdbs/hive2,taier-worker/taier-plugins/rdbs/hive3 -am




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月4日(星期五) 下午3:37
收件人: ***@***.***&gt;; 
抄送: "烦不烦 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DTStack/Taier] idea 本地执行mvn clean install -Dmaven.test.skip报错 (Issue #257)





 
请通过 build/目录下 mvn-build.sh 试下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vainhope** [comment]
脚本后面添加-D参数 看下mvn 构建日志

**Comment by bnyte** [comment]
> 不过，我遇到一个问题，执行mvn-build.sh，会闪退，通过将脚本中的命令粘贴出来，导致终端执行，启动vn-build.sh。 mvn clean package DskipTests -T 1C -pl taier-data-develop,taier-worker/taier-plugins/dummy,taier-worker/taier-plugins/flink/common,taier-worker/taier-plugins/flink/yarn3-hdfs3-flink110, taier-worker/taier-plugins/flink/yarn2-hdfs2-flink110,taier-worker/taier-plugins/spark/yarn3-hdfs3-spark210/spark-yarn-client,taier-worker/taier-plugins/spark/yarn3- hdfs3-spark210/spark-sql-proxy,taier-worker/taier-plugins/spark/yarn2-hdfs2-spark210/spark-yarn-client,taier-worker/taier-plugins/spark/yarn2-hdfs2-spark210/spark- sql-proxy,taier-worker/taier-plugins/hadoop/yarn3-hdfs3-hadoop3,taier-worker/taier-plugins/hadoop/yarn2-hdfs2-hadoop2,taier-worker/taier-plugins/stores/hdfs2,taier- worker/taier-plugins/stores/hdfs3,taier-worker/taier-plugins/schedules/yarn2,taier-worker/taier-plugins/schedules/yarn3,taier-worker/taier-plugins/rdbs/hive,taier-worker/taier-plugins/rdbs/hive2,taier-worker/taier-plugins/rdbs/hive3 -am
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年3月4日(星期五) 下午3:37 收件人: ***@***.***&gt;; 抄送: "烦不烦 ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [DTStack/Taier] idea 本地执行mvn clean install -Dmaven.test.skip报错 (Issue #257) 请通过 build/目录下 mvn-build.sh 试下 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，执行mvn clean install时吧 `build`中的插件拷贝到`$TAIER_PATH`下面然后执行`mvn-build.sh`等脚本即可完成编译

**Comment by vainhope** [comment]
好的
