### ISSUE TITLE
taier-ui 执行yarn build时候报错

### ISSUE THREAD

**Issue by zuoinlv** [DTStack/Taier#265]
![image](https://user-images.githubusercontent.com/3855382/157175587-38639ca5-6b79-49d0-90fb-2a7a4046d15c.png)

在执行yarn build编译 taier ui的时候报错，这个要怎么解决？

**Comment by mortalYoung** [comment]
修复了该问题，按照以下步骤重新构建即可
1. 拉去 master 分支最新的代码
2. 删除当前目录下的 node_modules 文件夹和 yarn.lock 文件
3. 重新执行 yarn 命令以及 yarn build 命令即可
