### ISSUE TITLE
Index column size too large. The maximum column size is 767 bytes.

### ISSUE THREAD

**Issue by nysyxxg** [DTStack/Taier#269]
mysql 版本：mysql-5.6.30-win32
建表语句：
 CREATE TABLE schedule_job_expand
(
	id INT AUTO_INCREMENT
		PRIMARY KEY,
	job_id VARCHAR(256) NOT NULL COMMENT '工作任务id',
	retry_task_params MEDIUMTEXT NULL COMMENT '重试任务参数',
	job_graph MEDIUMTEXT NULL COMMENT 'jobGraph构建json',
	job_extra_info MEDIUMTEXT NULL COMMENT '任务提交额外信息',
	engine_log LONGTEXT COLLATE utf8mb4_bin NULL,
	log_info LONGTEXT NULL COMMENT '错误信息',
	gmt_create DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '新增时间',
	gmt_modified DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间',
	is_deleted TINYINT(1) DEFAULT 0 NOT NULL COMMENT '0正常 1逻辑删除',
	CONSTRAINT index_job_id  UNIQUE (job_id)
);
错误码: 1709
Index column size too large. The maximum column size is 767 bytes.

Execution Time : 00:00:00:000
Transfer Time  : 00:00:00:000
Total Time     : 00:00:00:000

原因：job_id VARCHAR(256) NOT NULL COMMENT '工作任务id',   
请问： 长度过长，这个算问题吗？

**Comment by vainhope** [comment]
5.6 是由索引长度限制的
目前jobId的生成规则应该只有12位
可以的话 可以提个pr修复 或者等后面同理梳理处理下
