### ISSUE TITLE
所有周期实例没有正常调度

### ISSUE THREAD

**Issue by zuoinlv** [DTStack/Taier#272]
![image](https://user-images.githubusercontent.com/3855382/157572782-82af238d-0089-472e-9ffa-4e9e5c3d15b4.png)
[engine-log.zip](https://github.com/DTStack/Taier/files/8219617/engine-log.zip)

任务周期性实例未能正常调度执行，附件是相关日志。

**Comment by dtdazhi** [comment]
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/88131825/157576853-6aa99b4e-64fb-4418-8158-c0d4dd3e8ac0.png">
imp_dim_public_adcode_df这个任务是不是自依赖任务，9号是不是有任务没有运行完成？

**Comment by zuoinlv** [comment]
9号只有补数据的任务，我9号才提交到调度系统的

**Comment by dtdazhi** [comment]
这样 你看一下imp_dim_public_adcode_df这个的任务最近时间没有执行的实例（如果全部没有执行理论上是0点那个任务），你F12打开开发者工具，点击查看日志，有一个接口/taier/action/queryJobLog，入参有一个jobId，把这个jobid记录下来。
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/88131825/157578417-ff4fcc9f-2489-4f99-89e7-700b4654900e.png">

然后去 在数据库里面执行 sql:
SELECT * FROM schedule_job_job WHERE job_key IN (SELECT job_key FROM schedule_job WHERE job_id = "${jobId}")
看一下数据，最好截图一下  注意： ${jobId} 是你在页面上记录的jobId

**Comment by zuoinlv** [comment]
![querylog](https://user-images.githubusercontent.com/3855382/157580285-cd63d4ae-e1d5-406a-bb6f-8b7aaa778512.png)
![sqlquery](https://user-images.githubusercontent.com/3855382/157580286-3768bad5-bcdd-4c84-83ff-dee59d263d37.png)

数据库里没有查到记录。

**Comment by dtdazhi** [comment]
我查看了一下日志jobId:4i8ine37l6l0的实例，在判断资源的时候，没有通过导致只能在等待运行。

查看一下控制台，找到这个实例，看一下等待原因是什么：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/88131825/157581959-46691b47-b932-4299-9fdf-79f3ca8eb583.png">
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/88131825/157581938-224f9ccc-31bc-47b4-8551-e62378d2c683.png">

还有一点： 看一下consoleflink集群的prometheus是不是配置了，你上面截图的日志显示在控制台上面找不到prometheus的配置

**Comment by zuoinlv** [comment]
![image](https://user-images.githubusercontent.com/3855382/157590200-64425730-365b-40fc-bb8e-dc376f57f679.png)

显示Flink session cluster有问题

**Comment by vainhope** [comment]
Flink session 拉起的日志在engine_flink_monitor.log
可以的话 麻烦贴一下日志

**Comment by zuoinlv** [comment]
![image](https://user-images.githubusercontent.com/3855382/160055954-ddac6402-2b7b-4e74-8b52-c9ccfa3ae451.png)
日志里一直反复报“The file jar /data/insight_plugin/flink110_lib  path is not exist“， 我手工在hdfs上面创建了，也还是不行

**Comment by zuoinlv** [comment]
这个问题已经解决了，需要在本地创建改目录，并拷贝flink 的lib目录下的jar包。这个配置好了，出现了新的问题：
![image](https://user-images.githubusercontent.com/3855382/160320320-b25bbcee-57dc-4399-8f05-9e17880112a0.png)

**Comment by zuoinlv** [comment]
已解决，需要本地创建对应目录

**Comment by zuoinlv** [comment]
已解决，需要本地创建对应目录
