### ISSUE TITLE
sqlservercdc 写入sqlserver报错

### ISSUE THREAD

**Issue by littlezhaozhaozhao** [DTStack/Taier#278]
@WTZ468071157 
<img width="772" alt="lQLPDhs5ycsMxMbNAf_NBgiw1vZ7OXXasakCL1p9CMBJAA_1544_511" src="https://user-images.githubusercontent.com/31729002/157796884-59466d1a-3dde-4826-b0a2-552b49fc298a.png">
[报错信息和json配置.zip](https://github.com/DTStack/Taier/files/8228900/json.zip)

请大佬 帮忙看看

**Comment by vainhope** [comment]
请提交到对应的项目下 
https://github.com/DTStack/chunjun
