### ISSUE TITLE
TaskmanagerInfo实体，能从taskmanager日志中解析出读写条数吗

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/Taier#284]
**建议先去浏览下文档和部署常见问题**
[快速开始](https://dtstack.github.io/Taier/)
[部署常见问题](https://github.com/DTStack/Taier/issues/260)

**bug场景描述**

**bug日志信息或数据信息**

**bug相关代码**

**提示的异常或者没有达到的效果**

**Comment by vainhope** [comment]
不能解析出来
