### ISSUE TITLE
metrics.reporter.promgateway.class 和 prometheusClass区别是？

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/Taier#286]
你好咨询问题：指标打入到普鲁米修斯中，请问用的是下面哪个类？
"metrics.reporter.promgateway.class":"org.apache.flink.metrics.prometheus.PrometheusPushGatewayReporter",
"prometheusClass":"com.dtstack.jlogstash.metrics.promethues.PrometheusPushGatewayReporter",

**Comment by xiuzhu9527** [comment]
metrics.reporter.promgateway.class=org.apache.flink.metrics.prometheus.PrometheusPushGatewayReporter
