### ISSUE TITLE
Taier数据同步的任务是正常运行成功，过程信息不正确，显示为0

### ISSUE THREAD

**Issue by jehu654** [DTStack/Taier#351]
![微信图片_20220408163940](https://user-images.githubusercontent.com/55435255/162399072-33854949-3797-453e-8e9d-a4a04e34e54c.png)
实际同步是有数据的

**Comment by jiemotongxue** [comment]
补充问题描述，flink web ui 报错日志

![image](https://user-images.githubusercontent.com/16730029/162671563-4fad7a4f-301e-4e2a-b7aa-5e47e35104de.png)

**Comment by jiemotongxue** [comment]
问题背景：flink运行有指标，taier运行的时候没有， 并且promethues pushgateway上就没有job数据；  

解决结论：检查下面第一个图，图中这个配置的路径下，没有下面第二个图中的jar；需要从flink安装包中找到jar包，并在yarn 界面kill flink session的application（有可执行的session 的数据同步任务，taier 会自动拉起flink session）

![image](https://user-images.githubusercontent.com/16730029/162671707-9c32d6e9-a4ca-4e0a-9136-b33b33e6e565.png)

![image](https://user-images.githubusercontent.com/16730029/162671731-2b9e9d12-ba9e-41f7-8fc4-72da527008f2.png)
