### ISSUE TITLE
周期实例生成，未能正常调度运行，补数据实例可以正常运行

### ISSUE THREAD

**Issue by zuoinlv** [DTStack/Taier#355]
![65E38E3F-7F1F-46bb-A5EB-ED4EA445221A](https://user-images.githubusercontent.com/3855382/162856469-f021c603-95b8-4918-8791-4df2b69bdbd8.png)

第一个实例jobId:
![image](https://user-images.githubusercontent.com/3855382/162856565-ddaf63e5-037c-49eb-a1a5-631ab75bc601.png)

数据库相关实例截图：

![image](https://user-images.githubusercontent.com/3855382/162856509-31f0a3f7-a500-4724-b561-19fce7375885.png)

控制台队列截图：
![image](https://user-images.githubusercontent.com/3855382/162856668-af506289-f295-46e5-a81f-12c5054d632f.png)

**Comment by vainhope** [comment]
看数据信息
![image](https://user-images.githubusercontent.com/18212930/163087842-f25286c4-d81c-4f73-91a8-bbda19323807.png)

任务配置的是自依赖
需要确认下这个任务的前几次周期是否运行结束

并且任务的运行时间是否超过

时间范围

**Comment by zuoinlv** [comment]
![image](https://user-images.githubusercontent.com/3855382/164352762-845480f2-9b8a-4e67-8768-f60302470e44.png)
前一周期实例是因为手工取消了，如果手工置成功，则可以调度
