### ISSUE TITLE
计算组件只能添加一个组件

### ISSUE THREAD

**Issue by gaoasi** [DTStack/Taier#356]
问题描述：
     第一次添加计算组件，先添加一个sparkThrift组件，然后保存，点完成。
     然后再一次编辑集群信息，再添加一个spark组件，上一次保存的sparkThrift的配置信息会被重置，而且重新配置好sparkThrift和spark组件之后，点击保存组件 ，页面没有反应，无法保存，也没有调后端保存接口，点击 测试所有组件连通性 页面提示检查配置，但是所有必填配置都已填写

页面截图：
![image](https://user-images.githubusercontent.com/43560964/162930837-de027207-1709-44be-baae-3a9c838ca1c2.png)
![image](https://user-images.githubusercontent.com/43560964/162931050-4482a7ef-e26c-49bf-82e1-4fecba6169d5.png)
所有必填配置都已填写：
![image](https://user-images.githubusercontent.com/43560964/162934832-0d97252b-c6de-4442-8c21-b73848fd073f.png)
![image](https://user-images.githubusercontent.com/43560964/162934947-594a322c-9d8f-4017-ab49-891544828586.png)
![image](https://user-images.githubusercontent.com/43560964/162935000-b4824057-fab5-4a25-b26c-5be61af72392.png)
![image](https://user-images.githubusercontent.com/43560964/162935079-803210d3-e341-449c-ab49-370812646b08.png)

![image](https://user-images.githubusercontent.com/43560964/162935155-1d431443-490d-4276-97b1-4fc82f2e20b0.png)

**Comment by gaoasi** [comment]
使用的是 master分支编译

**Comment by gaoasi** [comment]
@mortalYoung  按照commit修改这两个文件后，重启服务，登不上去了，报404
![image](https://user-images.githubusercontent.com/43560964/163314087-ee0bf768-f45a-4848-937f-8f2e3711d7d2.png)

![image](https://user-images.githubusercontent.com/43560964/163313949-3fd20ab9-2ef0-41b3-bbd6-3796c9e20a97.png)

**Comment by mortalYoung** [comment]
> @mortalYoung 按照commit修改这两个文件后，重启服务，登不上去了，报404 ![image](https://user-images.githubusercontent.com/43560964/163314087-ee0bf768-f45a-4848-937f-8f2e3711d7d2.png)
> 
> ![image](https://user-images.githubusercontent.com/43560964/163313949-3fd20ab9-2ef0-41b3-bbd6-3796c9e20a97.png)

本地前端文件修改后，需要重新执行 `yarn build` 并重启服务才能生效。如果不急的话，可以等 1.0.1 发版等修复

**Comment by gaoasi** [comment]
@mortalYoung ，执行了的，我先执行的yarn，把依赖重新拉了一遍，然后执行yarn build，重启其服务，访问网页报404，回滚到之前的版本就没问题

**Comment by mortalYoung** [comment]
> @mortalYoung ，执行了的，我先执行的yarn，把依赖重新拉了一遍，然后执行yarn build，重启其服务，访问网页报404，回滚到之前的版本就没问题，但是我这边跟本地编译不太一样，我是本地编译好，然后把taier-ui打包上传到服务器上，这样会有影响吗，对前端不太了解

检查一下打包上传到服务器上后，nginx 配置的 root 路径是否是 dist 文件所在的路径，参考：https://github.com/DTStack/Taier/blob/04ab6ae24a0629eb2a51e427cada2294cf7a454e/taier-ui/docker/nginx.conf#L19-L23

**Comment by gaoasi** [comment]
@mortalYoung 用的是pm2 start cup 启动
![image](https://user-images.githubusercontent.com/43560964/163337263-01bc4acc-e001-4acf-b608-4e057690b51b.png)

**Comment by mortalYoung** [comment]
@gaoasi 那就检查一下上传到服务器上后 cup.config.js 同级别目录下是否存在 dist 文件夹

**Comment by gaoasi** [comment]
@mortalYoung 有的，我是把编译后的整个taier-ui copy过来的
![image](https://user-images.githubusercontent.com/43560964/163511220-59ed2577-1add-450c-866a-cad37b4fba43.png)

**Comment by mortalYoung** [comment]
> @mortalYoung 有的，我是把编译后的整个taier-ui copy过来的 ![image](https://user-images.githubusercontent.com/43560964/163511220-59ed2577-1add-450c-866a-cad37b4fba43.png)

试试看重启 cup，先 `pm2 stop id` , 再 `pm2 delete id` , 然后再 `pm2 start cup`

**Comment by gaoasi** [comment]
@mortalYoung 还是不行

**Comment by mortalYoung** [comment]
> @mortalYoung 还是不行

我这边暂时无法复现你的问题，我推测是打包的产物有问题，你可以看一下 dist 文件夹下面是不是没有 index.html 了

**Comment by gaoasi** [comment]
@mortalYoung 有index.html这个文件，方便把你本地的编译好的dist上传一下吗

**Comment by mortalYoung** [comment]
> @mortalYoung 有index.html这个文件，方便把你本地的编译好的dist上传一下吗

你试一下直接通过 `cup` 启动服务，看看日志内容

**Comment by gaoasi** [comment]
@mortalYoung 日志没啥东西
![image](https://user-images.githubusercontent.com/43560964/163746643-be1674d6-e9d6-4f7e-a79e-3579f4a1132b.png)

**Comment by mortalYoung** [comment]
> @mortalYoung 日志没啥东西 ![image](https://user-images.githubusercontent.com/43560964/163746643-be1674d6-e9d6-4f7e-a79e-3579f4a1132b.png)

日志上写了 `The app is running at` 说明项目是启动成功的，如果你 `curl http://localhost:8090` 应该是有东西的

**Comment by wewoor** [comment]
@gaoasi 你好，能看下 `dist` 目录下的文件内容吗？另外你有没有尝试直接使用 `nginx` 作为 `server` 来测试部署前端文件

**Comment by gaoasi** [comment]
@wewoor 有内容的，算了，我放弃了
