### ISSUE TITLE
租户与集群绑定出现报错

### ISSUE THREAD

**Issue by jehu654** [DTStack/Taier#358]
**建议先去浏览下文档和部署常见问题**
[快速开始](https://dtstack.github.io/Taier/)
[部署常见问题](https://github.com/DTStack/Taier/issues/260)

**bug场景描述**
配置好Kerberos认证的集群后，进行租户与集群绑定，出现报错

**bug日志信息或数据信息**
![image](https://user-images.githubusercontent.com/55435255/163084517-08281dee-fe0f-426a-85bc-e5ac0cea8893.png)
![image](https://user-images.githubusercontent.com/55435255/163084587-95f25182-a17e-48d1-88a5-5b2c0ddaa048.png)

**提示的异常或者没有达到的效果**
![image](https://user-images.githubusercontent.com/55435255/163084691-a24f11ab-dfe5-41d4-ab0a-ead960873262.png)

**Comment by QAQ-Jun** [comment]
这边需要你确定下sourceSftpPath路径是什么样的，因为看代码逻辑没多大问题，推测可能是路径的问题，所以希望你这边debug下代码，确定下sourceSftpPath的值
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/33590567/163096367-bceecac9-4170-4ede-9fe0-c243f26c7127.png">

**Comment by jehu654** [comment]
> 这边需要你确定下sourceSftpPath路径是什么样的，因为看代码逻辑没多大问题，推测可能是路径的问题，所以希望你这边debug下代码，确定下sourceSftpPath的值 <img alt="image" width="1241" src="https://user-images.githubusercontent.com/33590567/163096367-bceecac9-4170-4ede-9fe0-c243f26c7127.png">

这个是在哪里配置的呢？是这个吗？
![image](https://user-images.githubusercontent.com/55435255/163097353-0c1b1ca3-0e84-4537-9342-b5657037ee90.png)

因为我不是专业开发，在Linux下不知道怎么debug

**Comment by bnyte** [comment]
> > 这边需要你确定下sourceSftpPath路径是什么样的，因为看代码逻辑没多大问题，推测可能是路径的问题，所以希望你这边debug下代码，确定下sourceSftpPath的值 <img alt="image" width="1241" src="https://user-images.githubusercontent.com/33590567/163096367-bceecac9-4170-4ede-9fe0-c243f26c7127.png">
> 
> 这个是在哪里配置的呢？是这个吗？ ![image](https://user-images.githubusercontent.com/55435255/163097353-0c1b1ca3-0e84-4537-9342-b5657037ee90.png)
> 
> 因为我不是专业开发，在Linux下不知道怎么debug

![image](https://user-images.githubusercontent.com/75556346/163145750-d2a5c245-4163-4a68-8d81-75064c8112a8.png)
请问你这台服务器的这个文件目录是否确实存在呢

**Comment by jehu654** [comment]
存在的

**Comment by jehu654** [comment]
![image](https://user-images.githubusercontent.com/55435255/163206929-52fe563c-bbff-4f36-a086-678958d4f970.png)
集群管理里全部组件都显示连通，但是绑定集群时报这个错

**Comment by jehu654** [comment]
![image](https://user-images.githubusercontent.com/55435255/163296859-8c7b6d3f-032d-40c1-8055-6707b7d6093a.png)
![image](https://user-images.githubusercontent.com/55435255/163296977-6dcc75ca-d883-4968-858d-ec307a500e3e.png)
![image](https://user-images.githubusercontent.com/55435255/163297044-59615ad9-eb52-459a-b5e6-8c232abfd0c2.png)

**Comment by bnyte** [comment]
> ![image](https://user-images.githubusercontent.com/55435255/163296859-8c7b6d3f-032d-40c1-8055-6707b7d6093a.png) ![image](https://user-images.githubusercontent.com/55435255/163296977-6dcc75ca-d883-4968-858d-ec307a500e3e.png) ![image](https://user-images.githubusercontent.com/55435255/163297044-59615ad9-eb52-459a-b5e6-8c232abfd0c2.png)

从 Hive 连接中删除用户名和密码，保存并重新运行作业。你试试看看可以不。
