### ISSUE TITLE
上传Kerberos测试联通性报错，无法获取上传文件

### ISSUE THREAD

**Issue by bnyte** [DTStack/Taier#364]
# 上传Kerberos测试联通性报错
- 场景描述

> 上传kerberos会走AOP修饰注解`@FileUpload`获取上传的文件，但是无法获取因为接口用的是`丝袜哥`的`ApiParam`

- 错误代码

![image](https://user-images.githubusercontent.com/75556346/163513989-9d032ae9-5e07-48ba-a459-2da24cd2d38c.png)

**Comment by bnyte** [comment]
本地正在修

**Comment by bnyte** [comment]
前端跑不起来不好修，改完了要配合前端测试

![image](https://user-images.githubusercontent.com/75556346/163671449-9b354e37-9429-4aeb-811d-53d6092e5ede.png)

![image](https://user-images.githubusercontent.com/75556346/163671468-4ebaad76-88fc-4885-98ed-b23eabed7546.png)

**Comment by mortalYoung** [comment]
> 前端跑不起来不好修，改完了要配合前端测试
> 
> ![image](https://user-images.githubusercontent.com/75556346/163671449-9b354e37-9429-4aeb-811d-53d6092e5ede.png)
> 
> ![image](https://user-images.githubusercontent.com/75556346/163671468-4ebaad76-88fc-4885-98ed-b23eabed7546.png)
> 
> @vainhope

检查一下 @dtinsight/molecule 的版本

**Comment by bnyte** [comment]
> > 前端跑不起来不好修，改完了要配合前端测试
> > ![image](https://user-images.githubusercontent.com/75556346/163671449-9b354e37-9429-4aeb-811d-53d6092e5ede.png)
> > ![image](https://user-images.githubusercontent.com/75556346/163671468-4ebaad76-88fc-4885-98ed-b23eabed7546.png)
> > @vainhope
> 
> 检查一下 @dtinsight/molecule 的版本，目前的 latest 版本是 0.9.0-beta.4.2，如果不是最新的版本更新一下

![image](https://user-images.githubusercontent.com/75556346/163673158-71704a8a-0828-4a4d-bb51-724c892854c1.png)

不是最新的，你看你那边是吧最新版本的package.json文件推一下还是我一起pr上去

**Comment by bnyte** [comment]
![image](https://user-images.githubusercontent.com/75556346/163673284-a20da317-2672-483c-ba25-5325e7b81ee5.png)

![image](https://user-images.githubusercontent.com/75556346/163673290-8ba52b0e-710d-4655-8957-61efc57b6e5c.png)


 用了最新版本之后还是会有问题

**Comment by mortalYoung** [comment]
你当前的分支 behind master 有点多了，建议是 rebase 一下 master 分支或者 merge 一下当前的 mater 分支

**Comment by mortalYoung** [comment]
我们在 #266 修复过这个问题

**Comment by bnyte** [comment]
> 我们在 #266 修复过这个问题

好的，那我回家merge一下，但是我每次pr之前都会upstream哇

**Comment by bnyte** [comment]
fix to pr #370
