### ISSUE TITLE
mysql数据同步任务开启后，一直提示“任务等待”

### ISSUE THREAD

**Issue by windwhisper-i** [DTStack/Taier#372]
engine_all.log  日志提示信息截图：
![image](https://user-images.githubusercontent.com/73170854/163903799-1d50c4dc-5d74-4e23-8072-49ecb5cf7743.png)
engine_flink_monitor.log日志信息截图：在计算组件flink中已经修改参数：flinkJarPath、flinkPluginRoot、remotePluginRootDir
![image](https://user-images.githubusercontent.com/73170854/163903988-5b9ec87f-11b7-44f7-b96f-49741281fef0.png)

**Comment by vainhope** [comment]
麻烦日志问题贴一下哈 还有运行的任务ID

**Comment by windwhisper-i** [comment]
![image](https://user-images.githubusercontent.com/73170854/163905100-e0d8a73d-f535-46cd-925f-3d0a3f726b48.png)
![image](https://user-images.githubusercontent.com/73170854/163905184-dc4b010e-dd55-496d-a25e-912e010699b1.png)
任务ID: 4iigr4092qt0

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/163905748-137705bc-529c-4ea0-a9a5-fd58387e0951.png)
日志文件可以放上来么

**Comment by windwhisper-i** [comment]
![image](https://user-images.githubusercontent.com/73170854/163906456-7f57ce53-f656-4fca-9daf-e1a9127e7de3.png)
我重启后台服务，错误提示变了
[engine_all.log](https://github.com/DTStack/Taier/files/8509231/engine_all.log)
[engine_flink_monitor.log](https://github.com/DTStack/Taier/files/8509232/engine_flink_monitor.log)

**Comment by vainhope** [comment]
1.10的 flinkx的目录结构是这样子的
![image](https://user-images.githubusercontent.com/18212930/163907517-37df6082-83c9-4b6e-b09f-1ba047dda202.png)

对应的flinkPluginRoot 为 /opt/dtstack/110_flinkplugin

**Comment by windwhisper-i** [comment]
不是安装【flink-1.10.0-bin-scala_2.11.tgz】对应的安装目录中的plugins目录吗
![image](https://user-images.githubusercontent.com/73170854/163909581-12770042-60b1-47c6-8800-c147a334acd0.png)

**Comment by vainhope** [comment]
是的

**Comment by windwhisper-i** [comment]
好的，我修改后再试试

**Comment by windwhisper-i** [comment]
任务ID:  4iiic640jpl0

![image](https://user-images.githubusercontent.com/73170854/163939147-e3fb6dff-b3ad-461f-af0a-e385a8c33863.png)
![image](https://user-images.githubusercontent.com/73170854/163939207-070875fb-c274-4850-90e5-4d63d470625a.png)

**Comment by vainhope** [comment]
flinkPluginRoot = /rt/software/DTStack

sycnplugins是flinkx编译jar就默认有的 所以不配置的这一层级

**Comment by windwhisper-i** [comment]
我只上传了sycnplugins这一个目录到服务器（没有上传整个项目）， /rt/software/DTStack这样配置没问题吧

**Comment by vainhope** [comment]
可以的

**Comment by windwhisper-i** [comment]
还是报这个错：syncPlugin path is null 
![image](https://user-images.githubusercontent.com/73170854/163944098-119d62d9-9c20-452b-8f9d-dd4708e04b9c.png)

**Comment by vainhope** [comment]
应该是
![image](https://user-images.githubusercontent.com/18212930/163958470-de90f9f8-9183-4f7c-97a5-835d5dcc8e89.png)
 不带s

**Comment by helpudie** [comment]
您好 解决 了吗，不带S是什么意思呀

**Comment by windwhisper-i** [comment]
解决了，chunjun项目编译完成后，生成sycnplugins目录，在taier控制台-集群管理-计算组件-flink中字段：flinkPluginRoot 配置为sycnplugins目录的上级目录，但需要把【sycnplugins】目录名改成【sycnplugin】
