### ISSUE TITLE
Taier能支持windows下部署开发吗

### ISSUE THREAD

**Issue by zuoinlv** [DTStack/Taier#379]
taier能支持windows下开发工具idea上，进行部署开发吗

**Comment by bnyte** [comment]
支持的

**Comment by bnyte** [comment]
- 打开`bash`命令控制面板行执行脚本`${TAIER_HOME}/build/mvn-build.sh`会将依赖插件加载
- [下载DataSourceX](https://github.com/DTStack/DatasourceX/releases/download/v4.3.0/datasourceX.zip)并解压
- 在`${TAIER_HOME}/conf/application.properties`中的`datasource.plugin.path`配置指定你刚刚下载的`DataSourceX`插件解压后的根目录
- 配置配置数据库启动`TaierApplication`就可以了

**Comment by zuoinlv** [comment]
![image](https://user-images.githubusercontent.com/3855382/164382185-3d656432-ceb1-45ee-879e-e684b71c6e7d.png)
本地启动成功之后，输入账号和密码登录之后，ui端报错了

**Comment by bnyte** [comment]
> ![image](https://user-images.githubusercontent.com/3855382/164382185-3d656432-ceb1-45ee-879e-e684b71c6e7d.png) 本地启动成功之后，输入账号和密码登录之后，ui端报错了

![image](https://user-images.githubusercontent.com/75556346/164384863-6e114666-7f09-43b9-afc9-ab762a7fa699.png)
