### ISSUE TITLE
Taier数据同步无法从pushgateway获取过程信息

### ISSUE THREAD

**Issue by jehu654** [DTStack/Taier#381]
![image](https://user-images.githubusercontent.com/55435255/164578739-464a8267-afec-44d4-97e7-5c5f7d8da4ee.png)

**端口都telnet过，都是通的**

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/164580819-28978494-d13a-4273-8306-a15e3491153a.png)

flink里 这个二个配置项是正确吗
并且任务的计算节点和 对应的ip port通的吗

**Comment by jehu654** [comment]
正确的，ip端口都是通的，taier跟flink都是部署在同一个集群

**Comment by xiuzhu9527** [comment]
你好，你是在taier节点还是在flink计算节点上执行telnet的？

**Comment by jehu654** [comment]
集群是三台机，taier部署在其中一台，flink三台都有，都是互通的
