### ISSUE TITLE
配置mongodb数据源后，创建任务时无法选择mongodb任务

### ISSUE THREAD

**Issue by windwhisper-i** [DTStack/Taier#391]
![image](https://user-images.githubusercontent.com/73170854/165267331-7224e3f6-7285-4a07-a904-fa7c2f7a4984.png)

**Comment by vainhope** [comment]
https://dtstack.github.io/Taier/docs/functions/task

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/165530700-cfe20de3-d649-46e6-b97e-5574a32e8ff0.png)
目前向导模式暂不支持MongoDB
