### ISSUE TITLE
多类型集群支持

### ISSUE THREAD

**Issue by bnyte** [DTStack/Taier#396]
不知道后续会不会有多类型集群的支持呢，如`Doris`这些，我在chunjun问过，让我过来这边问一下taier,对了可以加个`doubt` or `help`的label

**Comment by vainhope** [comment]
可以描述下具体场景么

**Comment by vainhope** [comment]
如果有想法来自己开发Doris 可以钉钉一起沟通下 yuebai@dtstack.com

**Comment by bnyte** [comment]
> 如果有想法来自己开发Doris 可以钉钉一起沟通下 [yuebai@dtstack.com](mailto:yuebai@dtstack.com)

钉钉不存在 15555515953
