### ISSUE TITLE
绑定新租户时：获取组件标识:HDFS，信息为空

### ISSUE THREAD

**Issue by LiYouliang** [DTStack/Taier#404]
# 部署背景
- docker-compose快速部署
- 版本为docker hub上的最新版（2022.4.7更新）

# **场景描述**

## 已经完成设置

- [x] 控制台 -> 多集群管理 -> 集群配置（SFTP，YARN，HDFS，SparkThrift）
- [x] 测试所有组件连通性

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/2577525/167058390-fdaaeea2-c888-451e-afcc-9eaa1a3821e8.png">

## 失败地方

- [ ] 控制台 -> 资源管理 -> 绑定新租户 -> 对接已有SparkThrift -> 对接目标

**对接目标**下拉列表为空，前端提示：**集群ID:1，获取组件标识:HDFS，信息为空**

<img width="914" alt="image" src="https://user-images.githubusercontent.com/2577525/167058191-d2896299-175d-4b01-a2ce-7356abefa331.png">

# **日志信息**
## 报错请求
`Uri: /taier/batchComponent/getAllDatabases, Params: {"componentTypeCode":4,"clusterId":1}`

## 后端日志
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/2577525/167058781-6c3e733f-324b-4f7f-ac24-68346b8b661f.png">

# **相关代码**
https://github.com/DTStack/Taier/blob/029b9a325c56794b280ba344959fccb8b1171c94/taier-data-develop/src/main/java/com/dtstack/taier/develop/utils/develop/service/impl/Engine2DTOService.java#L609

```java
    /**
     * 获取 Hadoop 集群信息
     *
     * @param tenantId
     * @return
     */
    private static Map<String, Object> getHdfsInfo(Long tenantId) {
        JSONObject data = getComponentConfig(tenantId, EComponentType.HDFS);
        if (data == null) {
            throw new DtCenterDefException(String.format(ERROR_MSG_CLUSTER_INFO, tenantId, EComponentType.HDFS.name()));
        }
        return JSONObject.parseObject(data.toJSONString(), Map.class);
    }
```

**Comment by bnyte** [comment]
你好是不是可以debug看看这个位置传入的`tenantId`参数值呢 这个位置应该是`clusterId`未找到会使用默认的`-1`的确定一下是不是转换了

**Comment by QAQ-Jun** [comment]
现在看了下，是这个地方需要代码调整下，代码里还是拿了租户ID去判断，应该直接拿集群ID。

就目前而言，是否可以先直接通过创建的时候进行绑定集群呢。创建的话，就是会在SparkThrift下创建一个以租户名称为名的db

**Comment by LiYouliang** [comment]
> 你好是不是可以debug看看这个位置传入的`tenantId`参数值呢 这个位置应该是`clusterId`未找到会使用默认的`-1`的确定一下是不是转换了

- 传入的是`tenantId`，根据返回信息`集群ID:1`得知该值为`1`：
![image](https://user-images.githubusercontent.com/2577525/167071938-44a3600c-127d-41da-9bc7-8beff83545c6.png)

- 通过尝试绑定不同的租户，发现`tenantId`值都是1，确实这里实际上应该是`clusterId`

**Comment by QAQ-Jun** [comment]
这个地方我通过修改master代码改掉了，这个地方调错方法了qaq....

**Comment by LiYouliang** [comment]
> 现在看了下，是这个地方需要代码调整下，代码里还是拿了租户ID去判断，应该直接拿集群ID。
> 
> 就目前而言，是否可以先直接通过创建的时候进行绑定集群呢。创建的话，就是会在SparkThrift下创建一个以租户名称为名的db

通过创建方式初始化，也是报的同样的错误。

<img width="612" alt="image" src="https://user-images.githubusercontent.com/2577525/167099762-092ccdb5-1cd7-4010-b14b-bb8259f74e6a.png">

**Comment by LiYouliang** [comment]
`HadoopConf.getDefaultFs()`这里调用没有获取到信息，

https://github.com/DTStack/Taier/blob/029b9a325c56794b280ba344959fccb8b1171c94/taier-data-develop/src/main/java/com/dtstack/taier/develop/utils/develop/service/impl/Engine2DTOService.java#L111-L121

https://github.com/DTStack/Taier/blob/029b9a325c56794b280ba344959fccb8b1171c94/taier-data-develop/src/main/java/com/dtstack/taier/develop/utils/develop/common/HadoopConf.java#L67-L69

我猜会不会集群配置时`SparkThrift`没有配置`fs.defaultFS`的关系？

<img width="940" alt="image" src="https://user-images.githubusercontent.com/2577525/167101238-a2b02f42-cfe0-453a-876d-50eb80679a89.png">

因为在添加`SparkThrift`数据源时`defaultFS`是必填的

<img width="506" alt="image" src="https://user-images.githubusercontent.com/2577525/167101579-e7b2e024-82ee-48df-bc09-81c493888dac.png">

**Comment by LiYouliang** [comment]
> 这个地方我通过修改master代码改掉了，这个地方调错方法了qaq....

好的好的
