### ISSUE TITLE
执行任务时报错——引擎不支持或引擎为空

### ISSUE THREAD

**Issue by WujieRen** [DTStack/Taier#420]
引擎不支持（Spark SQL）
![image](https://user-images.githubusercontent.com/19680613/167751903-7bc43693-8b29-4d6e-bb2c-a73353249a6b.png)

引擎不能为空（Hive SQL）
![image](https://user-images.githubusercontent.com/19680613/167751790-c6f2ef5c-b208-4922-a195-dcfecedc6cb7.png)

**Comment by QAQ-Jun** [comment]
已在mater分支修复

**Comment by zuoinlv** [comment]
这个改了哪里，我从最新的master拉了最新的代码，还是报这个错误
