### ISSUE TITLE
flinksql -使用 自定义函数  - 启动任务异常（找不到资源）

### ISSUE THREAD

**Issue by seeTheWord** [DTStack/Taier#424]
1. 资源上传方式为 hdfs
2. 启动flink sql任务时，解析任务资源报错
定位问题类：com.dtstack.taier.develop.service.develop.impl.StreamSqlFormatService， 99行， hdfs 路径替换错误
![lQLPDhtqgrnwQwzNAV7NBIGwUlL_KT-wz5YCfy4lEACUAA_1153_350](https://user-images.githubusercontent.com/43259578/167985412-50c63a11-b692-4baf-b316-5cb7be6db4fe.png)
![lQLPDhtqgtof-RfMis0FF7BNjemfVnoBpgJ_LljLwDkA_1303_138](https://user-images.githubusercontent.com/43259578/167985425-d36d750c-8add-42be-8816-79d4eb632756.png)

**Comment by vainhope** [comment]
删除函数接口不正确
![image](https://user-images.githubusercontent.com/18212930/168001946-08bd13d4-8089-4da0-856e-99244c21c26b.png)
