### ISSUE TITLE
离线开发-运维中心-离线任务，调度周期显示错误，且调度周期筛选无效，在任务开发中是设置的按小时调度

### ISSUE THREAD

**Issue by yanji993** [DTStack/Taier#436]
**bug场景描述**
![3DE3FEBF-2F1B-4832-AF58-489DB7E6AA1C](https://user-images.githubusercontent.com/50412184/168546289-ef56c7f2-027d-4d11-b307-c691187f6215.png)
![C8829B95-04FC-4882-BC60-45E44B90CC58](https://user-images.githubusercontent.com/50412184/168546305-5199bfe8-3429-4d1e-9756-abd6d982c8dc.png)

**Comment by mortalYoung** [comment]
调度周期无法筛选的问题已在 #447 修复，调度周期显示错误的问题是服务端的传值问题，正在修复
