### ISSUE TITLE
离线开发-运维-依赖数图(没有显示任务调度依赖关系)

### ISSUE THREAD

**Issue by seeTheWord** [DTStack/Taier#441]
![1652756414(1)](https://user-images.githubusercontent.com/43259578/168719612-c2572d07-c9ff-4417-8b4a-86cdbb7dfd6d.jpg)
![1652756429(1)](https://user-images.githubusercontent.com/43259578/168719617-748e7752-0931-4f3c-87cd-303624274f0e.jpg)

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/168941252-e1f689c7-4fa9-4848-be5f-c5ea0aff7200.png)
点击展开上游 看下有吗

**Comment by seeTheWord** [comment]
更新了代码以后有了，感谢
