### ISSUE TITLE
获取开发目录失败

### ISSUE THREAD

**Issue by hxp0618** [DTStack/Taier#443]
**建议先去浏览下文档和部署常见问题**
[快速开始](https://dtstack.github.io/Taier/)
[部署常见问题](https://github.com/DTStack/Taier/issues/260)

![image](https://user-images.githubusercontent.com/30236140/168737050-704c700e-63c1-4870-8627-8efbafba92a7.png)

![image](https://user-images.githubusercontent.com/30236140/168736954-301157c7-896e-4854-ac14-f2869a504eda.png)
![image](https://user-images.githubusercontent.com/30236140/168737004-facf6265-a40a-4266-ae9f-00fd99918f28.png)

**bug场景描述**
获取开发目录失败，已经确认多次是否租户没有绑定队列的问题，但是好像并不是这个问题导致的，测试了yarn组件是正常的，后台没有异常日志，也没有调用接口的请求，所以我也不知道怎么排查了
**bug日志信息或数据信息**

**bug相关代码**

**提示的异常或者没有达到的效果**

**Comment by hxp0618** [comment]
我不能理解，我用master重新部署了一套，集群批准了，租户绑定了，但是出现了新问题，一直提示集群未绑定

**Comment by QAQ-Jun** [comment]
可以查看下console_cluster_tenant这个表的数据么，因为现在看是代码用租户ID去查询这个表数据时，没有查询到

**Comment by hxp0618** [comment]
> 可以查看下console_cluster_tenant这个表的数据么，因为现在看是代码用租户ID去查询这个表数据时，没有查询到
有数据，我按这个issue ：https://github.com/DTStack/Taier/issues/228 简单排查了一下，但是没有找到问题
![image](https://user-images.githubusercontent.com/30236140/168764688-c6792ea6-2063-4636-8900-1f1c4335d6be.png)

**Comment by QAQ-Jun** [comment]
你那边方便debug么，我现在看代码逻辑也是没问题，方便的话可以跟下
com.dtstack.taier.develop.service.develop.impl.BatchCatalogueService beforeGetCatalogue 这个方法，如果不方便，我再看看是不是哪里逻辑有问题

**Comment by hxp0618** [comment]
> beforeGetCatalogue
有值d的，
![image](https://user-images.githubusercontent.com/30236140/168768094-749c41e9-fcfb-404d-802a-325336c12f26.png)
![image](https://user-images.githubusercontent.com/30236140/168768206-34ab4d98-7721-4426-b047-834aee98a0d5.png)

**Comment by QAQ-Jun** [comment]
我现在看你最后一张图片的name属性是？？？，看看develop_catalogue是表中的数据乱码了么

**Comment by QAQ-Jun** [comment]
我刚本地复现了下，流程是没有问题的，所以肯定是哪里的数据存在了问题

**Comment by QAQ-Jun** [comment]
👌 解决问题了就行
