### ISSUE TITLE
前端编译失败

### ISSUE THREAD

**Issue by jehu654** [DTStack/Taier#448]
在taier1.1版本的前端模块进行编译，发现到92%时报内存不足
![image](https://user-images.githubusercontent.com/55435255/168769030-978c35c4-44bd-4fd3-a6e1-575c96e496b8.png)

把内存调成4G也不行，命令是yarn build --max_old_space_size=4096

**Comment by mortalYoung** [comment]
无法复现，可以提供更多一些的相关信息吗，比如说 node 版本，服务器的内存大小。或者试试把 `package.json` 里的 
```diff
- "build": "umi build",
+ "build": "NODE_OPTIONS=--max_old_space_size=4096 umi build",
```
然后执行 `yarn build`，参考 [通过-node_options-设置内存上限](https://umijs.org/zh-CN/guide/boost-compile-speed#%E9%80%9A%E8%BF%87-node_options-%E8%AE%BE%E7%BD%AE%E5%86%85%E5%AD%98%E4%B8%8A%E9%99%90)

**Comment by jehu654** [comment]
已解决
