### ISSUE TITLE
docker启动问题

### ISSUE THREAD

**Issue by vainhope** [DTStack/Taier#455]
docker 部署启动问题都可以在这里反馈

**Comment by rainsongsky** [comment]
如图所示
数据源添加失败，报错
![image](https://user-images.githubusercontent.com/1421582/176817616-a525f571-4b0a-4bd8-9173-a45df42eb9e8.png)

**Comment by rainsongsky** [comment]
测试新增 PostgreSQL 数据源，报错一样，其他工具连接 PostgreSQL 数据源正常

**Comment by WeiXue9** [comment]
> 测试新增 PostgreSQL 数据源，报错一样，其他工具连接 PostgreSQL 数据源正常

me too.

**Comment by WeiXue9** [comment]
> 测试新增 PostgreSQL 数据源，报错一样，其他工具连接 PostgreSQL 数据源正常

error is  This plugin type is not supported: mysql5.
