### ISSUE TITLE
数据同步时，数据源选择Oracle，数据同步目标选择SparkThrift和同步目标选定分区后，执行后报错

### ISSUE THREAD

**Issue by kissktyl** [DTStack/Taier#460]
数据同步时，数据源选择Oracle，数据同步目标选择SparkThrift。同步目标选定分区下拉列表时，接口数据显示为pt=给前端展示。
![image](https://user-images.githubusercontent.com/19199426/168968794-df50412e-ce1a-4d32-b35a-82bc0cccde37.png)

查询hive表分区时却是pt字段。
![image](https://user-images.githubusercontent.com/19199426/168968997-cd4879b3-cbf8-4606-ac04-e43af5440ab8.png)

任务执行后报错，显示partition spec is invalid; field pt does not exist or is empty。
![image](https://user-images.githubusercontent.com/19199426/168968923-cbd70be1-1e9d-4529-bb0e-9564eaee4c2d.png)

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/168971991-19b67408-9855-4eda-b04e-5a0c772a9fea.png)

分区字段 是同来做数据隔离

**Comment by kissktyl** [comment]
好的，谢谢。
