### ISSUE TITLE
任务同步，常量字符串 format字段应该赋值给chunjun中parseformat，导致输出时间错误

### ISSUE THREAD

**Issue by zekai-li** [DTStack/Taier#463]
![lQLPDhtvVmS6oArNAQDNAkuwYzb3gIKkgmwChxapesCuAA_587_256](https://user-images.githubusercontent.com/58294989/168981709-a7eb0616-ae72-4d09-850a-4a4b173d45f6.png)
![image](https://user-images.githubusercontent.com/58294989/168981762-62c6c6af-61fa-4bbf-a3aa-b726cee21d8f.png)
![lQLPDhtvVodMt1HNAQtTsPBUNmL2ACNpAocW4elAuwA_83_267](https://user-images.githubusercontent.com/58294989/168981784-7d3f9bb2-fbf0-4b24-89d3-5b6ddc370557.png)

**Comment by zekai-li** [comment]
![image](https://user-images.githubusercontent.com/58294989/168986683-c2891939-a7a8-4817-af5f-9a50eb8fcba6.png)
经验证此处两个字段都需要填充

**Comment by Saltingfish** [comment]
@zekai-li  可以贴一下 错误日志吗

**Comment by Saltingfish** [comment]
我从chunjun那边同学了解过来,这两个含义不一样,都要传的,后续还有什么问题再打开吧
