### ISSUE TITLE
前端已知问题

### ISSUE THREAD

**Issue by StrangeXin** [DTStack/Taier#466]
- 离线开发-数据同步-向导模式

1. 数据来源：选择数据源和表名，增量标识字段没有重置
2. 数据来源：POSTGRESQL表名不可多选
3. 选择目标：预览和重新编辑时分区信息没有显示
4. 字段映射：添加常量后，预览和编辑时没有显示添加的常量

- 编辑器问题

1. 编辑文件夹名称字符数量超出限制建议统一排查一下：任务编辑文件夹名长度超出限制还能点击确认；任务编辑文件夹名长度max限制64提示文字却显示20；目录树文件夹名超出一行不应该换行显示；编辑文件夹名后文件夹下的目录没有了，点击刷新按钮也没用，只能刷新页面；在目录树里新建和重命名文件夹没有做长度限制，与编辑表单对应不上；编辑文件夹名保存后，目录树里显示的还是修改前的名字。
2. 编辑文件夹名后，右侧面包屑导航没有刷新；右侧tab栏切换选中的编辑页面，左侧的目录树没有同步选中状态；表单里点击保存完成时，没有改变编辑器tab保存状态。

- src/constant/index.ts

1. SPARKTHRIFT连接信息没有展示
2. HBASE1.x和2.x类型不正确

修复方式：
DATA_SOURCE_TEXT：
[DATA_SOURCE_ENUM.SPARKTHRIFT]: 'SparkThrift',
[DATA_SOURCE_ENUM.HBASE]: 'HBase1.x',
[DATA_SOURCE_ENUM.HBASE2]: 'HBase2.x',

**Comment by mortalYoung** [comment]
Resolved in #487 #488  #473

**Comment by mortalYoung** [comment]
大部分问题应该已经修复了，有一些遗留问题暂时不影响用户操作，只影响用户体验，已经提到 molecule 那边排期解决，这个 bug 相关的 PR 先关闭了
