### ISSUE TITLE
打开旧版本的同步任务异常

### ISSUE THREAD

**Issue by jehu654** [DTStack/Taier#469]
更新版本，执行1.1的sql之后，打开旧版本的同步任务显示异常
![image](https://user-images.githubusercontent.com/55435255/169185985-6f389d87-344a-4bdb-b58c-5cc9dfa29cb2.png)

**Comment by vainhope** [comment]
1.0 升级到1.1 加了部分参数 和脚本模式 暂时不能兼容 可以新建任务
