### ISSUE TITLE
运维中心-【离线任务列表、周期实例列表、补数据实例详情中】中任务类型筛选项，比新建任务时多了虚节点、Spark、Shell、工作流等4个选项

### ISSUE THREAD

**Issue by kissktyl** [DTStack/Taier#476]
新建任务时，只支持如下5种类型：
![lQLPDhtwH3O5UmDNAanNBImwxh_F_EWZqcwCiGATIoDWAA_1161_425](https://user-images.githubusercontent.com/19199426/169232781-b09f8609-2484-4275-b1ee-e63b3ae5bf8e.png)

离线任务列表如下：
![image](https://user-images.githubusercontent.com/19199426/169234741-16978efa-af09-466d-8e38-29d25b2a0eba.png)

周期实例列表如下：
![image](https://user-images.githubusercontent.com/19199426/169234243-d29a4729-46d6-483a-a71b-9d2361ddde3f.png)

补数据实例详情如下：
![image](https://user-images.githubusercontent.com/19199426/169234572-14f37ef7-a9cc-47f4-aaf2-eca9ef93b275.png)

**Comment by basicdream** [comment]
您好， 可以问下，这个项目 多集群管理那块，调度资源，存储组件和计算组件是如何配置的吗，之前没接处过这块，看你截图的已经能跑任务了

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/169343992-30ca954d-97f0-41e7-97d5-e84fd3fcc7a6.png)

**Comment by kissktyl** [comment]
好的，谢谢

**Comment by StrangeXin** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/6157378/169442073-137ca3ac-e208-4530-8419-b8081db7fae2.png">
 
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/6157378/169442179-97105b4b-536b-4ecf-bd32-3f6b551ce618.png">

任务类型调了两个接口，是否能合并为一个接口？这里暂不支持的类型确实不应该显示

**Comment by mortalYoung** [comment]
> <img alt="image" width="907" src="https://user-images.githubusercontent.com/6157378/169442073-137ca3ac-e208-4530-8419-b8081db7fae2.png">
> 
> <img alt="image" width="1101" src="https://user-images.githubusercontent.com/6157378/169442179-97105b4b-536b-4ecf-bd32-3f6b551ce618.png">
> 
> 任务类型调了两个接口，是否能合并为一个接口？这里暂不支持的类型确实不应该显示

可以，这里可以一次请求存在 context 里
