### ISSUE TITLE
可以出一份关于集群配置的详细文档吗

### ISSUE THREAD

**Issue by basicdream** [DTStack/Taier#477]
本地系统已经能正常启动了，  想看下具体的任务配置，但是需要 绑定集群， 可能搞这个方向的人，懂怎么操作，没接处过这块，有点懵，资源调度组件，是先需要搭一套hadoop的集群吗， 然后按文档的上传配置文件，如果集群是在云上服务器，那么本地启动项目，该如何修改需要上传的配置文件，还有计算组件该如何配置 有时间，希望能出一版详细的文档，谢谢

**Comment by bnyte** [comment]
你好，现在在官方文档的集群配置你那里不清楚呢 可以说一下 你可以点击 [集群配置](https://dtstack.github.io/Taier/docs/functions/multi-cluster) 看看

**Comment by basicdream** [comment]
其实是我自己对集群不太熟悉，比如 资源调度  那块 需要配置， 是需要先部署一套hadoop的环境吗，然后从环境里拿到 所需的配置文件，然后再上传到 系统里

**Comment by basicdream** [comment]
> 你好，现在在官方文档的集群配置你那里不清楚呢 可以说一下 你可以点击 [集群配置](https://dtstack.github.io/Taier/docs/functions/multi-cluster) 看看

**Comment by bnyte** [comment]
> 其实是我自己对集群不太熟悉，比如 资源调度 那块 需要配置， 是需要先部署一套hadoop的环境吗，然后从环境里拿到 所需的配置文件，然后再上传到 系统里

是的 需要搭建其对应的环境 然后如`hdfs`需要上传起对应配置的`hdfs-site.xml`等配置文件，建议联系`ETL`配合一下哈
