### ISSUE TITLE
1.2 版本规划

### ISSUE THREAD

**Issue by vainhope** [DTStack/Taier#478]
**新增功能**
1.  工作流类型添加（拖拽式DAG图）
2. spark jar 任务类型添加
3. flink jar任务类型添加
4. 任务运行指定队列运行
5. Hive 支持UDF
6. 数据同步脏数据支持MySQL 存储
7. OceanBase 任务类型执行

**功能优化**
1. 组件参数添加说明

**代码优化**
data-develop代码逻辑梳理 提高可读性和扩展性

> 大家有更好的建议和想法也可以在issue 下留言

**Comment by WeiXue9** [comment]
任务类型可以支持http接口形式吗
