### ISSUE TITLE
编辑文件夹，修改1级目录后，2、3级目录不见了，

### ISSUE THREAD

**Issue by StrangeXin** [DTStack/Taier#480]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/6157378/169272249-0d47e402-4fb7-4f88-8a2d-8d45cf2bd3be.png">
编辑文件夹，修改1级目录后，2、3级目录不见了，点上面的刷新按钮没反应，需要手动刷新浏览器才能看见

**Comment by mortalYoung** [comment]
Duplicate of #466
