### ISSUE TITLE
前端:打开多个tab编辑，右上角关闭所有没有关掉控制台里对应tab的问题

### ISSUE THREAD

**Issue by StrangeXin** [DTStack/Taier#489]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/6157378/169474613-028e1447-3542-43a0-9ef3-5fb4b041503e.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/6157378/169475705-07c763c4-fcea-444b-8ab1-438f5b1ff7d6.png">

1. 打开多个tab编辑，右上角关闭所有，没有关掉控制台里对应tab的问题
2. 右上角的Show Opened Editors点击没反应
3. 点击语法检查，检查通过，但是控制台里仍然有对应的问题
4. 控制台里对应的问题不正确，代码实际能运行，但编辑器和控制台都报错

**Comment by mortalYoung** [comment]
1. [ ] 目前已经提 issue 在排期了 https://github.com/DTStack/molecule/issues/730
3. [ ] 目前语法检查是走服务端请求检查，控制台的问题是走前端的 [sql-parser](https://github.com/DTStack/dt-sql-parser) 校验，所以存在不一致的地方，后续会排期优化这个用户体验
4. [ ] 由于提到的上述 [sql-parser](https://github.com/DTStack/dt-sql-parser) 校验并不一定可靠，所以并没有用来阻塞代码运行的流程。后续会优化相关校验配置

有兴趣可以一起参与开发😊

**Comment by mortalYoung** [comment]
sql-parse 的问题会在后续的版本迭代中解决，目前暂时没有排期计划。第一个问题转到 #622 继续 track，这个 PR 先关掉了。
