### ISSUE TITLE
任务开发-新建数据同步任务后保存-关闭-编辑，之前保存的配置信息中：同步模式、描述内容丢失了

### ISSUE THREAD

**Issue by StrangeXin** [DTStack/Taier#503]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/6157378/169761987-f61702f5-8bdf-436a-8d13-45ee06637e8c.png">
任务开发-新建数据同步任务后保存-关闭-编辑，之前保存的配置信息中：同步模式、描述内容丢失了

**Comment by mortalYoung** [comment]
Fixed in #530
