### ISSUE TITLE
bug: dataSync target

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/Taier#513]
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/6157378/169979796-cb87f825-030c-4b2e-a5ae-5ad259b5a47a.png">
这里逻辑也有点问题，应该要判断是否有sourceId和table，存在一种情况：第二步没有选择分区，返回上一步，再进入第二步，没有触发请求分区的接口

<img width="635" alt="image" src="https://user-images.githubusercontent.com/6157378/169980773-c772335a-ce84-4311-b22b-b03be2f0f5e5.png">
仅供参考：
// 修复预览和重新编辑时分区信息不显示的问题
if(targetMap?.type && targetMap?.sourceId && targetMap?.table) {
	// 获取 Hive 分区字段
	if (ALLOW_REQUEST_HIVE.includes(targetMap.type)) {
		getHivePartitions(targetMap.sourceId, targetMap.table);
	}
}

_Originally posted by @StrangeXin in https://github.com/DTStack/Taier/issues/473#issuecomment-1135538994_

**Comment by StrangeXin** [comment]
刚刚发现，第一步数据来源也有类似同样的问题：存在一种情况：第一步没有选择分区，进入第二步，再返回第一步，没有触发请求分区接口 0.0
另外存在一个疑问：第一步选择的表存在分区，是非必填，第二步选择的表存在分区，是必填，这里逻辑是否有问题？
<img width="952" alt="image" src="https://user-images.githubusercontent.com/6157378/169983778-6208e7d9-bbef-4100-a243-d1a58a0c171d.png">
<img width="922" alt="image" src="https://user-images.githubusercontent.com/6157378/169983844-31837603-c69b-4ff5-8962-572e3efc7736.png">

**Comment by mortalYoung** [comment]
> 另外存在一个疑问：第一步选择的表存在分区，是非必填，第二步选择的表存在分区，是必填，这里逻辑是否有问题？

关于这个问题：读表可以读全表 或者只读对应某一个分区，但是写入分区表的时候 必须指定特定分区
