### ISSUE TITLE
SparkThrif连接Hive提示报错：Required field 'client_protocol' is unset

### ISSUE THREAD

**Issue by easonjim** [DTStack/Taier#514]
Dear，
       SparkThrif连接Hive提示报错：Required field 'client_protocol' is unset，cdh版本为5.16.1，hive版本为1.1.0，在集群配置中，SparkThrif选择了2.x版本，提示报错：Required field 'client_protocol' is unset，换回1.x版本可以正常连接，但是回到主界面，进行用户绑定的时候，仍然提示：Required field 'client_protocol' is unset。

**Comment by easonjim** [comment]
Dear，
这个问题解决了，我搞了一个天大的笑话，我在集群配置里面写了sparkthrif2.x的jdbcurl为cdh5.16.1里面的hive2地址，这个是错误的，应该写sparkthrif2.x部署之后，10000端口的才对，现在可以配置成功了。

**Comment by a2236802667** [comment]
@easonjim  请问下你们的hive sql能用吗？
