### ISSUE TITLE
运维中心-周期实例，运行中状态下点击批量杀任务，未杀成功，运行中的任务状态还是运行中，且数量显示也不对

### ISSUE THREAD

**Issue by kissktyl** [DTStack/Taier#515]
![image](https://user-images.githubusercontent.com/19199426/169987290-a99559ca-e043-4da1-90b7-503be367fade.png)

**Comment by vainhope** [comment]
杀任务是异步的 状态变更根据kill结果来 
可以根据jobId在日志里看下kill 是否成功

统计可以说明下复现的场景么 
本地没有复现出统计的问题

**Comment by kissktyl** [comment]
你可以根据我截图的情景试一下，杀任务是不成功的。且筛选状态是【运行中】的下面都展示有一个任务，但总任务和运行中的数量却为0

**Comment by kissktyl** [comment]
杀任务其实是可以的，杀不死和状态统计数量为0是脏状态数据导致，建议尽快修复issue519
