### ISSUE TITLE
stop接口不正确

### ISSUE THREAD

**Issue by vainhope** [DTStack/Taier#524]
![image](https://user-images.githubusercontent.com/18212930/170160985-d02b0d1f-fb05-451f-a6da-944a21ce8b30.png)

**Comment by dtdazhi** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/88131825/177154299-11f62fc9-d046-48c7-ac3d-89b50e716585.png">
按照条件杀任务的请求接口错误
应该是： /taier/action/stopJobByCondition
