### ISSUE TITLE
带有任务参数的任务在右键编辑时，重命名操作后报错，抛出异常

### ISSUE THREAD

**Issue by kissktyl** [DTStack/Taier#526]
![image](https://user-images.githubusercontent.com/19199426/170168527-31454e87-827c-48f1-96c1-9b0f480b05d9.png)
![image](https://user-images.githubusercontent.com/19199426/170169219-031898c6-0335-420e-abd3-b66e20cf9686.png)
![image](https://user-images.githubusercontent.com/19199426/170170031-9cee4af8-f682-44a1-93bd-dbe2ced7f758.png)

经调试，前端发送请求时，会传updateSource:false字段，后端却不会根据这个字段去判断：
<img width="686" alt="lQLPJxZXL6rztTDNA8LNBVywBqYM4929-eYCj-mEw4AZAA_1372_962" src="https://user-images.githubusercontent.com/19199426/170171727-8449f8fd-7fc0-4511-8e54-0ded9e7573c6.png">
![image](https://user-images.githubusercontent.com/19199426/170172376-8155ec96-649e-42d4-afd1-d78d1c9c8688.png)
进入batchTaskParamService.checkParams方法，导致后端会校验前端传参taskVariables，但重命名这种情况前端不会传这个字段，导致接口抛出异常报错，其实重命名不应该校验前端传参taskVariables：
![image](https://user-images.githubusercontent.com/19199426/170170670-822ca77f-bfe8-41f7-9f9b-c99de6ba9519.png)

**Comment by QAQ-Jun** [comment]
1.2 对于右键编辑任务接口做了新增，接口如下：editTask
不在addOrUpdateTask接口做判断，可以使用1.2版本进行修改
