### ISSUE TITLE
列表分页参数问题

### ISSUE THREAD

**Issue by StrangeXin** [DTStack/Taier#545]
前端：

1. 前端所有列表切换分页，点右上角刷新或其他触发submit方法丢失了分页参数current、pageSize
2. 控制台里部分列表分页pageSize参数是前端写死的，涉及接口：getClusterList、searchTenant、getViewDetail

后端：

1. 实时任务列表接口返回的是全部列表数据，没有根据pageSize返回分页数据，涉及接口：flink/getTaskList

**Comment by mortalYoung** [comment]
前端问题 fixed in #558
