### ISSUE TITLE
执行hivesql任务时 报错Hive table reads for this storage type are not supported

### ISSUE THREAD

**Issue by gaoasi** [DTStack/Taier#568]
版本：
taier : 1.1.0
hive: 3.1.0
spark: 2.4

问题：
绑定好集群租户后，在任务开发栏创建hivesql任务，并执行sql：
desc formatted yichang_poi.ods_amap_pois;
select * from yichang_poi.ods_amap_pois limit 10;
执行结果：
![image](https://user-images.githubusercontent.com/43560964/171145493-b6cc05fe-0e51-45ec-9def-215585f405ce.png)

desc formatted 信息：
![image](https://user-images.githubusercontent.com/43560964/171145761-e506afca-eb11-4451-99c2-f862a5777590.png)
![image](https://user-images.githubusercontent.com/43560964/171145822-a6568f9b-e7dd-4a25-b482-e8f6d19839f2.png)
![image](https://user-images.githubusercontent.com/43560964/171145877-458da769-b840-4f48-a1d0-537ed2c631a2.png)

后端报错信息：
![image](https://user-images.githubusercontent.com/43560964/171146033-7db1b3f0-4900-4c95-9520-53c6ab06372a.png)
![image](https://user-images.githubusercontent.com/43560964/171146076-b68f69c3-cd03-41af-8463-faf066bf969d.png)

**Comment by gaoasi** [comment]
hiveserver 配置如下：
![image](https://user-images.githubusercontent.com/43560964/171146331-01c6a951-500e-445f-a36c-e2e1bccae757.png)

**Comment by QAQ-Jun** [comment]
![image](https://user-images.githubusercontent.com/33590567/182601505-85d134a9-2b18-44f8-9275-1ea33dd6293f.png)
 通过desc formatted tableName 语句查询得到的inputformat 的类型，和我们现在判断是否是parquet存储格式存在不兼容问题，导致没有解析出该表的存储格式是parquet，所以报错。

可通过自行修改datasourcex(git地址：https://github.com/DTStack/DatasourceX)的源码，然后本地重新打包修改兼容你配置的hive集群parquet存储格式
