### ISSUE TITLE
已经完成租户配置和绑定集群，新建任务报错

### ISSUE THREAD

**Issue by Narcasserun** [DTStack/Taier#575]
**bug场景描述**

已经完成租户配置和绑定集群，新建任务报错，原因是前端私包里面@dtinsight/molecule，id和tree没拿到

**bug日志信息或数据信息**
![image](https://user-images.githubusercontent.com/39329477/172292077-3079611d-71e0-49c6-8cc2-1d8569a182cc.png)

版本v1.1.0/master 测试都有这个问题

**Comment by mortalYoung** [comment]
可能是数据库初始化的时候乱码，https://github.com/DTStack/Taier/issues/443 参考一下
