### ISSUE TITLE
添加HDP3.X版本的kerberos认证报错

### ISSUE THREAD

**Issue by hunter01bird** [DTStack/Taier#576]
文件都已经正常上传了
报错信息如下：
com.dtstack.taier.pluginapi.exception.PluginDefineException: java.lang.IllegalArgumentException: Can't get Kerberos realm com.dtstack.taier.pluginapi.exception.PluginDefineException: java.lang.IllegalArgumentException: Can't get Kerberos realm at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:214) at com.dtstack.taier.base.util.KerberosUtils.login(KerberosUtils.java:227) at com.dtstack.taier.yarn.DtYarnClient.testConnect(DtYarnClient.java:134) at com.dtstack.taier.common.client.ClientProxy.lambda$null$9(ClientProxy.java:273) at com.dtstack.taier.pluginapi.callback.ClassLoaderCallBackMethod.callbackAndReset(ClassLoaderCallBackMethod.java:31) at com.dtstack.taier.common.client.ClientProxy.lambda$testConnect$10(ClientProxy.java:273) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by vainhope** [comment]
使用的版本是🤔️
