### ISSUE TITLE
部署不起来

### ISSUE THREAD

**Issue by biandou1313** [DTStack/Taier#583]
**建议先去浏览下文档和部署常见问题**
[快速开始](https://dtstack.github.io/Taier/)
[部署常见问题](https://github.com/DTStack/Taier/issues/260)
https://dtstack.github.io/Taier/docs/guides/introduction#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
**bug场景描述**
  根据这个文档，本地编译完成，部署到服务器上，无法运行
**bug日志信息或数据信息**
![1655089340(1)](https://user-images.githubusercontent.com/34857750/173272018-1032b53d-4415-4f6f-b4fb-eefbc7a70c73.png)

建议：
大佬们 我想问一下 有没有详细部署文档，或者发布编译包，可以一键安装的

**Comment by biandou1313** [comment]
有没有详细部署文档，或者发布编译包

**Comment by vainhope** [comment]
文档 更新了一半 又遇到什么问题起不来么
