### ISSUE TITLE
这是一个关于按键绑定的问题

### ISSUE THREAD

**Issue by BojunZhong** [DTStack/Taier#585]
![1](https://user-images.githubusercontent.com/102637083/174560999-e13fc010-0328-406b-81fc-28d3b75ec4b0.png)
![2](https://user-images.githubusercontent.com/102637083/174561013-57a294d1-1c3f-4c91-bb72-3b591276b09b.png)

这个OPERATIONS的id为'task'的时候才会显示这个离线任务的窗口，那问题来了？为什么？为什么id为task，这个按键才会具有这个功能？我查看了这个文件，并没有导入其他关于这个项目的包？这个功能到底怎么被导入的？

**Comment by BojunZhong** [comment]
如果id为其他的，例如’12rqwfsad‘，那么这个按键就失去功能了，我想知道功能怎么被依据id名字被导入的，这个文件与其他文件没有关联性啊

**Comment by mortalYoung** [comment]
这里的逻辑是酱紫的。
1. 首先在 menu 中添加相关的菜单项，
https://github.com/DTStack/Taier/blob/fdf5d0412c40e80c193129fb65adc309bd1673b3/taier-ui/src/extensions/init.tsx#L297-L321
2. 在 menu 中的选择事件中修改当前路由
https://github.com/DTStack/Taier/blob/fdf5d0412c40e80c193129fb65adc309bd1673b3/taier-ui/src/extensions/menu/index.tsx#L25-L53
3. 最后监听路由变化，根据 drawer 展示不同的抽屉内容
https://github.com/DTStack/Taier/blob/fdf5d0412c40e80c193129fb65adc309bd1673b3/taier-ui/src/pages/index.tsx#L304-L315

**Comment by BojunZhong** [comment]
非常感谢！

**Comment by BojunZhong** [comment]
也就是说第三个文件不能被调用啊，功能还是无法实现

**Comment by mortalYoung** [comment]
> 也就是说第三个文件不能被调用啊，功能还是无法实现

他们之间没有直接的调用关系，是通过 history 作为之间沟通的桥梁。`handleMenuBarEvents` 该事件会修改 history 的 query 值，而在 `useLayoutEffect` 中会监听当前 history 的修改（包括 query 值的修改），然后根据当前路由展示不同的内容。

即 `handleMenuBarEvents -> history -> openDrawer`
