### ISSUE TITLE
[BUG][运行sparkSql]selectData接口没传递taskType

### ISSUE THREAD

**Issue by SuperLiChaoRen** [DTStack/Taier#586]
***bug场景描述**
![image](https://user-images.githubusercontent.com/100331512/174578555-13750428-f77e-4248-960e-ae54526cad85.png)
/batchSelectSql/selectData这个接口
**bug相关代码**
TenantComponent tenantEngine = developTenantComponentService.getByTenantAndEngineType(tenantId, result.getTaskType());
**提示的异常或者没有达到的效果**
result.getTaskType()获取到的taskType为null，导致查不到数据，原因是上层方法没传递taskType

**Comment by vainhope** [comment]
1.2 版本已修复
