### ISSUE TITLE
部署完毕任务类型只有sparkSQL，请问是哪里配置出了问题吗

### ISSUE THREAD

**Issue by lesliechueng** [DTStack/Taier#589]
**建议先去浏览下文档和部署常见问题**
[快速开始](https://dtstack.github.io/Taier/)
[部署常见问题](https://github.com/DTStack/Taier/issues/260)

**bug场景描述**
部署完毕任务类型只有sparkSQL，请问是哪里配置出了问题吗
![image](https://user-images.githubusercontent.com/13750154/175014431-ee6e3df7-924d-4887-98a5-bad47fed8b95.png)

**Comment by vainhope** [comment]
配置完成spark 组件 能建spark sql任务
数据同步需要 配置flink组件
