### ISSUE TITLE
如何实现nodejs发送邮件

### ISSUE THREAD

**Issue by BojunZhong** [DTStack/Taier#594]
import { Button } from 'antd';

const nodemailer = require('nodemailer');

const code = String(Math.floor(Math.random() * 1000000)).padEnd(6, '0') // 生成6位随机验证码

// 开启SMTP连接池
const transporter = nodemailer.createTransport({
	host: 'smtp.163.com',
	secureConnection: true,  // use SSL
	port: 465,
	secure: true,  // secure: true for port 465, secure:false for port 587
	auth: {
		user: 'zhongbojun624@163.com',
		pass: 'VGLHXKQCWCFLNFFH'  // qq授权码
	}
});

// 设置邮件内容（谁发送什么给谁）
const mailOptions = {
	from: '"Carbon System IDE"<zhongbojun624@163.com>',  // 发件人
	to: '823893097@qq.com',   // 收件人
	subject: 'Carbon System IDE 验证码',  // 主题
	text: '这是一封来自nodejs的测试邮件',  // 文本内容
	html: `
            <p>您好！</p>
            <p>欢迎注册Carbon System IDE</p>
            <p>您的验证码是：<strong style="color:orangered;">${code}</strong></p>
            <p>如果不是您本人操作，请无视此邮件</p>
        `
};

// 使用先前创建的传输器的sendMail方法传递消息对象
function sendmail(){
	transporter.sendMail(mailOptions);
}

export default () => {

	return (
		<div className="resource-wrapper">
			<Button
				className="dt-resource-tenant"
				type="primary"
				onMouseDown ={() => {
					sendmail();
				}}
			>
				绑定新租户
			</Button>
		</div>
	);
};

这个是我写的代码，就单个sendmail()方法我运行过受到过邮件，但是只要再按钮以下就不行了，为什么？

**Comment by BojunZhong** [comment]
也就是说我按下按钮收不到邮件，验证码。

**Comment by mortalYoung** [comment]
```diff
return (
	<div className="resource-wrapper">
		<Button
			className="dt-resource-tenant"
			type="primary"
-			onMouseDown ={() => {
+			onClick ={() => {
				sendmail();
			}}
		>
			绑定新租户
		</Button>
	</div>
);
```

**Comment by BojunZhong** [comment]
这个问题有点难，我上网查询了类似的资料，就是使用react 按钮绑定 邮件发送，基本上找不到，请问你有啥高见啊

**Comment by BojunZhong** [comment]
我尝试过很多次，基本上意思就是按钮按下后不报错也没反应

**Comment by BojunZhong** [comment]
但是我单独运行文件node sendmail.js基本上都运行得了

**Comment by mortalYoung** [comment]
> 这个问题有点难，我上网查询了类似的资料，就是使用react 按钮绑定 邮件发送，基本上找不到，请问你有啥高见啊

改成 onClick 也不行吗，或者你要不试试看 https://www.npmjs.com/package/nodemailer-react

**Comment by BojunZhong** [comment]
没那么简单，改过了，我就是用nodemail发邮件的，单独的功能还是可以实现，但是要使用antd的按钮就不行了，好像countdownbutton也不行，这个到底在网上怎么搜啊

**Comment by BojunZhong** [comment]
我想找个类似的

**Comment by mortalYoung** [comment]
我建议是放到服务端去做，把授权码这种 token 放在前端暴露的话 不太安全

**Comment by BojunZhong** [comment]
嗯嗯嗯，我知道了，但是按照理论上来说，放在前端也能实现功能，为什么实现不了呢

**Comment by mortalYoung** [comment]
> 嗯嗯嗯，我知道了，但是按照理论上来说，放在前端也能实现功能，为什么实现不了呢

我推测可能的原因是因为 nodemailer 这个包不支持前端调用，只支持 node.js 去调吧。前端如果要发邮件可能需要通过 mailto 实现

**Comment by BojunZhong** [comment]
谢谢啦，我也感觉像
