### ISSUE TITLE
这是一个关于按钮与事件绑定的问题

### ISSUE THREAD

**Issue by BojunZhong** [DTStack/Taier#605]
https://user-images.githubusercontent.com/102637083/176397512-692aeea9-1ac9-44a2-bc0a-8e78bd1d906f.mp4

我的登录界面 登录绑定了hello world这个选项
					<Button
						className="dt-button"
						loading={submitLoading}
						block
						type="primary"
						htmlType="submit"
						onClick={message.error("Hello World")}
					>
						登录
					</Button>

但是神奇的是，当进入登录界面的时候会就会显示红色提醒栏：Hello World，然后我点击退出登录界面，又会出现红色提醒栏：Hello World。这是嘛情况，我的按钮绑定不是这样的？

**Comment by mortalYoung** [comment]
```diff
<Button
  className="dt-button"
  loading={submitLoading}
  block
  type="primary"
  htmlType="submit"
- onClick={message.error("Hello World")}
+ onClick={() => message.error("Hello World")}
>
```
