### ISSUE TITLE
任务启动后无法停止

### ISSUE THREAD

**Issue by EngonVHKxZ** [DTStack/Taier#614]
![a6bf94714e8b8bed28d04dfb0ce87a6b8f4262c052842ea3dfdec9491ab68f15QzpcVXNlcnNcRW5nb25cQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDQwODMzMTc4X3YyXEltYWdlRmlsZXNcMTY1NjkwMTA4NzE4NF9FOTlFOUE5Ri1ERjZBLTQ0MjYtQTREOC0yQzRDMkUxODMwQTEucG5n](https://user-images.githubusercontent.com/74673814/177094707-d8eea76e-5e4e-4cb2-8810-276448c9a48d.png)
在执行oracle logminer数据同步到mysql时 monitor.log报错：No flink session found on yarn cluster.
麻烦帮我看下是不是哪里错误配置了
https://github.com/DTStack/Taier/issues/316
https://github.com/DTStack/Taier/issues/372
以上两个issues已经查看过了    不是上面这两个原因
[集群配置文件.zip](https://github.com/DTStack/Taier/files/9036890/default.zip)

**Comment by vainhope** [comment]
monitor日志能贴下么
