### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by wulalali** [DTStack/Taier#632]
安装操作文档部署后，运行cup run -c 
进入web界面，输入账号密码无法登录。（尝试按其他问题的登录方式进行登录，仍然不可行）
![微信截图_20220721125217](https://user-images.githubusercontent.com/41581569/180132431-d88a2550-60cc-446f-812e-2955e20ca574.png)

然后查看Taier/logs/rdos.err  显示Error: Could not find or load main class com.dtstack.taier.develop.TaierApplication

**Comment by vainhope** [comment]
看下Taier的后端服务是起了的么

**Comment by wulalali** [comment]
> 看下Taier的后端服务是起了的么

你好，请问后端服务怎么样才算启动成功呢，我将集群啥的都启动了

**Comment by vainhope** [comment]
如果是手动部署的话 
可以参考文档
https://dtstack.github.io/Taier/docs/quickstart/deploy/backend
