### ISSUE TITLE
提交同步任务运行等待（同步任务）

### ISSUE THREAD

**Issue by peaceliu123** [DTStack/Taier#662]
**bug场景描述**
[提交mysql库对库同步任务，没有错误日志，taier.log显示一直等待]([url](url))
**bug日志信息或数据信息**

**bug相关代码**
[taier.log](https://github.com/DTStack/Taier/files/9234575/taier.log)
![432222d71f508ea4b16b997e09944b2](https://user-images.githubusercontent.com/31022517/182167645-b75f66f2-06f9-4386-ac7e-8ab191b47051.png)
![eeb747f5432f5c9065bbccb32798ba5](https://user-images.githubusercontent.com/31022517/182167644-fa15d040-6b70-4ac5-b513-e7c9265340d8.png)

**提示的异常或者没有达到的效果**

**欢迎提交对应修复的pr**

**Comment by bnyte** [comment]
你是session模式嘛还是prejob

**Comment by bnyte** [comment]
session的话这是正在分配session 你确定一下你的yarn资源够不够

**Comment by vainhope** [comment]
可以通过界面快速查看未提交的原因

![image](https://user-images.githubusercontent.com/18212930/183901735-dd2215b7-302f-4129-a410-d86f6e1afbdf.png)
