### ISSUE TITLE
同步任务执行失败，异常The main method caused an error: Unrecognized option: -flinkxDistDir

### ISSUE THREAD

**Issue by peaceliu123** [DTStack/Taier#664]
**bug场景描述**
    测试执行Mysql同步任务，
    per_job模式下运行，
    Flink显示成功执行，但是控制台打印异常信息，同时下沉表未同步数据
**bug日志信息或数据信息**
1、[控制台log.txt](https://github.com/DTStack/Taier/files/9240321/log.txt)
2、[taier.log](https://github.com/DTStack/Taier/files/9240329/taier.log)
**bug相关代码**
![image](https://user-images.githubusercontent.com/31022517/182327997-1c99f831-3297-4a67-a11b-1e04798808a5.png)
![image](https://user-images.githubusercontent.com/31022517/182328068-496e7b48-e029-4219-97ea-8c37b2fc1678.png)
**提示的异常或者没有达到的效果**
打印日志，一直在循环调用执行
![image](https://user-images.githubusercontent.com/31022517/182328465-b77cdb9c-7a80-488c-9722-efd04904b009.png)

**欢迎提交对应修复的pr**

**Comment by peaceliu123** [comment]
chunjun版本：chunjun-1.12.4.tar.gz

**Comment by bnyte** [comment]
chunjun那边改参数了，你把`flinkx`改成`chunjun`就可以了

**Comment by peaceliu123** [comment]
![image](https://user-images.githubusercontent.com/31022517/182348364-4003f760-8f86-4621-b06e-4fface2bb561.png)
 promethues配置为空， promethues必须要安装吗？

**Comment by bnyte** [comment]
不需要 普鲁米修斯是为了获取到你任务运行中的一些日志信息 类似于 上行 下行 速率 你可以不配 不影响

**Comment by peaceliu123** [comment]
谢谢，问题解决了

**Comment by bnyte** [comment]
没关系 有问题 继续提issue哈，如果你有好的解决方案可以直接pr哦，没问题的话你可以关掉这个issue啦~

**Comment by peaceliu123** [comment]
good！

**Comment by bobqiu** [comment]
我也遇到了这个问题[The main method caused an error: Unrecognized option: -flinkxDistDir] ，我把taier源码中所有的flinkxDistDir改成了chunjunDistDir重新打包后，重启还是一直提示这个问题。

**Comment by vainhope** [comment]
@bobqiu  taier-pluigns 下 flink对应的插件包 有打包么

**Comment by vainhope** [comment]
com.dtstack.taier.flink.config.PluginConfig#buildProgramArgs
确认下打包的时候 代码是正确的么
![image](https://user-images.githubusercontent.com/18212930/183414036-1f7dbca6-f56b-46aa-b21d-07203c260620.png)

**Comment by bobqiu** [comment]
解决了，需要把plugin里对应的包进行替换。
