### ISSUE TITLE
[BUG] [yarn-core] resource manage -> binding tenant -> got an empty queue

### ISSUE THREAD

**Issue by DingPengfei** [DTStack/Taier#670]
**bug场景描述**
Binding tenant in Resource Management gets an empty queue list
![image](https://user-images.githubusercontent.com/9244946/182530328-610a4f2a-f4fd-48c6-a6ce-6424746facd5.png)

**bug日志信息或数据信息**
This is the response of /taier/console/clusterResources URL
![image](https://user-images.githubusercontent.com/9244946/182530633-e3c5646a-5352-4e9a-90f8-9eb2e4d8c7ba.png)
As you can see, the queue isn't empty, but the key "queue" is null

**bug相关代码**

```
private List<JSONObject> getQueueResource(YarnClient yarnClient) throws Exception {
        String webAddress = getYarnWebAddress(yarnClient);
        String schedulerUrl = String.format(YARN_SCHEDULER_FORMAT, webAddress);
        String schedulerInfoMsg = getDataFromYarnRest(yarnClient.getConfig(), schedulerUrl);
        JSONObject schedulerInfo = JSONObject.parseObject(schedulerInfoMsg);
        JSONObject schedulerJson = schedulerInfo.getJSONObject("scheduler");

        if (!schedulerJson.containsKey("schedulerInfo")) {
            LOG.error("get yarn queueInfo error! Miss schedulerInfo field");
            return null;
        }
        JSONObject schedulerInfoJson = schedulerJson.getJSONObject("schedulerInfo");
        if (!schedulerInfoJson.containsKey("queues")) {
            LOG.error("get yarn queueInfo error! Miss queues field");
            return null;
        }
        JSONObject queuesJson = schedulerInfoJson.getJSONObject("queues");
        List<JSONObject> modifyQueueInfos = modifyQueueInfo(null, queuesJson);
        return modifyQueueInfos;
    }
```

[Cluster Scheduler API](https://hadoop.apache.org/docs/r2.10.2/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html#Cluster_Scheduler_API)
the api response has different formats depend on the type of scheduler, but code here only parses the "capacity" type

**提示的异常或者没有达到的效果**
Should list right queues

**欢迎提交对应修复的pr**

**Comment by gzusgw** [comment]
这个问题应该是由于添加开启kerberos认证的集群组件时表console_component字段kerberos_file_name数据为空导致，属于前端的bug,字段中手动补上这个值试试
https://github.com/DTStack/Taier/issues/661

**Comment by DingPengfei** [comment]
> 这个问题应该是由于添加开启kerberos认证的集群组件时表console_component字段kerberos_file_name数据为空导致，属于前端的bug,字段中手动补上这个值试试 #661

应该不是这个问题，我集群未开kerberos。而且yarn有返回scheduler的信息，只是后端解析的代码逻辑只对capacity的情况作了处理

**Comment by vainhope** [comment]
fairschedule的模式 需要处理一下

**Comment by vainhope** [comment]
private String getRootQueueName(ISourceDTO sourceDTO, YarnClient yarnClient) {
        String webAddress = YarnConfUtil.getRMWebAddress(yarnClient);
        String schedulerUrl = String.format(YARN_SCHEDULER_FORMAT, webAddress);
        String schedulerInfoMsg = YarnRestUtil.getDataFromYarnRest(sourceDTO, yarnClient.getConfig(), schedulerUrl);
        JSONObject schedulerInfo = JSONObject.parseObject(schedulerInfoMsg);

        String rootQueueName = "root";
        JSONObject schedulerJson = schedulerInfo.getJSONObject("scheduler");
        if (schedulerJson.containsKey("schedulerInfo")) {
            JSONObject schedulerInfoJson = schedulerJson.getJSONObject("schedulerInfo");
            String schedulerType = schedulerInfoJson.getString("type");
            if (StringUtils.equalsIgnoreCase(schedulerType, CAPACITYSCHEDULER_TPYE)) {
                rootQueueName = schedulerInfoJson.getString("queueName");
            }
            if (StringUtils.equalsIgnoreCase(schedulerType, FAIRSCHEDULER_TPYE)) {
                JSONObject rootQueueJson = schedulerInfoJson.getJSONObject("rootQueue");
                rootQueueName = rootQueueJson == null ? rootQueueName : rootQueueJson.getString("queueName");
            }
        }
        return rootQueueName;
    }


@DingPengfei  FAIRSCHEDULER_TPYE 获取方式不一样 需要先拿rootQueue

**Comment by milfoil-w** [comment]
@vainhope 这个代码要加在哪里呢

**Comment by vainhope** [comment]
com.dtstack.taier.hadoop.HadoopClient#getQueueResource
这里

**Comment by milfoil-w** [comment]
![1659600097629](https://user-images.githubusercontent.com/10329981/182795802-8e9304a6-4f3c-4903-b743-b7f9a1466bdd.png)

**Comment by milfoil-w** [comment]
@vainhope 这感觉不对，DtYarnClient 这个类也有这个方法一模一样那边应该也要改下

**Comment by vainhope** [comment]
@milfoil-w 备注错类了 是DtYarnClient

**Comment by DingPengfei** [comment]
> ```
> private String getRootQueueName(ISourceDTO sourceDTO, YarnClient yarnClient) {
>     String webAddress = YarnConfUtil.getRMWebAddress(yarnClient);
>     String schedulerUrl = String.format(YARN_SCHEDULER_FORMAT, webAddress);
>     String schedulerInfoMsg = YarnRestUtil.getDataFromYarnRest(sourceDTO, yarnClient.getConfig(), schedulerUrl);
>     JSONObject schedulerInfo = JSONObject.parseObject(schedulerInfoMsg);
> 
>     String rootQueueName = "root";
>     JSONObject schedulerJson = schedulerInfo.getJSONObject("scheduler");
>     if (schedulerJson.containsKey("schedulerInfo")) {
>         JSONObject schedulerInfoJson = schedulerJson.getJSONObject("schedulerInfo");
>         String schedulerType = schedulerInfoJson.getString("type");
>         if (StringUtils.equalsIgnoreCase(schedulerType, CAPACITYSCHEDULER_TPYE)) {
>             rootQueueName = schedulerInfoJson.getString("queueName");
>         }
>         if (StringUtils.equalsIgnoreCase(schedulerType, FAIRSCHEDULER_TPYE)) {
>             JSONObject rootQueueJson = schedulerInfoJson.getJSONObject("rootQueue");
>             rootQueueName = rootQueueJson == null ? rootQueueName : rootQueueJson.getString("queueName");
>         }
>     }
>     return rootQueueName;
> }
> ```
> 
> @DingPengfei FAIRSCHEDULER_TPYE 获取方式不一样 需要先拿rootQueue

本地改完了，等会儿空了提个PR
