### ISSUE TITLE
1.3版本规划

### ISSUE THREAD

**Issue by vainhope** [DTStack/Taier#673]
#### 新增功能
支持 flink on standalone组件
支持PySpark、SparkJar任务

数据同步的向导模式数据源支持
  hive
  spark-thrift
  oracle
  mysql
  postgresql
  sqlserver
  es7

#### 功能优化
windows开发环境适配 
taier-plugins 和 datasoucex 部分重复插件融合

**Comment by itWMdeveloping** [comment]
现在已经有ocSQL，sparkSQL类型， 后续会不会还有mysqlSQL,  greenplumSQL，这一块考虑不考虑统一一下，任务考虑支持shell任务类型吗

**Comment by gzusgw** [comment]
任务考虑支持http任务类型吗

**Comment by vainhope** [comment]
sql和http任务的开发 在taier上可以通过扩展开发的方式来实现 实现上来说比较简单
开发新任务类型的文档在这里 https://dtstack.github.io/Taier/docs/expand/task
希望可以一起补充Taier支持的任务类型 @gzusgw @itWMdeveloping 
shell 任务会优先考虑 shell on yarn的方式去实现

**Comment by gaoasi** [comment]
考虑一下增加展示任务的血缘关系的功能吗

**Comment by itWMdeveloping** [comment]
这周1.3能发版吗？shell 任务能脱离hadoop吗

**Comment by windwhisper-i** [comment]
1.3 什么时候发版
