### ISSUE TITLE
taier1.2版本，配置集群HDFS是校验失败，代码存在bug

### ISSUE THREAD

**Issue by peaceliu123** [DTStack/Taier#693]
严重BUG!!!
**bug场景描述**
适配1.2版本，配置DHFS集群，前端页面显示有误，后台校验有误
**bug日志信息或数据信息**

**bug相关代码**
![image](https://user-images.githubusercontent.com/31022517/183697394-87f76a51-7ae0-4801-bf45-99bcce256e23.png)
![1660059755574](https://user-images.githubusercontent.com/31022517/183697468-47b6a7ac-7004-454a-ad4c-ecf5e5f19cd1.png)

**提示的异常或者没有达到的效果**
本地已修复bug
**欢迎提交对应修复的pr**

**Comment by vainhope** [comment]
能看下具体的fs的报错的堆栈么

**Comment by wangzhen-wudangshan** [comment]
> 
你好！我的 1.2.3版本配置hdfs 也遇到了，你是怎么解决的?

**Comment by Dkbei** [comment]
hi，我也遇到了相同的问题，请问如何解决的呢？ @peaceliu123

**Comment by vainhope** [comment]
最新的master 已修复
