### ISSUE TITLE
实时采集-脚本模式-提交之后任务状态未变化

### ISSUE THREAD

**Issue by StrangeXin** [DTStack/Taier#695]
![image-2022-08-11-11-49-17-852](https://user-images.githubusercontent.com/6157378/184070824-76e4e688-0c0e-4f74-b7e7-fb49432c3c4b.png)
![image-2022-08-11-12-50-43-370](https://user-images.githubusercontent.com/6157378/184070837-131e7e24-63c9-443a-8584-bb038bf7acd2.png)

**Comment by bnyte** [comment]
可以f12看一下后端请求吗 其次就是方便的话看一下数据库数据呢
