### ISSUE TITLE
[BUG][选中HiveSql执行] 执行select sql没有返回结果集

### ISSUE THREAD

**Issue by flyysoul** [DTStack/Taier#700]
**bug场景描述**
任务类型是HiveSql，在编辑区选定select语句查询，后端返回结果中result字段为null，前端只显示了成功日志，没有显示结果集标签页。

**bug日志信息或数据信息**
查询sql：
```sql
select way, rom  
from default.test;
```
输出日志：
``` log
[15:44:41] <info> 第1条任务开始执行
===========任务信息===========
select way, rom  
from default.test;
============================
[15:44:41] <info> 成功

```
**bug相关代码**
https://github.com/DTStack/Taier/blob/09910ce6fab46eecc462e5d0c6bae9c877506e5e/taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/runner/JdbcTaskRunner.java#L75
选中的select sql如果是在同一行上是没有问题的，因为进入了if里执行；
如果是多行的sql（如上述sql），正则通不过就会进入下面的else代码块，查询结果给丢了。

**提示的异常或者没有达到的效果**
显示结果集标签页。
**欢迎提交对应修复的pr**
这里正则不太会搞，还是交给你们吧(☆▽☆)

**Comment by bnyte** [comment]
看了一下 这里用startsWith貌似更好
