### ISSUE TITLE
绑定队列为空怎么解决

### ISSUE THREAD

**Issue by a2236802667** [DTStack/Taier#733]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

![image](https://user-images.githubusercontent.com/50047029/188616377-da90a045-9b64-46cf-ae2e-43e59bae0e15.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
https://github.com/DTStack/Taier/issues/717
参考下这个看下呢

**Comment by a2236802667** [comment]
![image](https://user-images.githubusercontent.com/50047029/188643322-860a9920-cd93-42e0-8233-905a80c3bc96.png)
谢谢，但区别是我这里没有数据，这个咋整？

**Comment by vainhope** [comment]
看下集群的webresource 界面 节点是正常的么
如果正常的话 看下控制台getResource的返回信息

**Comment by a2236802667** [comment]
额，没看到有这个界面

**Comment by a2236802667** [comment]
![image](https://user-images.githubusercontent.com/50047029/188775957-de30931f-9a3d-4346-ae8c-71c4d066ca03.png)

**Comment by a2236802667** [comment]
![image](https://user-images.githubusercontent.com/50047029/188776045-fef90c9c-9ad9-4574-9a1d-9ba47f6b02bb.png)

**Comment by a2236802667** [comment]
请问下部署taier要放行哪些端口？

**Comment by vainhope** [comment]
涉及的随机端口 建议和集群端口放放开
![image](https://user-images.githubusercontent.com/18212930/188800330-47601098-c505-406e-99af-68f171bf053a.png)
看下这个地方的返回信息呢

**Comment by a2236802667** [comment]
![image](https://user-images.githubusercontent.com/50047029/188801315-9f5ef503-a9ab-4be3-9bf7-f4403d8a9233.png)

**Comment by vainhope** [comment]
com.dtstack.taier.yarn.DtYarnClient#getQueueResource
看下这个地方的逻辑
是不是webresource 不通

**Comment by a2236802667** [comment]
![image](https://user-images.githubusercontent.com/50047029/188838420-ee159d7b-9102-4951-a9c4-a98926c88029.png)
这个端口没起来，是啥原因？

**Comment by vainhope** [comment]
看下 你yarn组件配置文件里面的
![image](https://user-images.githubusercontent.com/18212930/188850346-323d9c25-62d9-4746-8f0b-1c9222d2072b.png)
和docker的网络是通的么

**Comment by a2236802667** [comment]
{"scheduler":{"schedulerInfo":{"type":"fairScheduler","rootQueue":{"maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":12288,"vCores":8},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":0,"vCores":0},"demandResources":{"memory":0,"vCores":0},"steadyFairResources":{"memory":12288,"vCores":8},"fairResources":{"memory":12288,"vCores":8},"clusterResources":{"memory":12288,"vCores":8},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":0,"allocatedContainers":0,"reservedContainers":0,"queueName":"root","schedulingPolicy":"DRF","childQueues":{"queue":[{"type":"fairSchedulerLeafQueueInfo","maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":12288,"vCores":8},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":0,"vCores":0},"demandResources":{"memory":0,"vCores":0},"steadyFairResources":{"memory":6144,"vCores":4},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":12288,"vCores":8},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":0,"allocatedContainers":0,"reservedContainers":0,"queueName":"root.default","schedulingPolicy":"DRF","preemptable":true,"numPendingApps":0,"numActiveApps":0},{"maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":12288,"vCores":8},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":0,"vCores":0},"demandResources":{"memory":0,"vCores":0},"steadyFairResources":{"memory":6144,"vCores":4},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":12288,"vCores":8},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":0,"allocatedContainers":0,"reservedContainers":0,"queueName":"root.users","schedulingPolicy":"DRF","childQueues":{"queue":[{"type":"fairSchedulerLeafQueueInfo","maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":12288,"vCores":8},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":6144,"vCores":4},"demandResources":{"memory":0,"vCores":0},"steadyFairResources":{"memory":6144,"vCores":4},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":12288,"vCores":8},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":0,"allocatedContainers":0,"reservedContainers":0,"queueName":"root.users.hadoop","schedulingPolicy":"fair","preemptable":true,"numPendingApps":0,"numActiveApps":0}]},"preemptable":true}]},"preemptable":true}}}

**Comment by a2236802667** [comment]
docker方式部署的话，咋编译yarn插件呢？

**Comment by a2236802667** [comment]
可以了，感谢

**Comment by a2236802667** [comment]
重新编译yarn插件后，再次手动上传yarn配置文件后不能保存
![image](https://user-images.githubusercontent.com/50047029/189877473-c6a7f43f-3ec4-4489-a60e-6add193e0ce7.png)

**Comment by vainhope** [comment]
看下日志报错信息呢

**Comment by a2236802667** [comment]
我看taier.log无报错信息...

**Comment by vainhope** [comment]
可以看下request.log 还有浏览器的控制台

**Comment by a2236802667** [comment]
{"scheduler":{"schedulerInfo":{"type":"fairScheduler","rootQueue":{"maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":0,"vCores":0},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":0,"vCores":0},"demandResources":{"memory":2048,"vCores":2},"steadyFairResources":{"memory":0,"vCores":0},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":0,"vCores":0},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":2,"allocatedContainers":0,"reservedContainers":0,"queueName":"root","schedulingPolicy":"DRF","childQueues":{"queue":[{"type":"fairSchedulerLeafQueueInfo","maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":0,"vCores":0},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":0,"vCores":0},"demandResources":{"memory":0,"vCores":0},"steadyFairResources":{"memory":0,"vCores":0},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":0,"vCores":0},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":0,"allocatedContainers":0,"reservedContainers":0,"queueName":"root.default","schedulingPolicy":"DRF","preemptable":true,"numPendingApps":0,"numActiveApps":0},{"maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":0,"vCores":0},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":0,"vCores":0},"demandResources":{"memory":2048,"vCores":2},"steadyFairResources":{"memory":0,"vCores":0},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":0,"vCores":0},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":2,"allocatedContainers":0,"reservedContainers":0,"queueName":"root.users","schedulingPolicy":"DRF","childQueues":{"queue":[{"type":"fairSchedulerLeafQueueInfo","maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":0,"vCores":0},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":6144,"vCores":4},"demandResources":{"memory":2048,"vCores":2},"steadyFairResources":{"memory":0,"vCores":0},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":0,"vCores":0},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":2,"allocatedContainers":0,"reservedContainers":0,"queueName":"root.users.hadoop","schedulingPolicy":"fair","preemptable":true,"numPendingApps":2,"numActiveApps":0}]},"preemptable":true}]},"preemptable":true}}}}

**Comment by a2236802667** [comment]
还是获取不到队列，帮忙看下

**Comment by vainhope** [comment]
我用单测跑 这个json 是可以获取到的
com.dtstack.taier.yarn.TestDtYarnClient
![image](https://user-images.githubusercontent.com/18212930/190386435-71b9f281-f008-4f1e-91a3-b8467c1d4180.png)



建议你在环境上debug断一下这个地方 

com.dtstack.taier.yarn.DtYarnClient#getQueueResource
@a2236802667

**Comment by vainhope** [comment]
我用单测跑 这个json 是可以获取到的
com.dtstack.taier.yarn.TestDtYarnClient
![image](https://user-images.githubusercontent.com/18212930/190386435-71b9f281-f008-4f1e-91a3-b8467c1d4180.png)



建议你在环境上debug断一下这个地方 

com.dtstack.taier.yarn.DtYarnClient#getQueueResource
@a2236802667

**Comment by a2236802667** [comment]
![image](https://user-images.githubusercontent.com/50047029/191918336-85ffdca3-676f-44bf-98d5-fb38a26265f9.png)
报这个错

**Comment by a2236802667** [comment]
{"scheduler":{"schedulerInfo":{"type":"fairScheduler","rootQueue":{"maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":0,"vCores":0},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":0,"vCores":0},"demandResources":{"memory":10240,"vCores":10},"steadyFairResources":{"memory":0,"vCores":0},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":0,"vCores":0},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":10,"allocatedContainers":0,"reservedContainers":0,"queueName":"root","schedulingPolicy":"DRF","childQueues":{"queue":[{"type":"fairSchedulerLeafQueueInfo","maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":0,"vCores":0},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":0,"vCores":0},"demandResources":{"memory":0,"vCores":0},"steadyFairResources":{"memory":0,"vCores":0},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":0,"vCores":0},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":0,"allocatedContainers":0,"reservedContainers":0,"queueName":"root.default","schedulingPolicy":"DRF","preemptable":true,"numPendingApps":0,"numActiveApps":0},{"maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":0,"vCores":0},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":0,"vCores":0},"demandResources":{"memory":10240,"vCores":10},"steadyFairResources":{"memory":0,"vCores":0},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":0,"vCores":0},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":10,"allocatedContainers":0,"reservedContainers":0,"queueName":"root.users","schedulingPolicy":"DRF","childQueues":{"queue":[{"type":"fairSchedulerLeafQueueInfo","maxApps":2147483647,"minResources":{"memory":0,"vCores":0},"maxResources":{"memory":0,"vCores":0},"usedResources":{"memory":0,"vCores":0},"amUsedResources":{"memory":0,"vCores":0},"amMaxResources":{"memory":6144,"vCores":4},"demandResources":{"memory":10240,"vCores":10},"steadyFairResources":{"memory":0,"vCores":0},"fairResources":{"memory":0,"vCores":0},"clusterResources":{"memory":0,"vCores":0},"reservedResources":{"memory":0,"vCores":0},"pendingContainers":10,"allocatedContainers":0,"reservedContainers":0,"queueName":"root.users.hadoop","schedulingPolicy":"fair","preemptable":true,"numPendingApps":10,"numActiveApps":0}]},"preemptable":true}]},"preemptable":true}}}

**Comment by vainhope** [comment]
@a2236802667 
看下你的集群是否正常

json里面解析的core和memory 都为0 

确认下namenode是否启动注册成功 

![image](https://user-images.githubusercontent.com/18212930/192189932-d52f4ec0-0db6-4ad7-9638-201b73b7bc7d.png)

**Comment by a2236802667** [comment]
嗯嗯，是集群问题，感谢~
