### ISSUE TITLE
[Bug] [多集群管理] 唯独hdfs无法验证通过，其他都可以。

### ISSUE THREAD

**Issue by wangzhen-wudangshan** [DTStack/Taier#742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

在配置HDFS 存储组件过程中，上传Kerberos 的zip时出现Kerberos无法登录的情况。但是我自己单独搭建flink 1.13.5时，Kerberos是可以连通的。提示：Kerberos 的zip包里有：krb5.conf 和 nn.service.keytab 两个文件。方便的话，你们可以提供相关实例，我参考下。
截图如下：
![bb5e18f09462400ed0800ccded2241a](https://user-images.githubusercontent.com/96755853/189076650-859be67a-2a86-4236-9f2d-89296255f724.png)
错误是：
![59f34f1a528a695f7499fc3c4e20504](https://user-images.githubusercontent.com/96755853/189076787-993edd51-8a85-4c1e-9101-cdbacfb0c70d.png)

### What you expected to happen

我觉得是 taier 对 Kerberos 文件处理有问题 ，或者是我传的的kerberos有文件不对。

### How to reproduce

你们可以在多集群管理里面配置下HDFS, 看看是否可以重新。如果通过，可以提供建议给我们。

### Version

v.12

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/189087510-69b31ee3-a843-41f8-aebf-96888621d3c7.png)
 hdfs的配置xml文件能贴一下么

**Comment by wangzhen-wudangshan** [comment]
> ![image](https://user-images.githubusercontent.com/18212930/189087510-69b31ee3-a843-41f8-aebf-96888621d3c7.png) hdfs的配置xml文件能贴一下么

(1)kerberos zip文件：
[taier-kerberos.zip](https://github.com/DTStack/Taier/files/9531521/taier-kerberos.zip)
(2)hdfs的xml文件：
[taier-hdfs.zip](https://github.com/DTStack/Taier/files/9531528/taier-hdfs.zip)

相关文件已经发你了，请核对。

**Comment by vainhope** [comment]
com.dtstack.taier.hdfs.DtHdfsClient#checkHdfsConnect
等跟下这个地方181行 具体什么npe了
我看你的文件配置项是有的 应该不是配置项问题
![image](https://user-images.githubusercontent.com/18212930/189266159-c6ca8301-9f49-41c3-8c5f-f7537dd65de6.png)

**Comment by wangzhen-wudangshan** [comment]
那是不是Kerberos的问题？Kerberos文件也发你了，麻烦核实下和你们测试时啥区别。
![59f34f1a528a695f7499fc3c4e20504](https://user-images.githubusercontent.com/96755853/189294975-4dd0df5b-93e1-407e-9384-95f8d6a1730c.png)

**Comment by vainhope** [comment]
你的集群我访问不了 
本地测试没有出现你截图的这个问题
![image](https://user-images.githubusercontent.com/18212930/189300015-390f552b-5943-4fa0-b0bb-7471535ef29a.png)

**Comment by wangzhen-wudangshan** [comment]
什么情况下会有mergekerb5.conf 文件呢? 估计是Kerberos认证失败导致的。另外我的HDFS的 nn.service.keytab文件名称和格式对吗？对taier来说。

**Comment by vainhope** [comment]
点击过kerbero的编辑按钮就会有，可以删除掉keytab 在上传直接报错再试试

如果还是有点话 建议debug看下 具体的报错问题
![image](https://user-images.githubusercontent.com/18212930/189486704-22400195-145a-4f16-9757-03d200dd1c72.png)

**Comment by wangzhen-wudangshan** [comment]
请查看文
[scheduler.zip](https://github.com/DTStack/Taier/files/9572544/scheduler.zip)

**Comment by vainhope** [comment]
curl --location --request GET 'http://172.16.85.215:18088/ws/v1/cluster/scheduler' \
--header 'Accept: application/json' \
--header 'Accept-Language: zh-CN,zh;q=0.9' \
--header 'Cache-Control: max-age=0' \
--header 'Connection: keep-alive' \
--header 'Cookie: __utmc=182792038; __utmz=182792038.1654825563.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utma=182792038.1832709514.1654825563.1654825563.1654833206.2; hadoop.auth=; CLOUDERA_MANAGER_SESSIONID=node0rjwbnr4l15pfs530mnpbao4519706.node0' \
--header 'Upgrade-Insecure-Requests: 1' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36' \
--header 'Content-Type: application/json'



@wangzhen-wudangshan 能麻烦改下ip 吧对应的json发我么

**Comment by wangzhen-wudangshan** [comment]
请查收josn文件
[myjson.zip](https://github.com/DTStack/Taier/files/9580067/myjson.zip)

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/190542103-6c3b1717-e71a-4810-bd11-188321cc09e1.png)
队列是正常解析的 

建议debug下 com.dtstack.taier.yarn.DtYarnClient#getClusterResource

或者看下日志里面有没有对应 错误日志信息

@wangzhen-wudangshan
