### ISSUE TITLE
HiveSQL类型任务租户绑定不了schema 

### ISSUE THREAD

**Issue by a2236802667** [DTStack/Taier#747]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

![image](https://user-images.githubusercontent.com/50047029/189856324-18d5687b-e9e2-43fe-bc78-9e8379d63e17.png)

怀疑是版本适配问题，请问下1.12版本对应的hive-jdbc版本是多少， 
Driver: Hive JDBC (version 1.1.0-cdh5.16.1)这个版本要适配哪个版本的插件包？

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
hive 组件的版本你选择的1.x 还是2.x呢

**Comment by a2236802667** [comment]
哪个地方可以选择？

**Comment by a2236802667** [comment]
1.x版本
测试连接的时候报错了
![image](https://user-images.githubusercontent.com/50047029/189903162-237ed66a-20ca-4ec5-bc08-ddda8fb43471.png)

**Comment by vainhope** [comment]
tmp/hive目录权限给777呢

**Comment by a2236802667** [comment]
现在可以了，但是还是老问题，报最开始的错误

**Comment by vainhope** [comment]
com.dtstack.taier.develop.service.develop.runner.HiveSQLTaskRunner#componentTypeToDataSourceType
这个地方 默认是走对于的 1.x
你可以改成2.x 也试下 看是不是版本驱动不一致

**Comment by a2236802667** [comment]
@vainhope 读到的version为null
![image](https://user-images.githubusercontent.com/50047029/192467609-d2686000-4b96-4bfa-a88d-042c9bf54146.png)
