### ISSUE TITLE
[Question]taier 现在是内置flink1.12吗？还是需要另外关联？

### ISSUE THREAD

**Issue by wangzhen-wudangshan** [DTStack/Taier#761]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

1、taier 现在是内置flink1.12吗？
2、还是需要另外关联？
3、如果可以关联自己安装的flink的话，在哪里做配置？
4、数据同步向导模式，可以从两个源表进行join操作再同步到 一张表里面吗？
5、我按flink sql的语法标准编写 flink sql cdc 任务可以在taier上跑吗？也就是说支不支持原生的flink sql?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
1、taier 现在是内置flink1.12吗？
   taier没有内置1.12 
   相关flink的依赖包用的1.12的版本 以及 chunjun 1.2 要求对应的版本为flink 1.12
   可以说taier 当前仅支持flink 1.12 对版本有要求
2、还是需要另外关联？
   暂时没理解
3、如果可以关联自己安装的flink的话，在哪里做配置？
   通过flink组件的flinkJarPath配置flink jar 相关路径
4、数据同步向导模式，可以从两个源表进行join操作再同步到 一张表里面吗？
   是指多个相同结构表 聚合 同步到一张表里么 （mysql 分表 聚合同步到hive的类似场景）？
5、我按flink sql的语法标准编写 flink sql cdc 任务可以在taier上跑吗？也就是说支不支持原生的flink sql?
   目前还未支持flink 原生cdc 后续有计划
