### ISSUE TITLE
docker 容器启动不成功。

### ISSUE THREAD

**Issue by wheatma38** [DTStack/Taier#764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [x] I had searched my question on the internet but i didn't get any help.

- [x] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

1. 使用 docker-compose.yml 启动，提示以下信息：

 ⠿ Container taier-taier-db-1  Created                                                                                                         20.7s
 ⠿ Container taier-taier-zk-1  Created                                                                                                         20.7s
Attaching to taier-taier-1, taier-taier-db-1, taier-taier-ui-1, taier-taier-zk-1
taier-taier-db-1  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
taier-taier-1     | exec /bin/sh: exec format error
taier-taier-ui-1  | exec /bin/sh: exec format error
taier-taier-zk-1  | exec /docker-entrypoint.sh: exec format error
taier-taier-db-1 exited with code 1
taier-taier-1 exited with code 1
taier-taier-ui-1 exited with code 1
taier-taier-zk-1 exited with code 1
2. docker-compose 截图如下：

![image](https://user-images.githubusercontent.com/8164911/192102173-066e3832-4997-45c5-8e1f-55166f323592.png)

3.   https://dtstack.github.io/Taier/docs/quickstart/deploy/docker   中的 docker pull dtopensource/taier:latest 没有latest 版本。---- https://hub.docker.com/r/dtopensource/taier/tags

![image](https://user-images.githubusercontent.com/8164911/192102435-0f15ca6e-9ac3-4e02-994e-fa32ad16a86e.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
你单独起taier-taier-zk-1的镜像试下

**Comment by wheatma38** [comment]
docker logs taier-taier-zk-1
exec /docker-entrypoint.sh: exec format error
exec /docker-entrypoint.sh: exec format error

**Comment by wheatma38** [comment]
是的，其他镜像是正常的。

**Comment by wheatma38** [comment]
docker build  需要指定    --platform=linux/amd64 ？

export DOCKER_DEFAULT_PLATFORM=linux/amd64 

需要验证。
