### ISSUE TITLE
Hive1.X报错

### ISSUE THREAD

**Issue by a2236802667** [DTStack/Taier#766]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

![image](https://user-images.githubusercontent.com/50047029/192456636-76cd24c0-72fd-4f36-a86c-91d078831006.png)

![image](https://user-images.githubusercontent.com/50047029/192456713-048b2451-97ac-4313-9f54-f2008001efe9.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bnyte** [comment]
![image](https://user-images.githubusercontent.com/75556346/192457923-79b46d95-7115-41b2-93fd-4782316e887a.png)
这个位置请求参数中带有`id`你方便去数据库看看你的对应`任务id`这条数据的`sql_text`字段的值粘贴出来看看嘛

**Comment by hyperleoon** [comment]
see https://github.com/DTStack/Taier/issues/749

**Comment by a2236802667** [comment]
![image](https://user-images.githubusercontent.com/50047029/192459199-c06da6fc-f5a6-4d1d-bac6-726f40f212c9.png)
对应的表是啥？

**Comment by a2236802667** [comment]
![image](https://user-images.githubusercontent.com/50047029/192459888-b94e68a3-b69c-42ff-be2f-9e0e666e67e2.png)

**Comment by bnyte** [comment]
你好，在issue的 #749 已经解决了这个问题，已经merge到master你可以更新一下代码重新编译启动尝试一下呢
