### ISSUE TITLE
[Question][数据同步] MySQL同步到hive3，但目标端hive3不支持

### ISSUE THREAD

**Issue by SongGary** [DTStack/Taier#767]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

1. 完善flink-lib，增加hive3.1.2的jar包：
flink-connector-hive_2.11-1.12.7.jar
flink-sql-connector-hive-3.1.2_2.12-1.14.5.jar
hive-exec-3.1.2.jar
hive-jdbc-3.1.2.jar
hive-service-3.1.2.jar
libthrift-0.9.3.jar
2. 重新taier
3. 在webP平台研发数据同步任务
3.1 hive3.x数据源，测试通过
3.2 开发数据同步任务，设置源：mysql ,目标端：hive3
3.3 保存，报错：解析任务失败: 暂不支持该目标端

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiemotongxue** [comment]
@SongGary   任务开发的界面截图给我看下， 能选中hive3数据源？

**Comment by SongGary** [comment]
> @SongGary 任务开发的界面截图给我看下， 能选中hive3数据源？

可以选中，

**Comment by SongGary** [comment]
<img width="576" alt="hive3" src="https://user-images.githubusercontent.com/29721802/192487158-13d5d199-5317-4a9f-b436-ae3cde669f95.png">

**Comment by jiemotongxue** [comment]
问题：目前v1.2版本，没有开放对hive3数据同步的支持，但数据源那边可以添加，页面上也可以选择，这个是前端写死了的逻辑，是个bug。 

解决方案： 
1. 在当前1.3版本中已经将前端写死的改为后端控制，这个页面支持选择hive3就不会支持了，仍然没有开放hive3的支持。
2. 要使用hive3的方式，你可以将当前的任务转为脚本模式。 如果这个任务在chunjun里面已经调试通过了的，可以直接把任务文本复制过来，以脚本任务的方式去运行。

@SongGary

**Comment by jiemotongxue** [comment]
PR：  https://github.com/DTStack/Taier/pull/961
