### ISSUE TITLE
mysql2mysql同步任务失败报错

### ISSUE THREAD

**Issue by a2236802667** [DTStack/Taier#768]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

![image](https://user-images.githubusercontent.com/50047029/192507108-8bca114f-dbca-4324-94ee-0476b81d5ef4.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by a2236802667** [comment]
请问下咋解决？

**Comment by a2236802667** [comment]
![image](https://user-images.githubusercontent.com/50047029/192527429-d09d60a9-b951-4c1c-acfd-a2bb93d170ac.png)

**Comment by jiemotongxue** [comment]
你使用的chunjun插件是什么版本的？
@a2236802667

**Comment by a2236802667** [comment]
1.12 @jiemotongxue

**Comment by jiemotongxue** [comment]
@a2236802667   1.12有好几个tag号的，再具体一点，这个报错的意思看样子是logback 类冲突，我要复现下

**Comment by a2236802667** [comment]
v1.12.5 @jiemotongxue

**Comment by jiemotongxue** [comment]
ok

> v1.12.5 @jiemotongxue

**Comment by jiemotongxue** [comment]
@a2236802667   谢谢反馈的这个问题，我验证了问题是必现的；

原因：chunjun 的新版本在chunjun-core中将logback的依赖改为了provided；
![image](https://user-images.githubusercontent.com/16730029/192770111-d74105b1-1368-4f49-aaaa-470f4638d0ac.png)

临时解决方案：
将logback的2个jar 下载下来，放到flink_lib之下；

flink_lib的路径是控制台中配置的值
![image](https://user-images.githubusercontent.com/16730029/192770914-07ea251f-a906-4aa4-bd0d-5ab771fdbbdc.png)


logback的2个jar下载地址：
https://mvnrepository.com/artifact/ch.qos.logback/logback-core/1.2.11
![image](https://user-images.githubusercontent.com/16730029/192770384-015d69b8-3b42-405c-9dfc-354bfd90a603.png)

https://mvnrepository.com/artifact/ch.qos.logback/logback-classic/1.2.11

**Comment by a2236802667** [comment]
感谢，已解决。
