### ISSUE TITLE
数据源类型分类是杂乱错误的

### ISSUE THREAD

**Issue by itWMdeveloping** [DTStack/Taier#769]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/43467953/192725437-8f7f02b6-6948-4e4a-8fad-2c1d2b8bbb28.png)

### What you expected to happen

数据源分类需要调整

### How to reproduce

创建数据源的时候选择数据源类型，分类不正确

### Version

v.12

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
修复 在1.3
