### ISSUE TITLE
创建 api数据源：websocket、socket，提示“数据源类型不存在”

### ISSUE THREAD

**Issue by windwhisper-i** [DTStack/Taier#779]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

创建 api数据源：websocket、socket，提示“数据源类型不存在”

### What you expected to happen

通过api接口，把数据导入到taier数据库中

### How to reproduce

![image](https://user-images.githubusercontent.com/73170854/195083114-eda4827a-eea2-4df7-b8d6-dba6cab300b6.png)

### Version

v1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
修复on 1.3
