### ISSUE TITLE
[Bug] [任务开发] 工作流任务保存后回显不正确

### ISSUE THREAD

**Issue by StrangeXin** [DTStack/Taier#780]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

保存前关系如下<img width="923" alt="image" src="https://user-images.githubusercontent.com/6157378/195292178-caabe30e-e566-4be5-940d-ab41d36bea8b.png">
保存后重新打开，丢失了s2指向s3的一条线
<img width="867" alt="image" src="https://user-images.githubusercontent.com/6157378/195292428-e218db02-82cd-4505-b60c-98383f263bcb.png">

### What you expected to happen

保存数据时就丢掉了正确的关系，回显时解析不出来

### How to reproduce

如图添加几个节点测试即可

### Version

v.12

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by StrangeXin** [comment]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/6157378/195783553-87007e38-a2e7-49b8-bf5a-e1533e647664.png">
对应的依赖视图里面的内容也看下是不是准确的

**Comment by StrangeXin** [comment]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/6157378/195826359-cef017ff-8fe1-4a79-a338-e19b4a4f5500.png">

<img width="787" alt="image" src="https://user-images.githubusercontent.com/6157378/195826193-7feb3437-a1fe-4faa-b2ce-64df2d8ec49d.png">
这种复杂情况下，依赖视图里面出现了一个未知父节点，我是在1.2版本里，不知道1.3是否还有此问题，请排查一下

**Comment by mortalYoung** [comment]
![2022-10-17 10-39-42 2022-10-17 10_40_37](https://user-images.githubusercontent.com/18719701/196077663-55037915-426d-4f1f-bc8e-f0411ea5f9ed.gif)

在 fix/workflow 的分支暂时无法复现，你可以排查一下是接口数据的问题吗

**Comment by StrangeXin** [comment]
是接口数据没有返回上级的节点
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/6157378/196080762-bc181467-5f1f-4014-84b9-78fb2e4b490c.png">
我让后端同步下代码看下
