### ISSUE TITLE
[Question]调度支持重试吗？

### ISSUE THREAD

**Issue by melin** [DTStack/Taier#850]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

调度支持重试吗？例如失败重试2次，任务优先级，单个用户最大并发数量，防止单个用户占用太多资源等特性

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by melin** [comment]
重试怎么设计的？ 定时轮训方式，检测失败状态作业？

**Comment by melin** [comment]
![image](https://user-images.githubusercontent.com/1145830/199669733-72f460e4-6c77-40a2-9be5-9e2d33a3256e.png)

**Comment by vainhope** [comment]
重试根据任务的执行的状态来
状态为失败之后 会丢回内存延时队列
延时到期之后 再来take出来执行

上下游一层任务之间的依赖关系 
上游任务全部执行完之后。下游才满足执行条件

**Comment by melin** [comment]
嗯，延迟队列是不错方式。以前采用轮训数据库方式，阿里云dataworker 也是寻轮数据库的。

**Comment by vainhope** [comment]
具体的代码这个这里 com.dtstack.taier.scheduler.jobdealer.JobSubmitDealer.RestartJobProcessor
可以提供一些建议

轮训数据库方式的好处 在于重试过程中 对任务进行人为操作 状态比较好处理

**Comment by melin** [comment]
> 具体的代码这个这里 com.dtstack.taier.scheduler.jobdealer.JobSubmitDealer.RestartJobProcessor 可以提供一些建议
> 
> 轮训数据库方式的好处 在于重试过程中 对任务进行人为操作 状态比较好处理

轮训比较简单，例如：任务优先级，单个人最大并发任务数量控制等需求，控制补数据数量等特殊场景，通过队列控制还是比较麻烦的。

**Comment by vainhope** [comment]
当前只限制到了 集群-任务类型  还没有到用户
后续有扩展的话 可以参考这种方式来处理

**Comment by melin** [comment]
> 当前只限制到了 集群-任务类型 还没有到用户 后续有扩展的话 可以参考这种方式来处理
 延迟队列，用到什么MQ 中间件？

**Comment by vainhope** [comment]
内存延迟
com.dtstack.taier.common.queue.DelayBlockingQueue

**Comment by melin** [comment]
> 内存延迟 com.dtstack.taier.common.queue.DelayBlockingQueue

应用重启内存数据丢失，怎么解决？

**Comment by vainhope** [comment]
回去数据库重新恢复重试标识和次数

**Comment by melin** [comment]
你们内部版本和开源版本有差别吗？ 两套代码维护？ 开源代码是专职人员维护？

**Comment by vainhope** [comment]
开源和商业版是二套完全不一样的代码
商业版的功能更多

**Comment by melin** [comment]
> 开源和商业版是二套完全不一样的代码 商业版的功能更多

是同一个团队维护，还是独立开的？你们有专门开源团队？两套代码，维护有一定工作量。
