### ISSUE TITLE
[Bug] [SQL任务执行] 多条sql任务提交执行报错

### ISSUE THREAD

**Issue by chyueyi** [DTStack/Taier#857]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened
![image](https://user-images.githubusercontent.com/35141460/200117933-4438c3eb-c896-423e-b27b-89771c17c121.png)

![image](https://user-images.githubusercontent.com/35141460/200115492-12d8f5d7-36e3-4916-8986-c1000172ff7a.png)
1、当执行多条sql时，代码里将SQL未进行拆分直接请求，导致执行报错

![image](https://user-images.githubusercontent.com/35141460/200117436-f9e4490c-c10b-450e-b8d4-29718c0f21b6.png)

2、当多条查询语句一起查时，只会返回最后一个的执行结果
3、当存在查询语句和非查询语句一起查询时，如果最后一个是非查询语句则会报错

### What you expected to happen

如上

### How to reproduce

如上

### Version

v1.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
多sql执行的时候 
 
![image](https://user-images.githubusercontent.com/18212930/200222162-730bba25-ad33-4919-ad0f-852bbbfa269b.png)
前端会去分割请求


![image](https://user-images.githubusercontent.com/18212930/200222209-c20c6719-98d8-46c4-99d2-7c3190388a08.png)
![image](https://user-images.githubusercontent.com/18212930/200222226-8de372a2-4129-4e53-86ff-4b1aa346f3fe.png)


结果也是正常展示的 
想问下 你的触发方式是

**Comment by chyueyi** [comment]
参考OceanBase新增了JDBC任务类型，需要修改前端代码吗 @vainhope

**Comment by vainhope** [comment]
SQL 任务都是统一的模版化了 不需要前端的支持的
如果自定义开发中 有问题可以一起讨论
欢迎pr

**Comment by chyueyi** [comment]
自定义任务需要在前端添加配置
