### ISSUE TITLE
[Feature] Support HadoopMR

### ISSUE THREAD

**Issue by jiemotongxue** [DTStack/Taier#858]
1. 增加MR 的前端界面2
2. 增加Jar的上传
3. 提交MR on Yarn 任务

**Comment by jiemotongxue** [comment]
@mortalYoung    有时间支持一下Spark MR的前端页面吗？ 后端我来

**Comment by mortalYoung** [comment]
> @mortalYoung 有时间支持一下MR的前端页面吗？ 后端我来

阔以
