### ISSUE TITLE
[Bug] [flinksql] 向导模式语法检查报错不支持的表类型

### ISSUE THREAD

**Issue by ghm02708** [DTStack/Taier#864]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/91457562/200723042-b036c798-fdbe-4369-a394-c196f303fd46.png)

### What you expected to happen

语法检查阶段

### How to reproduce

语法检查阶段

### Version

v1.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ghm02708** [comment]
#867

**Comment by weaksloth** [comment]
在最新的master代码和1.4版本里进行校验操作我也会出现这个问题，请问是不是后续有什么修改导致的呢还是我哪里配置的不对？
