### ISSUE TITLE
[Bug] [自定义参数] 自定义组件无法识别代码中的自定义参数

### ISSUE THREAD

**Issue by chyueyi** [DTStack/Taier#879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

自定义组件无法识别出SQL代码中的参数
![image](https://user-images.githubusercontent.com/35141460/201593667-db0f1521-fccf-458d-b049-e106389e68e6.png)

### What you expected to happen

像Doris SQL任务一样，可以在自定义参数中识别。
![image](https://user-images.githubusercontent.com/35141460/201593776-6cb53a0c-1ee5-467c-9862-4a953c75e063.png)

### How to reproduce

如上

### Version

v1.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mortalYoung** [comment]
目前自定义参数的识别是写在 https://github.com/DTStack/Taier/blob/b0e7301a8f3c08abfb651a052179e99fbd3ce2ff/taier-ui/src/extensions/editor/index.tsx#L259-L285 可以暂时在这里加上自定义组件的枚举值，后续我们会优化这里的逻辑

**Comment by chyueyi** [comment]
@mortalYoung 好的，感谢
