### ISSUE TITLE
[Feature][组件配置] Script增加本地运行模式

### ISSUE THREAD

**Issue by chyueyi** [DTStack/Taier#880]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar feature requirement.

### Description

目前要执行shell和python任务，必须要先配置HDFS和YARN，希望能够增加一个Script local版本，可以直接调度shell和python任务，减少组件直接的依赖。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jiemotongxue** [comment]
+1
