### ISSUE TITLE
[Feature]FTP source and target supported on sync task type

### ISSUE THREAD

**Issue by bnyte** [DTStack/Taier#897]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar feature requirement.

### Description

FTP source and target supported on sync task type

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bnyte** [comment]
@mortalYoung hi man! do you have time? Is there time to support the source and target frontend pages of FTP?

**Comment by mortalYoung** [comment]
I'll cut my time to work on it recently :)

**Comment by bnyte** [comment]
![image](https://user-images.githubusercontent.com/75556346/203003410-0fccf628-2ad5-4d93-9aa4-8ae1e93bc262.png)
ftp to ftp local test success for backend
