### ISSUE TITLE
运行shell任务执行服务器sh脚本，任务一直在running卡死

### ISSUE THREAD

**Issue by itWMdeveloping** [DTStack/Taier#898]
### Search before asking

- [x] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

我有一个测试脚本test.sh，在服务器直接运行test.sh任务可以运行成功，脚本内容如下spark-submit --master yarn --deploy-mode client --num-executors 3 --executor-memory 1g --executor-cores 3 --driver-memory 1g --class com.nokia.doo.tagcenter.dsggq  /data/beier_tagcenter_xdr_mr-1.0-SNAPSHOT.jar /insight/script/staging/application_1661828259151_0004 /wzp/result3，
但是在taier上运行shell任务执行test.sh控制台会一直在运行中，
shell任务的参数都配置好了，比如运行test2.sh, 内容如下echo 112233 > /tmp/res.log，这样的可以运行成功。
![企业微信截图_16685866853664](https://user-images.githubusercontent.com/43467953/202127087-9cc56127-c607-4906-a3a4-6b3b30a1fdf4.png)
taier.err报错如下：
![企业微信截图_16685867024439](https://user-images.githubusercontent.com/43467953/202127180-f14400fc-86e2-44df-a009-4fef0a4a7c50.png)
从hadoop上看任务状态一直在running，没有日志：
![image](https://user-images.githubusercontent.com/43467953/202127551-363b3f69-b5f2-4de4-8673-837dc80ceebe.png)
![image](https://user-images.githubusercontent.com/43467953/202127595-34e2686b-5da8-4ece-aacb-5c23eec83e84.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
![image](https://user-images.githubusercontent.com/18212930/202134794-0942b56d-08e6-4277-82bc-0679aba20b5f.png)
 可以贴一下么

**Comment by itWMdeveloping** [comment]
master.log:
![image](https://user-images.githubusercontent.com/43467953/202137489-99f18f0b-c785-4372-a5cf-6a5e38fbc904.png)
master.err
![image](https://user-images.githubusercontent.com/43467953/202137711-2602737d-eaab-4720-a500-1ee46d1fda72.png)
prelaunch.out：
![image](https://user-images.githubusercontent.com/43467953/202137882-d8628d5e-c1eb-429d-9a0d-d10e74d8b0c6.png)

**Comment by vainhope** [comment]
shell 任务的结束 需要gh.sh的脚本结束才会正常退出
你比对下gh.sh 手动执行  和提交到yarn 执行时间差别大么

**Comment by itWMdeveloping** [comment]
时间几乎没什么差别

**Comment by vainhope** [comment]
正常情况下 container会伴随着脚本执行完后退出
可以确认下 执行的gh.sh 脚本任务在yarn上是否已经结束

**Comment by itWMdeveloping** [comment]
![image](https://user-images.githubusercontent.com/43467953/203006090-9ae2ebd9-a6de-49ec-9060-6eb261d0f8fb.png)
shell任务一直在running，然后脚本里的spark任务就一直在accept状态

**Comment by vainhope** [comment]
应该是 脚本里的spark任务 一直提交不上去 卡在accept状态 shell就一直runing
你可以上节点排查下 gb.sh 为啥会提交不上去
