### ISSUE TITLE
配置【增量数据同步任务】选择表名后报序列化错误

### ISSUE THREAD

**Issue by Sejon** [DTStack/Taier#903]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### 问题描述
配置数据同步任务 ，同步模式选择“有增量标识”,配置数据来源选择表名的时候会报如下错误
### 问题截图
![d695130216438e043203c990b89f8eb](https://user-images.githubusercontent.com/33147746/202399817-93d3b6e0-f7d7-42d3-adbe-1958fe4442e4.jpg)
![290aba325c41d30c0ac9bf3c8a0b591](https://user-images.githubusercontent.com/33147746/202399861-fd90eef2-426c-4fdc-9518-989a4fc932de.jpg)

### What you expected to happen

不报错，正常操作

### How to reproduce

修复bug

### Version

v1.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vainhope** [comment]
isql 里面未更正
可以参考 https://github.com/DTStack/Taier/issues/260#issuecomment-1306755666 修复
