### ISSUE TITLE
[bug]数据同步任务写入模式

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/Taier#910]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

目前数据同步中的写入模式，前端统一都是传的 `replace` 和 `insert`，前者表示 「覆盖（Insert Overwrite）」后者表示「追加（Insert Into）」

但是目前发现 chunjun 里面不同的数据源 writeMode 的值是不一样的，不确定服务端是否有做一层转义，如果没有希望做一下。

涉及的 writer 端数据源：Oracle, POSTGRESQL HDFS HIVE FTP CLICKHOUSE HIVE1X SPARKTHRIFT HIVE3X

### What you expected to happen

期望服务端能把数据结构磨平，因为不论是 replace overwrite 其实都表示同一个东西，即使是传 0 或 1 也没问题，只要能统一就可以。

### How to reproduce

。

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bnyte** [comment]
i will review this issue of the backend

**Comment by bnyte** [comment]
### oracle

- mode param: mode
- target value: insert and replace

### POSTGRESQL

- mode param: writeMode
- target value: insert and replace

### hdfs@stream_hdfs_orc

- mode param: writeMode
- target value: overwrite 

> But it is not clear what the added value is, and chunjun is required to provide document support

### FTP

- mode param: writeMode
- target value: append and overwrite

### CLICKHOUSE

- mode param: writeMode
- target value: overwrite

> But it is not clear what the added value is, and chunjun is required to provide document support
