### ISSUE TITLE
登录报错：该租户对应集群未配置任何组件

### ISSUE THREAD

**Issue by caosuwenwu** [DTStack/Taier#927]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

快速上手不够完善

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bnyte** [comment]
你好，你那里有问题呢

**Comment by bnyte** [comment]
该租户对应集群未配置任何组件问题 需要你在`控制台` -> `资源管理` -> `绑定集群`操作就可以了

**Comment by bnyte** [comment]
长期没有回复，暂时关闭issue，如果有问题请再次打开它
