### ISSUE TITLE
Mysql数据同步到Hive分区表，同步成功后，读取Hive分区表数据为空，Hdfs上数据已落地生成

### ISSUE THREAD

**Issue by a2236802667** [DTStack/Taier#951]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description
Taier master分支
Hive版本1.X，
数据同步成功后，使用select * from 分区表，数据查询不到。
hive shell使用 msck repair table  分区表，修复元数据再次查询，数据查询成功。

写入非分区表，使用select * from 分区表，数据查询成功。

麻烦看下这个问题，谢谢！

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by a2236802667** [comment]
请问有修复的计划吗？

**Comment by binfen1990** [comment]
我也是遇到这个问题，在1.3版更新后，同步到hive，无分区数据

**Comment by vainhope** [comment]
直接使用chunjun写入 可以正常读取么 @a2236802667
