### ISSUE TITLE
[Bug] [任务开发] 删除任务开发根目录下的任意任务后，再点击新建文件夹无反应，控制台报错

### ISSUE THREAD

**Issue by StrangeXin** [DTStack/Taier#952]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar issues.

### What happened

<img width="657" alt="image" src="https://user-images.githubusercontent.com/6157378/208078618-2ef0da1d-04d0-45c6-b397-a9e36fc673da.png">
如图，新建任务->删除任务->新建文件夹，无反应

### What you expected to happen

删除时改变了树结构

### How to reproduce

新建任务->删除任务->新建文件夹

### Version

v1.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by StrangeXin** [comment]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/6157378/208218761-891e5045-d163-403d-a363-a21df6f5ab2f.png">
选中根目录下某个任务，点击新建文件夹（根目录下）输入文件夹名后没法保存，回车也没反应
应该
<img width="577" alt="image" src="https://user-images.githubusercontent.com/6157378/208218830-ea9dd1ae-2f35-4719-8605-b2d0a62c498b.png">

**Comment by bnyte** [comment]
@StrangeXin 你好 你更新一下版本看看呢
