### ISSUE TITLE
1.3不支持hana数据库么，chunjun1.27是支持sap-hana

### ISSUE THREAD

**Issue by zqsgithub2023** [DTStack/Taier#986]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [ ] I had searched my question on the internet but i didn't get any help.

- [ ] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

1.3不支持hana数据库么，chunjun1.27是支持sap-hana。

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bnyte** [comment]
数据同步目前还没有支持奥
